// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RMT.Employee.Infrastructure.Data;

#nullable disable

namespace RMT.Employee.Infrastructure.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20231227141024_new db")]
    partial class newdb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RMT.Employee.Domain.Entities.EmployeePreference", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmployeeEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferenceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferenceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EmployeePreferences");
                });

            modelBuilder.Entity("RMT.Employee.Domain.Entities.PreferenceMaster", b =>
                {
                    b.Property<long>("PreferenceMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PreferenceMasterId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("PreferenceMasterId");

                    b.ToTable("PreferenceMasters");

                    b.HasData(
                        new
                        {
                            PreferenceMasterId = 100L,
                            Category = "LOCATION",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3391),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3396),
                            ModifiedBy = "System",
                            Name = "Noida",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 101L,
                            Category = "LOCATION",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3404),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3404),
                            ModifiedBy = "System",
                            Name = "Delhi",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 102L,
                            Category = "LOCATION",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3409),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3409),
                            ModifiedBy = "System",
                            Name = "Pune",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 103L,
                            Category = "LOCATION",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3413),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3414),
                            ModifiedBy = "System",
                            Name = "Lucknow",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 104L,
                            Category = "LOCATION",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3418),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3418),
                            ModifiedBy = "System",
                            Name = "Hydrabad",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 105L,
                            Category = "LOCATION",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3423),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3423),
                            ModifiedBy = "System",
                            Name = "Jaipur",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 106L,
                            Category = "SME",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3428),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3429),
                            ModifiedBy = "System",
                            Name = "SME 1",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 107L,
                            Category = "SME",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3433),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3433),
                            ModifiedBy = "System",
                            Name = "SME 2",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 108L,
                            Category = "SME",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3437),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3437),
                            ModifiedBy = "System",
                            Name = "SME 3",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 109L,
                            Category = "SME",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3441),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3441),
                            ModifiedBy = "System",
                            Name = "SME 4",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 110L,
                            Category = "SME",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3446),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3447),
                            ModifiedBy = "System",
                            Name = "SME 5",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 111L,
                            Category = "REVENUE_UNIT",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3451),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3451),
                            ModifiedBy = "System",
                            Name = "REVENUE UNIT 1",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 112L,
                            Category = "REVENUE_UNIT",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3455),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3456),
                            ModifiedBy = "System",
                            Name = "REVENUE UNIT 2",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 113L,
                            Category = "REVENUE_UNIT",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3459),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3460),
                            ModifiedBy = "System",
                            Name = "REVENUE UNIT 3",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 114L,
                            Category = "REVENUE_UNIT",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3463),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3464),
                            ModifiedBy = "System",
                            Name = "REVENUE UNIT 4",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 115L,
                            Category = "REVENUE_UNIT",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3467),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3468),
                            ModifiedBy = "System",
                            Name = "REVENUE UNIT 5",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 116L,
                            Category = "EXPERTISE",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3472),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3473),
                            ModifiedBy = "System",
                            Name = "EXPERTISE 1",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 117L,
                            Category = "EXPERTISE",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3476),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3477),
                            ModifiedBy = "System",
                            Name = "EXPERTISE 2",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 118L,
                            Category = "EXPERTISE",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3480),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3481),
                            ModifiedBy = "System",
                            Name = "EXPERTISE 3",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 119L,
                            Category = "EXPERTISE",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3486),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3487),
                            ModifiedBy = "System",
                            Name = "EXPERTISE 4",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 120L,
                            Category = "EXPERTISE",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3490),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3490),
                            ModifiedBy = "System",
                            Name = "EXPERTISE 5",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 121L,
                            Category = "ENGAGEMENT_LEADER",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3593),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3594),
                            ModifiedBy = "System",
                            Name = "Samarth Mathur",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 122L,
                            Category = "ENGAGEMENT_LEADER",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3598),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3598),
                            ModifiedBy = "System",
                            Name = "Manish Karl",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 123L,
                            Category = "ENGAGEMENT_LEADER",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3602),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3602),
                            ModifiedBy = "System",
                            Name = "Devang Sharma",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 124L,
                            Category = "ENGAGEMENT_LEADER",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3606),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3606),
                            ModifiedBy = "System",
                            Name = "Abhishake Kumar",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 125L,
                            Category = "ENGAGEMENT_LEADER",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3610),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3611),
                            ModifiedBy = "System",
                            Name = "Shristi",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 126L,
                            Category = "BUISNESS_UNIT",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3614),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3615),
                            ModifiedBy = "System",
                            Name = "Business Unit 1",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 127L,
                            Category = "BUISNESS_UNIT",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3619),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3619),
                            ModifiedBy = "System",
                            Name = "Business Unit 2",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 128L,
                            Category = "BUISNESS_UNIT",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3623),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3624),
                            ModifiedBy = "System",
                            Name = "Business Unit 3",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 129L,
                            Category = "BUISNESS_UNIT",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3628),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3629),
                            ModifiedBy = "System",
                            Name = "Business Unit 4",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 130L,
                            Category = "BUISNESS_UNIT",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3632),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3633),
                            ModifiedBy = "System",
                            Name = "Business Unit 5",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 131L,
                            Category = "INDUSTRY",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3636),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3637),
                            ModifiedBy = "System",
                            Name = "Industry 1",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 132L,
                            Category = "INDUSTRY",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3640),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3641),
                            ModifiedBy = "System",
                            Name = "Industry 2",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 133L,
                            Category = "INDUSTRY",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3644),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3644),
                            ModifiedBy = "System",
                            Name = "Industry 3",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 134L,
                            Category = "INDUSTRY",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3648),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3648),
                            ModifiedBy = "System",
                            Name = "Industry 4",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 135L,
                            Category = "INDUSTRY",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3652),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3652),
                            ModifiedBy = "System",
                            Name = "Industry 5",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 136L,
                            Category = "SECTOR",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3656),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3656),
                            ModifiedBy = "System",
                            Name = "Sector 1",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 137L,
                            Category = "SECTOR",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3661),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3661),
                            ModifiedBy = "System",
                            Name = "Sector 2",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 138L,
                            Category = "SECTOR",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3664),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3665),
                            ModifiedBy = "System",
                            Name = "Sector 3",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 139L,
                            Category = "SECTOR",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3669),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3669),
                            ModifiedBy = "System",
                            Name = "Sector 4",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 140L,
                            Category = "SECTOR",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3672),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 10, 24, 98, DateTimeKind.Utc).AddTicks(3673),
                            ModifiedBy = "System",
                            Name = "Sector 5",
                            SortOrder = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
