// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RMT.Employee.Infrastructure.Data;

#nullable disable

namespace RMT.Employee.Infrastructure.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20231227142821_new db 1")]
    partial class newdb1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RMT.Employee.Domain.Entities.EmployeePreference", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmployeeEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferenceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferenceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PreferenceOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("EmployeePreferences");
                });

            modelBuilder.Entity("RMT.Employee.Domain.Entities.PreferenceMaster", b =>
                {
                    b.Property<long>("PreferenceMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PreferenceMasterId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("PreferenceMasterId");

                    b.ToTable("PreferenceMasters");

                    b.HasData(
                        new
                        {
                            PreferenceMasterId = 100L,
                            Category = "LOCATION",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(776),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(780),
                            ModifiedBy = "System",
                            Name = "Noida",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 101L,
                            Category = "LOCATION",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(787),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(788),
                            ModifiedBy = "System",
                            Name = "Delhi",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 102L,
                            Category = "LOCATION",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(792),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(793),
                            ModifiedBy = "System",
                            Name = "Pune",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 103L,
                            Category = "LOCATION",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(797),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(798),
                            ModifiedBy = "System",
                            Name = "Lucknow",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 104L,
                            Category = "LOCATION",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(801),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(802),
                            ModifiedBy = "System",
                            Name = "Hydrabad",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 105L,
                            Category = "LOCATION",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(805),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(806),
                            ModifiedBy = "System",
                            Name = "Jaipur",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 106L,
                            Category = "SME",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(810),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(811),
                            ModifiedBy = "System",
                            Name = "SME 1",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 107L,
                            Category = "SME",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(815),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(816),
                            ModifiedBy = "System",
                            Name = "SME 2",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 108L,
                            Category = "SME",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(820),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(821),
                            ModifiedBy = "System",
                            Name = "SME 3",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 109L,
                            Category = "SME",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(825),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(825),
                            ModifiedBy = "System",
                            Name = "SME 4",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 110L,
                            Category = "SME",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(830),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(831),
                            ModifiedBy = "System",
                            Name = "SME 5",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 111L,
                            Category = "REVENUE_UNIT",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(835),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(835),
                            ModifiedBy = "System",
                            Name = "REVENUE UNIT 1",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 112L,
                            Category = "REVENUE_UNIT",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(839),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(840),
                            ModifiedBy = "System",
                            Name = "REVENUE UNIT 2",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 113L,
                            Category = "REVENUE_UNIT",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(843),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(844),
                            ModifiedBy = "System",
                            Name = "REVENUE UNIT 3",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 114L,
                            Category = "REVENUE_UNIT",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(848),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(849),
                            ModifiedBy = "System",
                            Name = "REVENUE UNIT 4",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 115L,
                            Category = "REVENUE_UNIT",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(853),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(854),
                            ModifiedBy = "System",
                            Name = "REVENUE UNIT 5",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 116L,
                            Category = "EXPERTISE",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(857),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(858),
                            ModifiedBy = "System",
                            Name = "EXPERTISE 1",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 117L,
                            Category = "EXPERTISE",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(862),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(862),
                            ModifiedBy = "System",
                            Name = "EXPERTISE 2",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 118L,
                            Category = "EXPERTISE",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(866),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(866),
                            ModifiedBy = "System",
                            Name = "EXPERTISE 3",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 119L,
                            Category = "EXPERTISE",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(871),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(872),
                            ModifiedBy = "System",
                            Name = "EXPERTISE 4",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 120L,
                            Category = "EXPERTISE",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(875),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(876),
                            ModifiedBy = "System",
                            Name = "EXPERTISE 5",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 121L,
                            Category = "ENGAGEMENT_LEADER",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(881),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(882),
                            ModifiedBy = "System",
                            Name = "Samarth Mathur",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 122L,
                            Category = "ENGAGEMENT_LEADER",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(886),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(886),
                            ModifiedBy = "System",
                            Name = "Manish Karl",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 123L,
                            Category = "ENGAGEMENT_LEADER",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(890),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(891),
                            ModifiedBy = "System",
                            Name = "Devang Sharma",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 124L,
                            Category = "ENGAGEMENT_LEADER",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(894),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(895),
                            ModifiedBy = "System",
                            Name = "Abhishake Kumar",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 125L,
                            Category = "ENGAGEMENT_LEADER",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(898),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(899),
                            ModifiedBy = "System",
                            Name = "Shristi",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 126L,
                            Category = "BUISNESS_UNIT",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(903),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(904),
                            ModifiedBy = "System",
                            Name = "Business Unit 1",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 127L,
                            Category = "BUISNESS_UNIT",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(908),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(909),
                            ModifiedBy = "System",
                            Name = "Business Unit 2",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 128L,
                            Category = "BUISNESS_UNIT",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(913),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(913),
                            ModifiedBy = "System",
                            Name = "Business Unit 3",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 129L,
                            Category = "BUISNESS_UNIT",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(917),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(918),
                            ModifiedBy = "System",
                            Name = "Business Unit 4",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 130L,
                            Category = "BUISNESS_UNIT",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(921),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(922),
                            ModifiedBy = "System",
                            Name = "Business Unit 5",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 131L,
                            Category = "INDUSTRY",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(926),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(926),
                            ModifiedBy = "System",
                            Name = "Industry 1",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 132L,
                            Category = "INDUSTRY",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(930),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(931),
                            ModifiedBy = "System",
                            Name = "Industry 2",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 133L,
                            Category = "INDUSTRY",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(935),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(936),
                            ModifiedBy = "System",
                            Name = "Industry 3",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 134L,
                            Category = "INDUSTRY",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(940),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(941),
                            ModifiedBy = "System",
                            Name = "Industry 4",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 135L,
                            Category = "INDUSTRY",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(944),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(945),
                            ModifiedBy = "System",
                            Name = "Industry 5",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 136L,
                            Category = "SECTOR",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(948),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(949),
                            ModifiedBy = "System",
                            Name = "Sector 1",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 137L,
                            Category = "SECTOR",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(953),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(953),
                            ModifiedBy = "System",
                            Name = "Sector 2",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 138L,
                            Category = "SECTOR",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(957),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(957),
                            ModifiedBy = "System",
                            Name = "Sector 3",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 139L,
                            Category = "SECTOR",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(961),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(962),
                            ModifiedBy = "System",
                            Name = "Sector 4",
                            SortOrder = 10
                        },
                        new
                        {
                            PreferenceMasterId = 140L,
                            Category = "SECTOR",
                            CreatedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(965),
                            CreatedBy = "System",
                            Description = "String",
                            IsActive = true,
                            ModifiedAt = new DateTime(2023, 12, 27, 14, 28, 21, 699, DateTimeKind.Utc).AddTicks(966),
                            ModifiedBy = "System",
                            Name = "Sector 5",
                            SortOrder = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
