using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using RMT.Notification.Domain.Entities;
using RMT.Notification.Infrastructure.Constants;
using RMT.Notification.Infrastructure.Seeder;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Reflection;
using System.Reflection.Emit;
using System.Security;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Linq;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace RMT.Notification.Infrastructure.Data
{
    public class NotificationDbContext : DbContext
    {
        public NotificationDbContext(DbContextOptions<NotificationDbContext> options) : base(options)
        {
        }

        protected override void OnConfiguring(DbContextOptionsBuilder options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            //Add Template Data using seeder method
            PopulateNotificationTemplateDate(modelBuilder);
            PopulateNotificationLink(modelBuilder);

        }

        private static object PopulateNotificationTemplateDate(ModelBuilder modelBuilder)
        {
            return modelBuilder.Entity<NotificationTemplate>()
            .HasData(
            new NotificationTemplate
            {
                Id = 315,
                module = "Notification",
                sub_module = "Notification",
                subject = "Allocation conflicts for <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>",
                type = "ALLOCATION_CONFLICT_NOTIFICATION",
                is_active = true,
                notification_type = "PUSH",
                to = "ResourceRequestor,Reviewer,AdditionalEl,AdditionalDelegate",
                template = @"Employee <<empEmail:ResourceAllocationDetails:item_id>> is not available on the allocated dates for the project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>.
Kindly update the allocations accordingly.",
                link_id = 16,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 314,
                module = "Notification",
                sub_module = "Notification",
                subject = "Allocation conflicts for <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>",
                type = "EMPLOYEE_ABSCONDING_NOTIFCATION",
                is_active = true,
                notification_type = "PUSH",
                to = "ResourceRequestor,Reviewer,AdditionalEl,AdditionalDelegate",
                template = @"Employee <<empEmail:ResourceAllocationDetails:item_id>> is not available on the allocated dates for the project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>.
Kindly update the allocations accordingly.",
                link_id = 16,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 313,
                module = "Notification",
                sub_module = "Notification",
                subject = "Allocation conflicts for <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>",
                type = "EMPLOYEE_ABSCONDING_NOTIFCATION",
                is_active = true,
                notification_type = "EMAIL",
                to = "ResourceRequestor,Reviewer,AdditionalEl,AdditionalDelegate",
                template = @"Dear User,<br/><br/>
Allocation conflicts in the project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> as Employee: <<empEmail:ResourceAllocationDetails:item_id>> is not available.<br/><br/>
Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=3'>click here</a> to review allocation detail and kindly update the allocations.<br/><br/>
Regards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 312,
                module = "Notification",
                sub_module = "Notification",
                subject = "Skill Assessment Review Updates",
                type = "SUPERCOACH_ACCEPTED_SKILL_ASSESSMENT_REQUEST",
                is_active = true,
                notification_type = "PUSH",
                to = "userskillemail",
                template = @"Your Skill Review request has been actioned.",
                link_id = 1,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 311,
                module = "Notification",
                sub_module = "Notification",
                subject = "Skill Assessment Review Updates",
                type = "SUPERCOACH_ACCEPTED_SKILL_ASSESSMENT_REQUEST",
                is_active = true,
                notification_type = "EMAIL",
                to = "userskillemail",
                template = @"Dear User,<br/><br/>
Your skill self-assessment request for the following skill has been approved by your Supercoach 
<<updated_by>>. <br/><br/>
Skill Name : <<skillname:UserSkill:item_id>><br/>
Skill Proficiency Level : <<Proficiency:UserSkill:item_id>><br/><br/>
Please <a href='<<BaseUrl:config>>myskill'>click here</a> for the details.<br/><br/>
Regards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 310,
                module = "Notification",
                sub_module = "Notification",
                subject = "Allocation conflicts for <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>",
                type = "ALLOCATION_CONFLICT_NOTIFICATION",
                is_active = true,
                notification_type = "EMAIL",
                to = "ResourceRequestor,Reviewer,AdditionalEl,AdditionalDelegate",
                template = @"Dear User,<br/><br/>
Allocation conflict for Employee: <<empEmail:ResourceAllocationDetails:item_id>> as the employee is not available.<br/><br/>
Kindly update the allocations accordingly.<br/><br/>
Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=3'>click here</a> for the details.<br/><br/>
Regards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 309,
                module = "Notification",
                sub_module = "Notification",
                subject = "Allocation conflicts for <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>",
                type = "EMPLOYEE_LEAVE_NOTIFCATION",
                is_active = true,
                notification_type = "PUSH",
                to = "ResourceRequestor,Reviewer,AdditionalEl,AdditionalDelegate",
                template = @"Employee <<employeeemail:ResourceAllocationDetails:item_id>> is not available on the allocated dates for the project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>>.
Kindly update the allocations accordingly.",
                link_id = 16,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 308,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> Budget Updates",
                type = "PROJECT_BUDGET_NOTIFICATION",
                is_active = true,
                notification_type = "PUSH",
                to = "ResourceRequestor,Reviewer",
                template = @"Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> has consumed <<Limit:GETPROJECTBUDGET:pipelineCode|jobCode>> % of the budget in allocations.",
                link_id = 15,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 307,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> Budget Updates",
                type = "PROJECT_BUDGET_NOTIFICATION",
                is_active = true,
                notification_type = "EMAIL",
                to = "ResourceRequestor,Reviewer",
                template = @"Dear User,<br/><br/>
Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> has consumed <<Limit:GETPROJECTBUDGET:pipelineCode|jobCode>> % of the budget in allocations.<br/><br/>
Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=2'>click here</a> for the details. Request you to review the future budget requirements and seek additional budget approval in WCGT if required.<br/><br/>
Regards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 306,
                module = "Notification",
                sub_module = "Notification",
                subject = "Allocation conflicts for <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>>",
                type = "EMPLOYEE_LEAVE_NOTIFCATION",
                is_active = true,
                notification_type = "EMAIL",
                to = "ResourceRequestor,Reviewer,AdditionalEl,AdditionalDelegate",
                template = @"Dear User,<br/><br/>
Employee: <<employeeemail>> is on leave for the below mentioned dates which conflicts with allocations on the Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>>.<br/><br/>
Leave Dates : <<leavestartdate:EmployeeLeaves:empEmail>> - <<leaveenddate:EmployeeLeaves:empEmail>><br/><br/>
Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=3'>click here</a> to review allocation detail and kindly update the allocations.<br/><br/>
Regards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 305,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project:<<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> - <<pipelineStatus:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>",
                type = "PROJECT_SUSPENSION_ALLOCATION_RELEASE_NOTIFICATION",
                is_active = true,
                notification_type = "PUSH",
                to = "employee_name_suspend",
                template = @"Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. has been <<pipelineStatus:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> on <<suspendedat:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. Your allocation has been auto-released from the project.",
                link_id = null,
                subscription_role = null,
                cc = null
            },
             new NotificationTemplate
             {
                 Id = 505,
                 module = "Notification",
                 sub_module = "Notification",
                 subject = "Project:<<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> - inactive",
                 type = "JOB_INACTIVE_ALLOCATION_RELEASE_NOTIFICATION",
                 is_active = true,
                 notification_type = "PUSH",
                 to = "employee_name_suspend",
                 template = @"Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. has been made inactive on <<suspendedat:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. Your allocation has been auto-released from the project.",
                 link_id = null,
                 subscription_role = null,
                 cc = null
             },
             new NotificationTemplate
             {
                 Id = 506,
                 module = "Notification",
                 sub_module = "Notification",
                 subject = "Allocation Supercoach delegate assignment",
                 type = "NOTIFICATION_FOR_ALLOCATION_SUPERCOACH_DELEGATE_CHANGE",
                 is_active = true,
                 notification_type = "EMAIL",
                 to = "allocation_supercoach_email",
                 template = @"You have been assigned as a Delegate to <<supercoach_email>> in OptiWise to support Allocation Workflow Management.<br/>If you have any questions about your responsibilities, please feel free to reach out to <<supercoach_email>> for guidance.",
                 link_id = null,
                 subscription_role = null,
                 cc = null
             },
             new NotificationTemplate
             {
                 Id = 507,
                 module = "Notification",
                 sub_module = "Notification",
                 subject = "Skill Supercoach delegate assignment",
                 type = "NOTIFICATION_FOR_SKILL_SUPERCOACH_DELEGATE_CHANGE",
                 is_active = true,
                 notification_type = "EMAIL",
                 to = "skill_supercoach_email",
                 template = @"You have been assigned as a Delegate to <<supercoach_email>> in OptiWise to support Skill Workflow Management.<br/>If you have any questions about your responsibilities, please feel free to reach out to <<supercoach_email>> for guidance.",
                 link_id = null,
                 subscription_role = null,
                 cc = null
             },
            new NotificationTemplate
            {
                Id = 304,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project:<<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> - <<pipelineStatus:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>",
                type = "PROJECT_SUSPENSION_NOTIFICATION",
                is_active = true,
                notification_type = "PUSH",
                to = "ResourceRequestor,Reviewer,AdditionalEl,AdditionalDelegate",
                template = @"Pipeline: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. has been <<pipelineStatus:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> on <<suspendedmodifyat:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. Any allocated resources have been auto-released.",
                link_id = 13,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 303,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project:<<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> - <<pipelineStatus:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>",
                type = "PROJECT_SUSPENSION_NOTIFICATION",
                is_active = true,
                notification_type = "EMAIL",
                to = "ResourceRequestor",
                template = @"Dear User, <br/><br/> 
<<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. has been <<pipelineStatus:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> on <<suspendedmodifyat:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. Any allocated resources have been auto-released. <br/><br/> 
Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=0'>click here</a> for the details. <br/><br/>
Regards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = "Reviewer,AdditionalEl,AdditionalDelegate"
            },
            new NotificationTemplate
            {
                Id = 302,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project:<<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> - <<pipelineStatus:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>",
                type = "PROJECT_SUSPENSION_ALLOCATION_RELEASE_NOTIFICATION",
                is_active = true,
                notification_type = "EMAIL",
                to = "employee_name_suspend",
                template = @"Dear User,<br/><br/> 
Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. has been <<pipelineStatus:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> on <<suspendedat:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. Your allocation has been auto-released from the project. <br/><br/> 
Regards,<br/>RMS Team<br/><br/>** This is an autogenerated email. Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 502,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project:<<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> - In Active",
                type = "JOB_INACTIVE_ALLOCATION_RELEASE_NOTIFICATION",
                is_active = true,
                notification_type = "EMAIL",
                to = "employee_name_suspend",
                template = @"Dear User,<br/><br/> 
Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. has been made inactive on <<suspendedat:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. Your allocation has been auto-released from the project. <br/><br/> 
Regards,<br/>RMS Team<br/><br/>** This is an autogenerated email. Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 503,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project:<<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> - In Active",
                type = "NOTIFICATION_FOR_TIMESHEET_CROSSING_BUDGETED_THRESHOLD",
                is_active = true,
                notification_type = "PUSH",
                to = "sender_for_notification",
                template = @"Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> has consumed <<consumedtimesheetbudgetpct>>% of the budgeted hours in actuals.",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 504,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project:<<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> - In Active",
                type = "NOTIFICATION_FOR_TIMESHEET_CROSSING_BUDGETED_THRESHOLD",
                is_active = true,
                notification_type = "EMAIL",
                to = "sender_for_notification",
                template = @"Dear User,<br/><br/> 
Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> has consumed <<consumedtimesheetbudgetpct>>% of the budgeted hours in clocking.<br/><br/><a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=2'>Click here</a> for the details. Request you to review the future budget requirements and seek additional budget approval in WCGT if required. <br/><br/> 
Regards,<br/>RMS Team<br/><br/>** This is an autogenerated email. Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 301,
                module = "Notification",
                sub_module = "Notification",
                subject = "RMS Admin Role assigned",
                type = "ADMIN_ASSIGNED_BY_SYSTEM_ADMIN",
                is_active = true,
                notification_type = "EMAIL",
                to = "employee_name_assign_as_admin",
                template = @"Dear User,<br/><br/>
You have been assigned the role of Admin in the RMS application.<br/><br/>
Please <a href='<<BaseUrl:config>>roles-permission'>click here</a> to view details in the User Management section.<br/><br/> 
Regards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 300,
                module = "Notification",
                sub_module = "Notification",
                subject = "RMS Admin Role assigned",
                type = "ADMIN_ASSIGNED_BY_SYSTEM_ADMIN",
                is_active = true,
                notification_type = "PUSH",
                to = "employee_name_assign_as_admin",
                template = @"You have been assigned the Admin role.Please check your email or visit the User Management Section.",
                link_id = 11,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 299,
                module = "Notification",
                sub_module = "Notification",
                subject = "Additional Delegate assigned to Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>",
                type = "ASSIGNMENT_OF_ADDITIONAL_DELEGATE_BY_ADDITIONAL_EL",
                is_active = true,
                notification_type = "EMAIL",
                to = "employee_name_additional_delegate",
                template = @"Dear User,<br/><br/>
<<User requesting>> has assigned you as Additional Delegate to the Additional EL for Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> on date <<userassignmentdate>> <br/><br/>
Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=0'>click here</a> for the details. You may contact <<User Requesting>> to discuss your responsibilities on the project in RMS.<br/><br/> 
Regards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 298,
                module = "Notification",
                sub_module = "Notification",
                subject = "Additional Delegate assigned to Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>",
                type = "ASSIGNMENT_OF_ADDITIONAL_DELEGATE_BY_ADDITIONAL_EL",
                is_active = true,
                notification_type = "PUSH",
                to = "employee_name_additional_delegate",
                template = @"You have been assigned as Additional Delegate for <<User Requesting>> for Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>.",
                link_id = 13,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 297,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<projectname>> Allocation Update",
                type = "JOB_CODE_UPDATE_TO_NEW_CODE",
                is_active = true,
                notification_type = "EMAIL",
                to = "previousrolesemails",
                template = @"Dear User,<br/><br/>
Allocations on the Project: <<projectname>> have been moved from Project Code <<oldprojectcode>> to new Project Code <<newprojectcode>> due to an update in WCGT of the Job Code.<br/><br/>
Please <a href='<<BaseUrl:config>>project-details/<<newpipelinecode##>>/<<newjobcode##>>?tab=0'>click here<a/> for the details.<br/><br/>
Regards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 296,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<projectname>> Allocation Update",
                type = "JOB_CODE_UPDATE_TO_NEW_CODE",
                is_active = true,
                notification_type = "PUSH",
                to = "previousrolesemails",
                template = @"Project: <<projectname>> allocations have been moved to new project code",
                link_id = 19,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 295,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update ",
                type = "NOTIFICATION_TO_EMPLOYEE_REVIEWER_APPROVED_EMPLOYEE_REJECTION",
                is_active = true,
                notification_type = "PUSH",
                to = "employee_name_allocation_wf",
                template = @"Your allocation to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been cancelled.Allocation Rejection request has been approved by Reviewer <<updated_by>> .",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 293,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update ",
                type = "NOTIFICATION_TO_EMPLOYEE_REVIEWER_APPROVED_EMPLOYEE_REJECTION",
                is_active = true,
                notification_type = "EMAIL",
                to = "employee_name_allocation_wf",
                template = @"Dear User,<br/><br/>
Your assignment to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been cancelled.
Your request for non acceptance of the allocation  has been approved by Reviewer <<updated_by>>.
<br/><br/>
Regards,<br/>RMS Team<br/><br/>** This is an autogenerated email. Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 409,
                module = "Notification",
                sub_module = "Notification",
                subject = "PUSH_NOTIFICATION_FOR_ALLOCATION_OF_RESOURCE_TO_PROJECT_REVIEWER_CONFIG_OFF",
                type = "PUSH_NOTIFICATION_FOR_ALLOCATION_OF_RESOURCE_TO_PROJECT_REVIEWER_CONFIG_OFF",
                is_active = true,
                notification_type = "PUSH",
                to = "resource_requestor_allocation_wf,Reviewer",
                template = @"Resources have been assigned to the project <<ProjectName:ResourceAllocationDetails:item_id>> on <<created_at>>. ",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 410,
                module = "Notification",
                sub_module = "Notification",
                subject = "PUSH_NOTIFICATION_TO_REQUESTOR_AFTER_REVIEWER_ACCEPTS",
                type = "PUSH_NOTIFICATION_TO_REQUESTOR_AFTER_REVIEWER_ACCEPTS",
                is_active = true,
                notification_type = "PUSH",
                to = "resource_requestor_allocation_wf",
                template = @"Resource Allocation Request for Project: <<ProjectName:ResourceAllocationDetails:item_id>>  have been approved by <<updated_by>>. ",
                link_id = 16,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 411,
                module = "Notification",
                sub_module = "Notification",
                subject = "PUSH_NOTIFICATION_TO_REQUESTOR_ONCE_APPROVED_BY_EMPLOYEE",
                type = "PUSH_NOTIFICATION_TO_REQUESTOR_ONCE_APPROVED_BY_EMPLOYEE",
                is_active = true,
                notification_type = "PUSH",
                to = "resource_requestor_allocation_wf,Reviewer",
                template = @"Resource Allocation Request for Project: <<ProjectName:ResourceAllocationDetails:item_id>> have been confirmed by employee <<empEmail:ResourceAllocationDetails:item_id>>. ",
                link_id = 16,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 412,
                module = "Notification",
                sub_module = "Notification",
                subject = "PUSH_NOTIFICATION_TO_REQUESTOR_ONCE_WITHDRAWAL_BY_EMPLOYEE",
                type = "PUSH_NOTIFICATION_TO_REQUESTOR_ONCE_WITHDRAWAL_BY_EMPLOYEE",
                is_active = true,
                notification_type = "PUSH",
                to = "resource_requestor_allocation_wf,Reviewer",
                template = @"Resource Allocation Request for Project: <<ProjectName:ResourceAllocationDetails:item_id>> have been confirmed by employee <<empEmail:ResourceAllocationDetails:item_id>>. ",
                link_id = 16,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 413,
                module = "Notification",
                sub_module = "Notification",
                subject = "PUSH_NOTIFICATION_TO_REQUESTOR_REVIEWER_ACCEPTS_EMPLOYEE_UPDATE",
                type = "PUSH_NOTIFICATION_TO_REQUESTOR_REVIEWER_ACCEPTS_EMPLOYEE_UPDATE",
                is_active = true,
                notification_type = "PUSH",
                to = "resource_requestor_allocation_wf",
                template = @"Allocation of <<empEmail:ResourceAllocationDetails:item_id>>, <<designation:ResourceAllocationDetails:item_id>> , <<grade:ResourceAllocationDetails:item_id>> on the Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been updated. ",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 414,
                module = "Notification",
                sub_module = "Notification",
                subject = "PUSH_NOTIFICATION_TO_REQUESTOR_AND_REVIEWER_AFTER_EMPLOYEE_UPDATE",
                type = "PUSH_NOTIFICATION_TO_REQUESTOR_AND_REVIEWER_AFTER_EMPLOYEE_UPDATE",
                is_active = true,
                notification_type = "PUSH",
                to = "resource_requestor_allocation_wf,Reviewer",
                template = @"Allocation of <<empEmail:ResourceAllocationDetails:item_id>>, <<designation:ResourceAllocationDetails:item_id>> , <<grade:ResourceAllocationDetails:item_id>> on the Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been updated. ",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 277,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update",
                type = "REVIEWER_ACCEPTED_EMPLOYEE_REJECTION_RESPONSE",
                is_active = true,
                notification_type = "EMAIL",
                to = "resource_requestor_allocation_wf",
                template = @"Dear User,<br/><br/>
The Allocation request rejected by employee <<empEmail:ResourceAllocationDetails:item_id>> for Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been approved by Super Coach <<updated_by>>.
Request you to please allocate another resource.<br/><br/>
Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=4'>click here</a> for the details.<br/><br/>
Regards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 276,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update",
                type = "REVIEWER_ACCEPTED_EMPLOYEE_REJECTION_RESPONSE",
                is_active = true,
                notification_type = "PUSH",
                to = "resource_requestor_allocation_wf",
                template = @" Allocation rejection by <<empEmail:ResourceAllocationDetails:item_id>> for Project: <<ProjectName:ResourceAllocationDetails:item_id>> have been approved by super coach <<updated_by>>. Please do new allocations",
                link_id = 16,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 274,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> Roll Forward Update - Allocation Release",
                type = "ROLL_OVER_ALLOCATION_TERMINATED_DUE_TO_UNAVAILABLITY",
                is_active = true,
                notification_type = "PUSH",
                to = "employee_name_roll_over_terminated",
                template = @"Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> has been rolled forward to <<pipelinestartdate>>. ",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 273,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> Roll Forward Update - Allocation Release",
                type = "ROLL_OVER_ALLOCATION_TERMINATED_DUE_TO_UNAVAILABLITY",
                is_active = true,
                notification_type = "EMAIL",
                to = "employee_name_roll_over_terminated",
                template = @"Dear User,<br/><br/>
Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> dates have been rolled forward from <<pipelineoldstartdate>> to <<pipelinestartdate>>.  Since you are not available on the revised project dates, your allocation on the project has been released.<br/><br/>
Please speak to <<ProjectResourceRequestor:GetProjectResourceRequestor:pipelineCode|jobCode>> for concerns on the allocations.<br/><br/>
Regards,<br/>RMS Team<br/><br/>** This is an autogenerated email. Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 272,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> Roll Forward Update - Allocation Release",
                type = "ROLL_OVER_ALLOCATION_IN_DRAFT_DUE_TO_UNAVAILABLITY",
                is_active = true,
                notification_type = "PUSH",
                to = "employee_name_roll_over_draft",
                template = @"Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> has been rolled forward to <<pipelinestartdate>>. Your allocation has been released. ",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 271,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> Roll Forward Update - Allocation Release",
                type = "ROLL_OVER_ALLOCATION_IN_DRAFT_DUE_TO_UNAVAILABLITY",
                is_active = true,
                notification_type = "EMAIL",
                to = "employee_name_roll_over_draft",
                template = @"Dear User,<br/><br/>
Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> dates have been rolled forward from <<pipelineoldstartdate>> to <<pipelinestartdate>>.  Since you are not available on the revised project dates, your allocation on the project has been released.<br/><br/>
Please speak to <<ProjectResourceRequestor:GetProjectResourceRequestor:pipelineCode|jobCode>> for concerns on the allocations.<br/><br/>
Regards,<br/>RMS Team<br/><br/>** This is an autogenerated email. Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 270,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> Name Marketplace Summary",
                type = "NOTIFICATION_TO_RESOURCE_REQUESTOR_AND_DELEGATE_FOR_REMOVAL_OF_PROJECT_FROM_MP",
                is_active = true,
                notification_type = "EMAIL",
                to = "ResourceRequestor,Delegate",
                template = @"Dear User,<br/><br/>
Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> has been removed from Marketplace & has received <<employeeshowedinterestcount>> interests.<br/><br/>
Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=5'>click here</a> for the details.<br/><br/>
Regards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 269,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> Name Marketplace Summary",
                type = "NOTIFICATION_TO_RESOURCE_REQUESTOR_AND_DELEGATE_FOR_REMOVAL_OF_PROJECT_FROM_MP",
                is_active = true,
                notification_type = "PUSH",
                to = "ResourceRequestor,Delegate",
                template = @"Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> has received <<employeeshowedinterestcount>> interests. ",
                link_id = 18,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 268,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> Roll Forward Update.",
                type = "NOTIFICATION_TO_REVIEWER_ALLOCATIONS_ARE_SHIFTED_AND_NEW_WORKFLOW_ARE_TRIGGERED",
                is_active = true,
                notification_type = "PUSH",
                to = "Reviewer",
                template = @"Allocation Update - Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> rolled forward to <<pipelinestartdate>>",
                link_id = 16,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 267,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> Roll Forward Update.",
                type = "NOTIFICATION_TO_REVIEWER_ALLOCATIONS_ARE_SHIFTED_AND_NEW_WORKFLOW_ARE_TRIGGERED",
                is_active = true,
                notification_type = "EMAIL",
                to = "Reviewer",
                template = @"Dear User,<br/><br/>
Allocation of Employees has been updated on the  project : <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> as the Project dates have been rolled forward from <<pipelineoldstartdate>> to <<pipelinestartdate>>.<br/><br/> 
Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=3'>click here</a> for the details.<br/><br/> 
Regards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 264,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> Allocation Update",
                type = "NOTIFICATION_TO_EMPLOYEE_AS_RELEASED_FROM_PROJECT",
                is_active = true,
                notification_type = "EMAIL",
                to = "employee_name_release_resource",
                template = @"Dear User,<br/><br/>
Your Allocation on the Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> has been released.<br/> 
Please reach out to <<modifiedBy>> for any queries.<br/><br/>
Regards,<br/>RMS Team<br/><br/>** This is an autogenerated email. Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = "ResourceRequestor,Reviewer,AdditionalEl,Delegate,AdditionalDelegate"
            },
            new NotificationTemplate
            {
                Id = 263,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> Allocation Update",
                type = "NOTIFICATION_TO_EMPLOYEE_AS_RELEASED_FROM_PROJECT",
                is_active = true,
                notification_type = "PUSH",
                to = "employee_name_release_resource,ResourceRequestor,Reviewer,AdditionalEl,Delegate,AdditionalDelegate",
                template = @"Allocation updates for Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>>",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 156,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> Roll Forward Update",
                type = "ROLL_OVER_ALLOCATED_EMPLOYEES_AVAILABLE_FOR_REVISED_DATES_ALLOCATION_SHIFTED_NEW_WF_TRIGGERED_NOTIFICATION_TO_REQUESTOR_AND_REVIEWER",
                is_active = true,
                notification_type = "PUSH",
                to = "ResourceRequestor,Delegate,Reviewer,AdditionalEl,AdditionalDelegate",
                template = @"Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> has been rolled forward to <<pipelinestartdate>>. Review Project details for change in allocations.",
                link_id = 16,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 155,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> Roll Forward Update",
                type = "ROLL_OVER_ALLOCATED_EMPLOYEES_AVAILABLE_FOR_REVISED_DATES_ALLOCATION_SHIFTED_NEW_WF_TRIGGERED_NOTIFICATION_TO_REQUESTOR_AND_REVIEWER",
                is_active = true,
                notification_type = "EMAIL",
                to = "ResourceRequestor,Delegate,Reviewer,AdditionalEl,AdditionalDelegate",
                template = @"Dear User,<br/><br/>
Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> dates have been rolled forward from <<pipelineoldstartdate>> to <<pipelinestartdate>>. The system has taken the following actions based on the new start date which are set out below:<br/><br/>
1. For allocated employees who are available on the revised dates, new allocation workflow and relevant approvals will be triggered.<br/>
2. For allocated employees who are not available on certain dates in the new project period, those allocations will be moved to DRAFT state to review and change as appropriate.<br/>
3. For allocated employees who are not available for the requested period, they will be released from the project.<br/><br/>
Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=3'>click here</a> for the details.<br/><br/>
Regards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 154,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update",
                type = "NOTIFICATION_TO_EMPLOYEE_REQUESTOR_APPROVED_REJECTION",
                is_active =
            true,
                notification_type = "PUSH",
                to = "employee_name_allocation_wf",
                template = @"Your allocation to the project <<ProjectName:ResourceAllocationDetails:item_id>> has been cancelled. Allocation Rejection request has been approved by Resoruce Requestor <<updated_by>>.",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 153,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update",
                type = "NOTIFICATION_TO_EMPLOYEE_REQUESTOR_APPROVED_REJECTION",
                is_active = true,
                notification_type = "EMAIL",
                to = "employee_name_allocation_wf",
                template = @"Dear User,<br/><br/>
Your allocation to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been cancelled, as you have not agreed to accept the allocation.<br/><br/> 
Your  request for not being allocated was approved by  <<updated_by>>.<br/><br/>
Regards,<br/>RMS Team<br/><br/>** This is an autogenerated email. Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 406,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update",
                type = "NOTIFICATION_TO_EMPLOYEE_REQUESTOR_AUTO_APPROVED_REJECTION",
                is_active =
            true,
                notification_type = "PUSH",
                to = "employee_name_allocation_wf",
                template = @"Your allocation to the project <<ProjectName:ResourceAllocationDetails:item_id>> has been cancelled. Allocation Rejection request has been auto approved by the system.",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 407,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update",
                type = "NOTIFICATION_TO_EMPLOYEE_REQUESTOR_AUTO_APPROVED_REJECTION",
                is_active = true,
                notification_type = "EMAIL",
                to = "employee_name_allocation_wf",
                template = @"Dear User,<br/><br/>
Resource allocation for employee <<empEmail:ResourceAllocationDetails:item_id>> for Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been cancelled, as the resource did not accept the allocation.<br/><br/> 
Request you to allocate another resource for the Requisition.<br/><br/>
Regards,<br/>RMS Team<br/><br/>** This is an autogenerated email. Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 152,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update",
                type = "NOTIFICATION_TO_EMPLOYEE_WITHDRAWS_REJECTION",
                is_active = true,
                notification_type = "PUSH",
                to = "employee_name_allocation_wf",
                template = @"You have successfully been allocated to the project <<ProjectName:ResourceAllocationDetails:item_id>> on <<startdate:ResourceAllocationDetails:item_id>>",
                link_id = 16,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 151,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update",
                type = "NOTIFICATION_TO_EMPLOYEE_WITHDRAWS_REJECTION",
                is_active = true,
                notification_type = "EMAIL",
                to = "employee_name_allocation_wf",
                template =
            @"Dear User,<br/><br/>As you have accepted the allocation, you have now been allocated to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> on <<startdate:ResourceAllocationDetails:item_id>>. 
<br/><br/>
Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=3'>click here</a> to view further details.<br/><br/>
<br/><br/>
Regards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 150,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update",
                type = "NOTIFICATION_TO_EMPLOYEE_AUTO_APPROVED_AFTER_EMPLOYEE_DUE_DATE_CROSS",
                is_active = true,
                notification_type = "PUSH",
                to = "employee_name_allocation_wf",
                template = @"Your allocation has been auto-approved for the Project <<ProjectName:ResourceAllocationDetails:item_id>> on <<startdate:ResourceAllocationDetails:item_id>>",
                link_id = 16,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 149,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update",
                type = "NOTIFICATION_TO_EMPLOYEE_AUTO_APPROVED_AFTER_EMPLOYEE_DUE_DATE_CROSS",
                is_active = true,
                notification_type = "EMAIL",
                to = "employee_name_allocation_wf",
                template = @"Dear User,<br/><br/>
You have been auto-allocated to the Project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/>
Start Date: <<startdate:ResourceAllocationDetails:item_id>><br/> End Date: <<enddate:ResourceAllocationDetails:item_id>><br/> Hours: <<totaleffort:ResourceAllocationDetails:item_id>>.<br/><br/>
Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=3'>click here</a> to view allocation details.<br/><br/>
Regards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 148,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update",
                type = "NOTIFICATION_TO_EMPLOYEE_AFTER_REVIEWER_ACCEPTS",
                is_active = true,
                notification_type = "PUSH",
                to = "employee_name_allocation_wf",
                template = @"You have been allocated to the project <<ProjectName:ResourceAllocationDetails:item_id>> on <<startdate:ResourceAllocationDetails:item_id>> as your rejection has not been accepted.",
                link_id = 16,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 147,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update",
                type = "NOTIFICATION_TO_EMPLOYEE_AFTER_REVIEWER_ACCEPTS",
                is_active = true,
                notification_type = "EMAIL",
                to = "employee_name_allocation_wf",
                template = @"Dear User,<br/><br/>
Your request for non-acceptance of allocation has been rejected by the Reviewer <<updated_by>>. You have now been allocated to the Project: <<ProjectName:ResourceAllocationDetails:item_id>><br/><br/>The Project Allocation Period is:<br/>
Start Date: <<startdate:ResourceAllocationDetails:item_id>><br/> End Date: <<enddate:ResourceAllocationDetails:item_id>><br/> Hours: <<totaleffort:ResourceAllocationDetails:item_id>><br/><br/>
For any queries please reach out to the above mentioned Reviewer.<br/><br/>
Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=3'>click here</a> review project and allocation the details..<br/><br/>
Regards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 404,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update",
                type = "NOTIFICATION_TO_EMPLOYEE_AFTER_EMPLOYEE_ACCEPTS",
                is_active = true,
                notification_type = "PUSH",
                to = "employee_name_allocation_wf",
                template = @"You have been successfully  allocated  to the project <<ProjectName:ResourceAllocationDetails:item_id>> on <<startdate:ResourceAllocationDetails:item_id>>.",
                link_id = 16,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 405,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update",
                type = "NOTIFICATION_TO_EMPLOYEE_AFTER_EMPLOYEE_ACCEPTS",
                is_active = true,
                notification_type = "EMAIL",
                to = "employee_name_allocation_wf",
                template = @"Dear User,<br/><br/>
You have been allocated to the Project: <<ProjectName:ResourceAllocationDetails:item_id>>  on <<startdate:ResourceAllocationDetails:item_id>>.<br/><br/>
Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=3'>click here</a> for the details.<br/><br/>
Regards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 146,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update",
                type = "NOTIFICATION_TO_RESOURCE_REQUESTOR_AND_REVIEWER_ON_EMPLOYEE_REJECTION_REQUESTOR_CONFIG_IS_ON",
                is_active = true,
                notification_type = "PUSH",
                to = "resource_requestor_allocation_wf,Reviewer,supercoach_email",
                template = @"Resource allocation requests have been rejected for Project: <<ProjectName:ResourceAllocationDetails:item_id>> by employee <<empEmail:ResourceAllocationDetails:item_id>>. Please review employee action",
                link_id = 16,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 145,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update",
                type = "NOTIFICATION_TO_RESOURCE_REQUESTOR_AND_REVIEWER_ON_EMPLOYEE_REJECTION_REQUESTOR_CONFIG_IS_ON",
                is_active = true,
                notification_type = "EMAIL",
                to = "resource_requestor_allocation_wf,Reviewer,supercoach_email",
                template = @"Dear User,<br/><br/>
Resource allocation request has been rejected by employee <<empEmail:ResourceAllocationDetails:item_id>> for Project: <<ProjectName:ResourceAllocationDetails:item_id>><br/>
Rejection reason: <<ReasonForRejectionProvidedByEmployee>><br/><br/>
Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=4'>click here</a> to view details and review employee action.<br/><br/>
Regards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 144,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update",
                type = "NOTIFICATION_TO_RESOURCE_REQUESTOR_AND_REVIEWER_ON_EMPLOYEE_REJECTION",
                is_active = true,
                notification_type = "PUSH",
                to = "resource_requestor_allocation_wf,Reviewer",
                template = @"Resource allocation requests have been rejected for Project: <<ProjectName:ResourceAllocationDetails:item_id>> by employee <<empEmail:ResourceAllocationDetails:item_id>>.",
                link_id = 16,
                subscription_role = null,
                cc = ""
            },
            new NotificationTemplate
            {
                Id = 143,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update",
                type = "NOTIFICATION_TO_RESOURCE_REQUESTOR_AND_REVIEWER_ON_EMPLOYEE_REJECTION",
                is_active = true,
                notification_type = "EMAIL",
                to = "resource_requestor_allocation_wf,Reviewer",
                template = @"Dear User,<br/><br/>
Resource allocation request has been rejected by Employee: <<empEmail:ResourceAllocationDetails:item_id>> for Project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/>
You can terminate the workflow by <<due_date>> to make new allocations provided the allocated employee does not withdraw their rejection.<br/>
Rejection reason: <<ReasonForRejectionProvidedByEmployee>><br/><br/>
Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=4'>click here</a> for the details.<br/><br/>
Regards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = "",
            },
            new NotificationTemplate
            {
                Id = 142,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update",
                type = "EMPLOYEE_ALLOCATION_REJECTED_BY_REVIEWER_NOTIFICATION_TO_RESOURCE_REQUESTOR",
                is_active = true,
                notification_type = "PUSH",
                to = "resource_requestor_allocation_wf,Reviewer,supercoach_email",
                template = @"Resource allocation requests have been rejected for Project: <<ProjectName:ResourceAllocationDetails:item_id>> by reviewer <<updated_by>>. Please do new allocations",
                link_id = 17,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 141,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update",
                type = "EMPLOYEE_ALLOCATION_REJECTED_BY_REVIEWER_NOTIFICATION_TO_RESOURCE_REQUESTOR",
                is_active = true,
                notification_type = "EMAIL",
                to = "resource_requestor_allocation_wf,Reviewer,supercoach_email",
                template = @"Dear User,<br/><br/>
Resource allocation request has been rejected by reviewer: <<updated_by:GetUserInfo:updated_by>> for employee: <<empEmail:ResourceAllocationDetails:item_id>> 
in the project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/>
Rejection reason: <<ReasonForRejectionProvidedByReviewer>><br/><br/>
Request you to please allocate another resource.<br/><br/>
Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=4'>click here</a> for the details.<br/><br/>
Regards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 140,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update",
                type = "NOTIFICATION_FOR_ALLOCATION_UPDATE_TO_EMPLOYEE",
                is_active = true,
                notification_type = "PUSH",
                to = "employee_name_allocation_wf",
                template = @"Your assignment on the project <<ProjectName:ResourceAllocationDetails:item_id>> has been updated on <<modifiedat>>. ",
                link_id = 16,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 139,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update",
                type = "NOTIFICATION_FOR_ALLOCATION_UPDATE_TO_EMPLOYEE",
                is_active = true,
                notification_type = "EMAIL",
                to = "employee_name_allocation_wf",
                template = @"Dear User,<br/><br/>
Your assignment on the Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been updated on <<modifiedat>>.<br/><br/>
You revised allocation dates are:<br/>
Start Date: <<startdate:ResourceAllocationDetails:item_id>><br/> End Date: <<enddate:ResourceAllocationDetails:item_id>><br/> Hours: <<totaleffort:ResourceAllocationDetails:item_id>>.<br/><br/>
Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=3'>click here</a> or the details.<br/><br/>
Regards,<br/>
RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 43,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update",
                type = "NOTIFICATION_TO_EMPLOYEE_FOR_HIS_ALLOCATION_TASK_TO_PROJECT",
                is_active = true,
                notification_type = "EMAIL",
                to = "employee_name_allocation_wf",
                template = @"Dear User,<br/><br/>
You have been assigned to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> on <<created_at>>.<br/>
The Project Allocation Period is:<br/>
Start Date: <<startdate:ResourceAllocationDetails:item_id>><br/> End Date: <<enddate:ResourceAllocationDetails:item_id>><br/> Hours: <<totaleffort:ResourceAllocationDetails:item_id>>.<br/><br/>
Please <a href='<<BaseUrl:config>>myapproval'>click here</a> to view further details of the allocation.<br/><br/>
Please note, if you are unable to review the request for approval, it will be auto - approved by <<due_date>>.<br/><br/>
Regards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 42,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update",
                type = "NOTIFICATION_TO_EMPLOYEE_FOR_HIS_ALLOCATION_TASK_TO_PROJECT",
                is_active = true,
                notification_type = "PUSH",
                to = "employee_name_allocation_wf",
                template = @"You have been assigned to the Project <<ProjectName:ResourceAllocationDetails:item_id>> on <<created_at>>.",
                link_id = 12,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 316,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project Updates",
                type = "ALLOCATION_SUMMARY_NOTIFICATION",
                is_active = true,
                notification_type = "EMAIL",
                to = "ResourceRequestor,Reviewer,AdditionalEl,AdditionalDelegate",
                template = @"Dear User,
<br/><br/>
The following activities have been performed on the below mentioned Job / Pipeline (s): 
<br/>
<<RequistionSummary:Allocation:PipelineCode|JobCode>>
<br/>
<<RequstionSummary:Requistion:PipelineCode|JobCode>>
<br/>
<<AllocationSummary:AllocationPublished:PipelineCode|JobCode>>
<br/>
<<MarketPlaceSummary:MarketPlace:PipelineCode|JobCode>>
<br/> 
Please <a href='<<BaseUrl:config>>projects'>click here </a> to view the details of project(s). 
<br/>
<br/>
Regards,<br/>
RMS Team<br/><br/>** This is an autogenerated email. Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 172,
                module = "Notification",
                sub_module = "Notification",
                subject = "RMS Tasks pending for your action",
                type = "ADDITION_OF_NEW_PROJECT_NOTIFICATION_TO_RESOURCE_REQUESTOR",
                is_active = true,
                notification_type = "EMAIL",
                to = "employee",
                template = @"Dear User,<br/><br/>
Following tasks are pending for your action:
<br/><br/>
<<allocationtablecontent>>
<br/><br/>
<<skilltablecontent>>
<br/><br/>
Please <a href='<<BaseUrl:config>>myapproval'>click here</a> for to review further details and approve/reject the request.
<br/><br/>
Regards,<br/>RMS Team<br/><br/>** This is an autogenerated email. Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 171,
                module = "Notification",
                sub_module = "Notification",
                subject = "RMS Tasks pending for your action",
                type = "RMS_ALLOCATION_AND_SKILL_TASKS_PENDING_FOR_ACTION_SUMMARY_MAIL",
                is_active = true,
                notification_type = "EMAIL",
                to = "employee",
                template = @"Dear User,<br/><br/>
Following tasks are pending for your action:<br/><br/>
<<allocationtablecontent>><br/><br/>
<<skilltablecontent>><br/><br/>
Please <a href='<<BaseUrl:config>>myapproval'>click here</a> for to review further details and approve/reject the request.<br/><br/>
Regards,<br/>RMS Team<br/><br/>** This is an autogenerated email. Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 170,
                module = "Notification",
                sub_module = "Notification",
                subject = "New Projects in the Marketplace",
                type = "CONSOLIDATED_MAIL_TO_EMPLOYEE_FOR_PROJECT_LISTING_IN_MARKETPLACE",
                is_active = true,
                notification_type = "EMAIL",
                to = "employee",
                template = @"Dear User,<br/><br/>
New projects have been added to the Marketplace in the RMS. These projects offer exciting opportunities for you to contribute your skills and expertise. A summary of the new projects provided in the table below:<br/><br/>
<<projectlistinginmarketplacenotificationtoemployee>>
<br/><br/>
Please <a href='<<BaseUrl:config>>marketplace'>click here</a> to view details in the Marketplace and submit your interest.<br/><br/>
Regards,<br/>RMS Team<br/><br/>** This is an autogenerated email. Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 169,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project Marketplace Updates",
                type = "PROJECT_MOVED_TO_MARKETPLACE_SUMMARY_EMAIL",
                is_active = true,
                notification_type = "EMAIL",
                to = "Reviewer,ResourceRequestor,Delegate",
                template = @"Dear User,<br/><br/>
Below listed projects have been moved in the Marketplace.<br/><br/>
<projectmovedtomarketplacetable><br/><br/>
Regards,<br/>RMS Team<br/><br/>** This is an autogenerated email. Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = ""
            },
            new NotificationTemplate
            {
                Id = 400,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> Allocations Update.",
                type = "PROJECT_END_DATE_UPDATE_NOTIFICATION",
                is_active = true,
                notification_type = "PUSH",
                to = "ResourceRequestor,Reviewer,AdditionalEl,AdditionalDelegate,Delegate",
                template = @"Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> end date has been updated to <<enddate>>. Please take necessary actions.",
                link_id = 13,
                subscription_role = null,
                cc = ""
            },


            new NotificationTemplate
            {
                Id = 317,
                module = "Notification",
                sub_module = "Notification",
                subject = " Additional EL assigned to Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>>",
                type = "PROJECT_ADDITIONAL_EL_UPDATE_NOTIFICATION",
                is_active = true,
                notification_type = "EMAIL",
                to = "newadditionalels",
                template = @"Dear User, <br/><br/>
<<userrequesting>> has assigned you Additional EL for project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> on date <<userassignmentdate>>
<br/> <br/> Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=0'>click here</a> for the details. You may contact <<userrequesting>> to discuss your responsibilities on the project in RMS. <br/><br/>
Regards,<br/>RMS Team<br/><br/>** This is an autogenerated email. Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 318,
                module = "Notification",
                sub_module = "Notification",
                subject = " Additional EL assigned to Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>>",
                type = "PROJECT_ADDITIONAL_EL_UPDATE_NOTIFICATION",
                is_active = true,
                notification_type = "PUSH",
                to = "newadditionalels",
                template = @"You have been assigned as Additional EL for Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> on date <<userassignmentdate>>",
                link_id = 13,
                subscription_role = null,
                cc = null
            },

            new NotificationTemplate
            {
                Id = 319,
                module = "Notification",
                sub_module = "Notification",
                subject = "Delegate assignment on Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> ",
                type = "PROJECT_DELEGATE_UPDATE_NOTIFICATION",
                is_active = true,
                notification_type = "EMAIL",
                to = "Delegate",
                template = @"Dear User,<br/><br/>
You have been assigned as Delegate to <<delegateassignedby>> on Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> on date <<delegateassignmentdate>>.
<br/> <br/> Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=0'>click here</a> for the details.You may contact <<delegateassignedby>> to discuss your responsibilities on the project in RMS. <br/><br/>
Regards,<br/>RMS Team<br/><br/>** This is an autogenerated email. Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },

            new NotificationTemplate
            {
                Id = 320,
                module = "Notification",
                sub_module = "Notification",
                subject = "Delegate assignment on Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> ",
                type = "PROJECT_DELEGATE_UPDATE_NOTIFICATION",
                is_active = true,
                notification_type = "PUSH",
                to = "Delegate",
                template = @"You have been assigned as Delegate for <<delegateassignedby>> in Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> on date <<delegateassignmentdate>>.",
                link_id = 13,
                subscription_role = null,
                cc = null
            },

            new NotificationTemplate
            {
                Id = 321,
                module = "Notification",
                sub_module = "Notification",
                subject = "Additional Delegate assigned to Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> ",
                type = "PROJECT_ADDITIONAL_DELEGATE_UPDATE_NOTIFICATION",
                is_active = true,
                notification_type = "EMAIL",
                to = "newadditionaldelegates",
                template = @"Dear User,<br/><br/>
<<userrequesting>> has assigned you as Additional Delegate to the Additional EL for Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> on date <<userassignmentdate>>
<br/> <br/> Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=0'>click here</a> for the details. You may contact <<userrequesting>> to discuss your responsibilities on the project in RMS. <br/> <br/>
Regards,<br/>RMS Team<br/><br/>** This is an autogenerated email. Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },

            new NotificationTemplate
            {
                Id = 322,
                module = "Notification",
                sub_module = "Notification",
                subject = "Additional Delegate assigned to Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>>",
                type = "PROJECT_ADDITIONAL_DELEGATE_UPDATE_NOTIFICATION",
                is_active = true,
                notification_type = "PUSH",
                to = "newadditionaldelegates",
                template = @"You have been assigned as Additional Delegate for <<userrequesting>> for Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>>.  ",
                link_id = 13,
                subscription_role = null,
                cc = null
            },

            new NotificationTemplate
            {
                Id = 401,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> end date update.",
                type = "PROJECT_END_DATE_UPDATE_NOTIFICATION",
                is_active = true,
                notification_type = "EMAIL",
                to = "ResourceRequestor,Reviewer,AdditionalEl,AdditionalDelegate,Delegate",
                template = @"Dear User,<br/><br/>
Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> end date has been updated to <<enddate>>.Please review allocations made to the project and take any necessary actions.
<br/><br/>
Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=0'>click here</a> for the details.
<br/><br/>
Regards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.* *",
                link_id = null,
                subscription_role = null,
                cc = ""
            },
            new NotificationTemplate
            {
                Id = 323,
                module = "Notification",
                sub_module = "Notification",
                subject = "Skill Assessment Review Updates",
                type = "SUPERCOACH_REJECTED_SKILL_ASSESSMENT_REQUEST",
                is_active = true,
                notification_type = "PUSH",
                to = "userskillemail",
                template = @"Your Skill Review request has been actioned.",
                link_id = 1,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 324,
                module = "Notification",
                sub_module = "Notification",
                subject = "Skill Assessment Review Updates",
                type = "SUPERCOACH_REJECTED_SKILL_ASSESSMENT_REQUEST",
                is_active = true,
                notification_type = "EMAIL",
                to = "userskillemail",
                template = @"Dear User, <br/><br/> 
Your skill assessment approval has been declined by your Supercoach <<updated_by>>. <br/><br/> 
Skill Name : <<skillname:UserSkill:item_id>><br/>
Skill Proficiency Level : <<Proficiency:UserSkill:item_id>><br/>
Reason : <<rejection_remark>> <br/><br/>
Please <a href='<<BaseUrl:config>>myskill'>click here</a> for the details and reach out to your Supercoach for any further clarifications.<br/><br/> 
Regards,<br/>RMS Team<br/><br/>** This is an autogenerated email. Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 403,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<projectname>> Allocation Update",
                type = "PROJECT_JOB_CODE_CHANGE_INFORMATION_TO_EMPLOYEE",
                is_active = true,
                notification_type = "PUSH",
                to = "employee_jobcode_change",
                template = @"Project: <<projectname>> allocations have been moved to new project code",
                link_id = 19,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 402,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<projectname>> Allocation Update",
                type = "PROJECT_JOB_CODE_CHANGE_INFORMATION_TO_EMPLOYEE",
                is_active = true,
                notification_type = "EMAIL",
                to = "employee_jobcode_change",
                template = @"Dear User,<br/><br/>
Your Allocation on the Project: <<projectname>> has been moved from Project Code <<oldprojectcode>> to new Project Code <<newprojectcode>>.<br/><br/>
Please <a href='<<BaseUrl:config>>project-details/<<newpipelinecode##>>/<<newjobcode##>>?tab=0'>click here<a/> for the details.<br/><br/>
Regards,<br/>RMS Team<br/><br/>** This is an autogenerated email. Kindly do not respond to this.**",
                link_id = null,
                subscription_role = null,
                cc = null
            },
            new NotificationTemplate
            {
                Id = 408,
                module = "Notification",
                sub_module = "Notification",
                subject = "Project: <<projectname>> Markeplace Interest Submitted",
                type = "NOTIFICATION_FOR_INTEREST_IN_MARKETPLACE_AGAINST_THEIR_PROJECT",
                is_active = true,
                notification_type = "PUSH",
                to = "ResourceRequestor,Delegate",
                template = @"You have received an interest for the Project: <<projectname>> in Marketplace. Total <<noofinterested>> likes received.",
                link_id = 18,
                subscription_role = null,
                cc = null
            }

            );
        }

        private static object PopulateNotificationLink(ModelBuilder modelBuilder)
        {
            return modelBuilder.Entity<NotificationTemplateLinks>()
            .HasData(new NotificationTemplateLinks
            {
                Id = 1,
                Module = "Notification",
                SubModule = "Skill",
                Link = "/myskill"
            },
            new NotificationTemplateLinks
            {
                Id = 2,
                Module = "Notification",
                SubModule = "Skill",
                Link = "/skill-review"
            },
            new NotificationTemplateLinks
            {
                Id = 3,
                Module = "Notification",
                SubModule = "Skill",
                Link = "/searchskill"
            },
            new NotificationTemplateLinks
            {
                Id = 4,
                Module = "Notification",
                SubModule = "Skill",
                Link = "/skillmaster"
            },
            new NotificationTemplateLinks
            {
                Id = 5,
                Module = "Notification",
                SubModule = "Skill",
                Link = "/projects"
            },
            new NotificationTemplateLinks
            {
                Id = 6,
                Module = "Notification",
                SubModule = "Project",
                Link = "/projects"
            },
            new NotificationTemplateLinks
            {
                Id = 7,
                Module = "Notification",
                SubModule = "Project",
                Link = "/marketplace"
            },
            new NotificationTemplateLinks
            {
                Id = 8,
                Module = "Notification",
                SubModule = "Manage",
                Link = "/my-preference"
            },
            new NotificationTemplateLinks
            {
                Id = 9,
                Module = "Notification",
                SubModule = "Manage",
                Link = "/my-preference"
            },
            new NotificationTemplateLinks
            {
                Id = 10,
                Module = "Notification",
                SubModule = "Manage",
                Link = "/my-calender"
            },
            new NotificationTemplateLinks
            {
                Id = 11,
                Module = "Notification",
                SubModule = "User",
                Link = "/roles-permission"
            },
            new NotificationTemplateLinks
            {
                Id = 12,
                Module = "Notification",
                SubModule = "User",
                Link = "/myapproval"
            },
            new NotificationTemplateLinks
            {
                Id = 13,//Project Details Tab
                Module = "Notification",
                SubModule = "Details",
                Link = "/project-details/<<pipelinecode##>>/<<jobcode##>>?tab=0"
            },
            new NotificationTemplateLinks
            {
                Id = 14,//Project Calender Tab
                Module = "Notification",
                SubModule = "Details",
                Link = "/project-details/<<pipelinecode##>>/<<jobcode##>>?tab=1"
            },
            new NotificationTemplateLinks
            {
                Id = 15,//Project Budget Tab
                Module = "Notification",
                SubModule = "Details",
                Link = "/project-details/<<pipelinecode##>>/<<jobcode##>>?tab=2"
            },
            new NotificationTemplateLinks
            {
                Id = 16,//Project Allocation Tab
                Module = "Notification",
                SubModule = "Details",
                Link = "/project-details/<<pipelinecode##>>/<<jobcode##>>?tab=3"
            },
            new NotificationTemplateLinks
            {
                Id = 17,//Project Requisition Tab
                Module = "Notification",
                SubModule = "Details",
                Link = "/project-details/<<pipelinecode##>>/<<jobcode##>>?tab=4"
            },
            new NotificationTemplateLinks
            {
                Id = 18,//Project MP Interest Tab
                Module = "Notification",
                SubModule = "Details",
                Link = "/project-details/<<pipelinecode##>>/<<jobcode##>>?tab=5"
            },
            new NotificationTemplateLinks
            {
                Id = 19,
                Module = "Notification",
                SubModule = "Details",
                Link = "/project-details/<<newpipelinecode##>>/<<newjobcode##>>?tab=0"
            }
            );
        }
        public DbSet<NotificationTemplate> NotificationTemplates { get; set; }
        public DbSet<NotificationPlaceHolder> NotificationPlaceHolder { get; set; }
        public DbSet<NotificationTypes> NotificationTypes { get; set; }
        public DbSet<NotificationEntity> NotificationEntity { get; set; }
        public DbSet<UserNotification> UserNotification { get; set; }
        public DbSet<NotificationTemplateLinks> NotificationTemplateLinks { get; set; }
        public DbSet<NotificationSubscription> NotificationSubscription { get; set; }
        public DbSet<NotificationLog> NotificationLog { get; set; }

    }
}
