export enum EWorkflowHistoryAction {
  ENGAGEMENT_WORKFLOW_CREATED = "engagement-created",
  ENGAGEMENT_PARTNER_APPROVED = "engagement-partner-approved",
  ENGAGEMENT_PARTNER_REJECT = "engagement-partner-reject",
  ENGAGEMENT_PARTNER_APPROVAL_CREATE = "engagement-partner-approval-create",
  ENGAGEMENT_BUSINESS_SPOC_REJECT = "engagement-business-spoc-reject",
  ENGAGEMENT_BUSINESS_SPOC_APPROVED = "engagement-business-spoc-approved",
  ENGAGEMENT_BUSINESS_SPOC_APPROVAL_CREATE = "engagement-business-spoc-approval-create",
  ENGAGEMENT_ACCEPTED = "engagement-accepted",
  ENGAGEMENT_DELIVERED = "engagement-delivered",
  ENGAGEMENT_CLOSE = "engagement-close",
  NO_ACTION_FOUND = "no-action-found",
  KPI_EXECUTION_EXECUTED = "kpi-executed",
  KPI_EXECUTION_CONFIRMED_BY_ET = "kpi-confimed-by-et",
  KPI_EXECUTION_DROPPED = "kpi-dropped",
  KPI_EXECUTION_REVISION = "revision-required",
  KPI_EXECUTION_INPUT_PROVIDED = "input-provided",
  KPI_EXECUTION_READY_REVIEW = "ready-review",
  KPI_EXECUTION_COMPLETED = "completed",
  KPI_EXECUTION_INPUT_PENDING = "input-pending-et",
  NEW_WORKFLOW = "new_workflow",
  KPI_EXECUTION_RUNNING = "kpi-execution-running",
  KPI_EXECUTION_FAILED = "kpi-execution-failed",
  KPI_EXECUTION_SELECT = "kpi-execution-selected",
  KPI_ACTIVE_STATUS_CHANGE = "kpi-active-status-change",
}
