### Get list of all industries
GET  http://localhost:5006/erp/industry/v1
content-type: application/json

### Get list of all industries
GET  http://localhost:5006/erp/serviceline/v1
content-type: application/json

