using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace RMT.Notification.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class releaseresourcev3 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 302L,
                columns: new[] { "subject", "template" },
                values: new object[] { "Project:<<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> - <<pipelineStatus:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>", "Dear User,<br/><br/> \r\nProject: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. has been <<pipelineStatus:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> on <<suspendedat:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. Your allocation has been auto-released from the project. <br/><br/> \r\nRegards,<br/>RMS Team<br/><br/>** This is an autogenerated email. Kindly do not respond to this.**" });

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 305L,
                column: "template",
                value: "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. has been <<pipelineStatus:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> on <<suspendedat:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. Your allocation has been auto-released from the project.");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 302L,
                columns: new[] { "subject", "template" },
                values: new object[] { "Project:<<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> - <<pipelineStatus :GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>", "Dear User,<br/><br/> \r\nProject: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. has been <<pipelineStatus:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> on <<SuspendedAt:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. Your allocation has been auto-released from the project. <br/><br/> \r\nRegards,<br/>RMS Team<br/><br/>** This is an autogenerated email. Kindly do not respond to this.**" });

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 305L,
                column: "template",
                value: "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. has been <<pipelineStatus :GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> on <<SuspendedAt:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. Your allocation has been auto-released from the project.");
        }
    }
}
