using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace RMT.Notification.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class updateseeder2606 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 290L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 291L);

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 296L,
                columns: new[] { "subject", "template" },
                values: new object[] { "Project: <<projectname>> Allocation Update", "Project: <<projectname>> allocations have been moved to new project code" });

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 297L,
                columns: new[] { "subject", "template" },
                values: new object[] { "Project: <<projectname>> Allocation Update", "Dear User,<br/><br/>\r\nAllocations on the Project: <<projectname>> have been moved from Project Code <<oldprojectcode>> to new Project Code <<newprojectcode>> due to an update in WCGT of the Job Code.<br/><br/>\r\nPlease <a href='<<BaseUrl:config>>project-details/<<newpipelinecode##>>/<<newjobcode##>>?tab=0'>click here<a/> for the details.<br/><br/>\r\nRegards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 296L,
                columns: new[] { "subject", "template" },
                values: new object[] { "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> Allocation Update", "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> allocations have been moved to new project code" });

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 297L,
                columns: new[] { "subject", "template" },
                values: new object[] { "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> Allocation Update", "Dear User,<br/><br/>\r\nAllocations on the Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> have been moved from Project Code <<jobcode>> to new Project Code <<newjobcode>> due to an update in WCGT of the Job Code.<br/><br/>\r\nPlease <a href='<<BaseUrl:config>>project-details/<<newpipelinecode##>>/<<newjobcode##>>?tab=0'>click here<a/> for the details.<br/><br/>\r\nRegards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**" });

            migrationBuilder.InsertData(
                table: "NotificationTemplates",
                columns: new[] { "Id", "cc", "is_active", "link_id", "module", "notification_type", "sub_module", "subject", "subscription_role", "template", "to", "type" },
                values: new object[,]
                {
                    { 290L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear User,<br/><br/>\r\nYour assignment to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been cancelled. Your Allocation Rejection request had been approved by <<updated_by>>.<br/><br/>\r\nRegards,<br/>RMS Team<br/><br/>** This is an autogenerated email. Kindly do not respond to this.**", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_REQUESTOR_APPROVED_REJECTION" },
                    { 291L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Your allocation to the project <<ProjectName:ResourceAllocationDetails:item_id>> has been cancelled. Allocation Rejection request has been approved by Resoruce Requestor <<updated_by>>.", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_REQUESTOR_APPROVED_REJECTION" }
                });
        }
    }
}
