using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace RMT.Notification.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class budgetfixv1 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 307L,
                column: "template",
                value: "Dear User,<br/><br/>\r\nProject: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> has consumed <<Limit:GETPROJECTBUDGET:pipelineCode|jobCode>> % of the budget in allocations.<br/><br/>\r\nPlease <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=2'>click here</a> for the details. Request you to review the future budget requirements and seek additional budget approval in WCGT if required.<br/><br/>\r\nRegards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 308L,
                column: "template",
                value: "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> has consumed <<Limit:GETPROJECTBUDGET:pipelineCode|jobCode>> % of the budget in allocations.");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 307L,
                column: "template",
                value: "Dear User,<br/><br/>\r\nProject: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> has consumed  <<Limit:GETPROJECTBUDGET:pipelineCode|jobCode>> % of the budget in allocations.<br/><br/>\r\nPlease <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=2'>click here</a> for the details. Request you to review the future budget requirements and seek additional budget approval in WCGT if required.<br/><br/>\r\nRegards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 308L,
                column: "template",
                value: "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> has consumed  <<Limit:GETPROJECTBUDGET:pipelineCode|jobCode>> % of the budget in allocations.");
        }
    }
}
