using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace RMT.Notification.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class notificationtemplate145update : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 145L);

            migrationBuilder.InsertData(
                table: "NotificationTemplates",
                columns: new[] { "Id", "cc", "is_active", "link_id", "module", "notification_type", "sub_module", "subject", "subscription_role", "template", "to", "type" },
                values: new object[,]
                {
                    { 145L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null,
                        @"Dear User,<br/><br/>
                        Resource allocation request has been rejected by employee <<empEmail:ResourceAllocationDetails:item_id>> for Project: <<ProjectName:ResourceAllocationDetails:item_id>><br/>
                        Rejection reason: <<ReasonForRejectionProvidedByEmployee>><br/><br/>
                        Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=4'> click here </a> to view details and review employee action.<br/><br/>
                        Regards,<br/> RMS Team <br/><br/> **This is an autogenerated email.Kindly do not respond to this.* *"
                    , "resource_requestor_allocation_wf,Reviewer", "NOTIFICATION_TO_RESOURCE_REQUESTOR_AND_REVIEWER_ON_EMPLOYEE_REJECTION_REQUESTOR_CONFIG_IS_ON" },
                });

        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 145L);
        }
    }
}
