using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace RMT.Notification.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class updateseeder1106 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 280L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 292L);

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 143L,
                columns: new[] { "cc", "template", "to" },
                values: new object[] { "Reviewer", "Dear User,<br/><br/>\r\n            Resource allocation request has been rejected by Employee: <<empEmail:ResourceAllocationDetails:item_id>> for Project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/>\r\n            You can terminate the workflow by <<due_date>> to make new allocations provided the allocated employee does not withdraw their rejection.<br/>\r\n            Rejection reason: <<ReasonForRejectionProvidedByEmployee>><br/><br/>\r\n\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=4'>click here</a> for the details.<br/><br/>\r\n\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.**", "resource_requestor_allocation_wf" });

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 144L,
                columns: new[] { "cc", "to" },
                values: new object[] { "Reviewer", "resource_requestor_allocation_wf" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 143L,
                columns: new[] { "cc", "template", "to" },
                values: new object[] { null, "Dear User,<br/><br/>\r\n\r\n            Resource allocation request has been rejected by Employee: <<empEmail:ResourceAllocationDetails:item_id>> for Project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/>\r\n            You can terminate the workflow by <<due_date>> to make new allocations provided the allocated employee does not withdraw their rejection.<br/>\r\n            Rejection reason: <<ReasonForRejectionProvidedByEmployee>><br/><br/>\r\n\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=4'>click here</a> for the details.<br/><br/>\r\n\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.**", "resource_requestor_allocation_wf,Reviewer" });

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 144L,
                columns: new[] { "cc", "to" },
                values: new object[] { null, "resource_requestor_allocation_wf,Reviewer" });

            migrationBuilder.InsertData(
                table: "NotificationTemplates",
                columns: new[] { "Id", "cc", "is_active", "link_id", "module", "notification_type", "sub_module", "subject", "subscription_role", "template", "to", "type" },
                values: new object[,]
                {
                    { 280L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear User,<br/><br/>\r\n            Resource allocation request has been rejected by Employee: <<empEmail:ResourceAllocationDetails:item_id>> for Project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/>\r\n            You can terminate the workflow by <<due_date>> to make new allocations provided the allocated employee does not withdraw their rejection.<br/>\r\n            Rejection reason: <<ReasonForRejectionProvidedByEmployee>><br/><br/>\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=4'>click here</a> for the details.<br/><br/>\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n            **This is an autogenerated email.Kindly do not respond to this.**", "resource_requestor_allocation_wf,Reviewer", "NOTIFICATION_TO_RESOURCE_REQUESTOR_AND_REVIEWER_ON_EMPLOYEE_REJECTION" },
                    { 292L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Resource allocation requests have been rejected for Project: <<ProjectName:ResourceAllocationDetails:item_id>> by employee <<empEmail:ResourceAllocationDetails:item_id>>.  Please make new allocations.", "resource_requestor_allocation_wf,Reviewer", "NOTIFICATION_TO_RESOURCE_REQUESTOR_AND_REVIEWER_ON_EMPLOYEE_REJECTION" }
                });
        }
    }
}
