using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace RMT.Notification.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class notification_change_for_timesheet : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                table: "NotificationTemplates",
                columns: new[] { "Id", "cc", "is_active", "link_id", "module", "notification_type", "sub_module", "subject", "subscription_role", "template", "to", "type" },
                values: new object[,]
                {
                    { 503L, null, true, null, "Notification", "PUSH", "Notification", "Project:<<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> - In Active", null, "Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> has consumed <<consumedtimesheetbudgetpct>>% of the budgeted hours in actuals.", "sender_for_notification", "NOTIFICATION_FOR_TIMESHEET_CROSSING_BUDGETED_THRESHOLD" },
                    { 504L, null, true, null, "Notification", "EMAIL", "Notification", "Project:<<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> - In Active", null, "Dear User,<br/><br/> \r\nProject: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> has consumed <<consumedtimesheetbudgetpct>>% of the budgeted hours in clocking.<br/><br/>Click here for the details. Request you to review the future budget requirements and seek additional budget approval in WCGT if required. <br/><br/> \r\nRegards,<br/>RMS Team<br/><br/>** This is an autogenerated email. Kindly do not respond to this.**", "sender_for_notification", "NOTIFICATION_FOR_TIMESHEET_CROSSING_BUDGETED_THRESHOLD" }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 503L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 504L);
        }
    }
}
