using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace RMT.Notification.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class correcting_additionalEl : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 155L,
                column: "to",
                value: "Requestor,Reviewer,AdditionalEl,AdditionalDelegate");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 156L,
                column: "to",
                value: "Requestor,Reviewer,AdditionalEl,AdditionalDelegate");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 264L,
                column: "cc",
                value: "ResourceRequestor,Reviewer,AdditionalEl,Delegate,AdditionalDelegate");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 303L,
                column: "to",
                value: "Requestor,Reviewer,AdditionalEl,AdditionalDelegate");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 304L,
                column: "to",
                value: "Requestor,Reviewer,AdditionalEl,AdditionalDelegate");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 306L,
                column: "to",
                value: "Requestor,Reviewer,AdditionalEl,AdditionalDelegate");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 309L,
                column: "to",
                value: "Requestor,Reviewer,AdditionalEl,AdditionalDelegate");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 310L,
                column: "to",
                value: "Requestor,Reviewer,AdditionalEl,AdditionalDelegate");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 313L,
                column: "to",
                value: "Requestor,Reviewer,AdditionalEl,AdditionalDelegate");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 314L,
                column: "to",
                value: "Requestor,Reviewer,AdditionalEl,AdditionalDelegate");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 315L,
                column: "to",
                value: "Requestor,Reviewer,AdditionalEl,AdditionalDelegate");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 402L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n                    Your Allocation on the Project: <<projectname>> has been moved from Project Code <<oldprojectcode>> to new Project Code <<newprojectcode>>.<br/><br/>\r\n                    Please <a href='<<BaseUrl:config>>project-details/<<newpipelinecode##>>/<<newjobcode##>>?tab=0'>click here<a/> for the details.<br/><br/>\r\n                    Regards,<br/><br/>\r\n                    RMS Team\r\n                    <br/><br/>** This is an autogenerated email. Kindly do not respond to this.**");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 155L,
                column: "to",
                value: "Requestor,Reviewer,AdditionalEL,AdditionalDelegate");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 156L,
                column: "to",
                value: "Requestor,Reviewer,AdditionalEL,AdditionalDelegate");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 264L,
                column: "cc",
                value: "ResourceRequestor,Reviewer,AdditionalEL,Delegate,AdditionalDelegate");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 303L,
                column: "to",
                value: "Requestor,Reviewer,AdditionalEL,AdditionalDelegate");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 304L,
                column: "to",
                value: "Requestor,Reviewer,AdditionalEL,AdditionalDelegate");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 306L,
                column: "to",
                value: "Requestor,Reviewer,AdditionalEL,AdditionalDelegate");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 309L,
                column: "to",
                value: "Requestor,Reviewer,AdditionalEL,AdditionalDelegate");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 310L,
                column: "to",
                value: "Requestor,Reviewer,AdditionalEL,AdditionalDelegate");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 313L,
                column: "to",
                value: "Requestor,Reviewer,AdditionalEL,AdditionalDelegate");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 314L,
                column: "to",
                value: "Requestor,Reviewer,AdditionalEL,AdditionalDelegate");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 315L,
                column: "to",
                value: "Requestor,Reviewer,AdditionalEL,AdditionalDelegate");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 402L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n                    Your Allocation on the Project: <<projectname>> has been moved from Project Code <<oldprojectcode>> to  new Project Code<<newprojectcode>>.<br/><br/>\r\n                    Please <a href='<<BaseUrl:config>>project-details/<<newpipelinecode##>>/<<newjobcode##>>?tab=0'>click here<a/> for the details.<br/><br/>\r\n                    Regards,<br/><br/>\r\n                    RMS Team\r\n                    <br/><br/>** This is an autogenerated email. Kindly do not respond to this.**");
        }
    }
}
