using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace RMT.Notification.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class PcJcCodeSpecialChar : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "NotificationTemplateLinks",
                keyColumn: "Id",
                keyValue: 13L,
                column: "Link",
                value: "/project-details/<<pipelinecode##>>/<<jobcode##>>?tab=0");

            migrationBuilder.UpdateData(
                table: "NotificationTemplateLinks",
                keyColumn: "Id",
                keyValue: 14L,
                column: "Link",
                value: "/project-details/<<pipelinecode##>>/<<jobcode##>>?tab=1");

            migrationBuilder.UpdateData(
                table: "NotificationTemplateLinks",
                keyColumn: "Id",
                keyValue: 15L,
                column: "Link",
                value: "/project-details/<<pipelinecode##>>/<<jobcode##>>?tab=2");

            migrationBuilder.UpdateData(
                table: "NotificationTemplateLinks",
                keyColumn: "Id",
                keyValue: 16L,
                column: "Link",
                value: "/project-details/<<pipelinecode##>>/<<jobcode##>>?tab=3");

            migrationBuilder.UpdateData(
                table: "NotificationTemplateLinks",
                keyColumn: "Id",
                keyValue: 17L,
                column: "Link",
                value: "/project-details/<<pipelinecode##>>/<<jobcode##>>?tab=4");

            migrationBuilder.UpdateData(
                table: "NotificationTemplateLinks",
                keyColumn: "Id",
                keyValue: 18L,
                column: "Link",
                value: "/project-details/<<pipelinecode##>>/<<jobcode##>>?tab=5");

            migrationBuilder.UpdateData(
                table: "NotificationTemplateLinks",
                keyColumn: "Id",
                keyValue: 19L,
                column: "Link",
                value: "/project-details/<<newPipelineCode##>>/<<newJobCode##>>?tab=0");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 139L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n                Your assignment on the Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been updated on date <<created_at>>.<br/><br/>\r\n                Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=3'>click here</a> for the details.<br/><br/>\r\n                Regards,<br/>\r\n                RMS Team<br/><br/>\r\n                **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 141L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n            Resource allocation request has been rejected by reviewer: <<updated_by:GetUserInfo:updated_by>> for employee: <<empEmail:ResourceAllocationDetails:item_id>> \r\n            in the project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/>\r\n            Rejection reason: <<ReasonForRejectionProvidedByReviewer>><br/><br/>\r\n            Request you to please allocate another resource.<br/><br/>\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=4'>click here</a> for the details.<br/><br/>\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 143L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n            Resource allocation request has been rejected by Employee: <<empEmail:ResourceAllocationDetails:item_id>> for Project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/>\r\n            You can terminate the workflow by <<due_date>> to make new allocations provided the allocated employee does not withdraw their rejection.<br/>\r\n            Rejection reason: <<ReasonForRejectionProvidedByEmployee>><br/><br/>\r\n\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=4'>click here</a> for the details.<br/><br/>\r\n\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 145L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n\r\n            Resource allocation request has been rejected by employee <<empEmail:ResourceAllocationDetails:item_id>> for Project: <<ProjectName:ResourceAllocationDetails:item_id>><br/>\r\n            Rejection reason: <<ReasonForRejectionProvidedByEmployee>><br/><br/>\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=4'>click here</a> to view details and review employee action.<br/><br/>\r\n\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 147L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n\r\n            You have been assigned to the Project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/>\r\n            The Project Allocation Period is:<br/>\r\n            Start Date: <<startdate:ResourceAllocationDetails:item_id>><br/> End Date: <<enddate:ResourceAllocationDetails:item_id>><br/> Hours: <<totaleffort:ResourceAllocationDetails:item_id>>.<br/><br/>\r\n\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=3'>click here</a> to view further details of the allocation and provide your agreement to the allocation.<br/><br/>\r\n            Please note, if you donot take any action, your allocation will be auto-approved by <<due_date>>.<br/><br/>\r\n\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 149L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n\r\n            You have been auto-allocated to the Project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/>\r\n            Start Date: <<startdate:ResourceAllocationDetails:item_id>><br/> End Date: <<enddate:ResourceAllocationDetails:item_id>><br/> Hours: <<totaleffort:ResourceAllocationDetails:item_id>>.<br/><br/>\r\n\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=3'>click here</a> to view allocation details.<br/><br/>\r\n\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 151L,
                column: "template",
                value: "Dear User,<br/><br/> You have been assigned to the Project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/> The Project Allocation Period is: Allocation Start Date: <<startdate:ResourceAllocationDetails:item_id>><br/>\r\n            End Date: <<enddate:ResourceAllocationDetails:item_id>><br/><br/> Hrs: <<totaleffort:ResourceAllocationDetails:item_id>>. \r\n            <br/><br/>\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=3'>click here</a> to view further details of the allocation and provide your agreement to the allocation.<br/><br/>\r\n            Please note, if you donot take any action, your allocation will be auto-approved by <<due_date>>.<br/><br/> \r\n            <br/><br/>Regards,<br/> RMS Team<br/><br/> ** This is an autogenerated email. Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 155L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n\r\n            Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> dates have been rolled forward from <<pipelineoldstartdate>> to <<pipelinestartdate>>. The system has taken the following actions based on the new start date which are set out below:<br/><br/>\r\n\r\n            1. For allocated employees who are available on the revised dates, new allocation workflow and relevant approvals will be triggered.<br/>\r\n            2. For allocated employees who are not available on certain dates in the new project period, those allocations will be moved to DRAFT state to review and change as appropriate.<br/>\r\n            3. For allocated employees who are not available for the requested period, they will be released from the project.<br/><br/>\r\n\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=3'>click here</a> for the details.<br/><br/>\r\n\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 267L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n            Allocation of Employees has  been updated on the   project : <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> as the  Project dates have been rolled forward from <<pipelineoldstartdate>> to <<pipelinestartdate>>.<br/><br/> \r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=3'>click here</a> for the details.<br/><br/> \r\n            Regards,<br/>\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 270L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n            Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> has been removed from Marketplace & has received <<employeeshowedinterestcount>> interests.<br/><br/>\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=5'>click here</a> for the details.<br/><br/>\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 277L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n            The Allocation request rejected by employee <<empEmail:ResourceAllocationDetails:item_id>> for Project: <<ProjectName:ResourceAllocationDetails:item_id>>  has been approved by Reviewer <<updated_by>>.<br/>\r\n            Please do new allocations.<br/><br/>\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=3'>click here</a> for the details.<br/><br/>\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 282L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n            Resource allocation request has been rejected by employee <<empEmail:ResourceAllocationDetails:item_id>> for Project: <<ProjectName:ResourceAllocationDetails:item_id>><br/>\r\n            Rejection reason: <<ReasonForRejectionProvidedByEmployee>><br/><br/>\r\n            Please <a href=' <<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=3'>click here</a> to view details and review employee action.<br/><br/>\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 286L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n            You have been auto-allocated to the Project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/>\r\n            Start Date: <<startdate:ResourceAllocationDetails:item_id>><br/> End Date: <<enddate:ResourceAllocationDetails:item_id>><br/> Hours: <<totaleffort:ResourceAllocationDetails:item_id>>.<br/><br/>\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=3'>click here</a> to view allocation details.<br/><br/>\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 297L,
                column: "template",
                value: "Dear User,\r\n            <br/>\r\n            <br/>\r\n            Allocations on the Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> have been moved from Project Code <<jobcode>> to new Project Code <<newjobcode>> due to an update in WCGT of the Job Code.<br/><br/>\r\n            Please <a href='<<BaseUrl:config>>project-details/<<newPipelineCode##>>/<<newJobCode##>>?tab=0'>click here<a/> for the details.\r\n            <br/>\r\n            <br/>\r\n\r\n            Regards,\r\n            <br/>\r\n            RMS Team\r\n            <br/>\r\n            <br/>\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 299L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n            <<User requesting>> has assigned you as Additional Delegate to the  Additional EL for  Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> on date <<DD-MM-YY>> <br/><br/>\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=0'>click here</a> for the details. You may contact <<User Requesting>> to discuss your responsibilities on the project in RMS.<br/><br/> \r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 303L,
                column: "template",
                value: "Dear User, <br/><br/> \r\n            cc: Delegate/ Add EL/ Add Delegate/ Reviewer Pipeline: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. has been <<pipelineStatus :GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> on <<:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. Any allocated resources have been auto-released. <br/><br/> \r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=0'>click here</a> for the details. <br/><br/>\r\n                Regards, <br/>\r\n                RMS Team <br/><br/>\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 306L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n\r\n            Employee: <<Employee Name>> is on leave for the below mentioned dates which conflicts with allocations on the Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>.<br/><br/>\r\n\r\n            Leave Dates : <<LeaveDates:EmployeeLeaves:empEmail>><br/><br/>\r\n\r\n            Plaese <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=3'>click here</a> to review allocation detail and kindly update the allocations.<br/><br/>\r\n\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 307L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n\r\n            Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> has consumed <<Limit:GETPROJECTBUDGET:pipelineCode|jobCode>> % of the budget in allocations.<br/><br/>\r\n\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=2'>click here</a> for the details. Request you to review the future budget requirements and seek additional budget approval in WCGT if required.<br/><br/>\r\n\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 310L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n\r\n            Allocation conflict for Employee: <<empEmail:ResourceAllocationDetails:item_id>> as the employee is not available.<br/><br/>\r\n\r\n            Kindly update the allocations accordingly.<br/><br/>\r\n\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=3'>click here</a> for the details.<br/><br/>\r\n\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 313L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n\r\n            Allocation conflicts in the project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> as Employee: <<empEmail:ResourceAllocationDetails:item_id>> is not available.<br/><br/>\r\n\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=3'>click here</a> to review allocation detail and kindly update the allocations.<br/><br/>\r\n\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 316L,
                column: "template",
                value: "Dear User,\r\n            <br/><br/>\r\n            The following activities have been performed on the below mentioned Job / Pipeline (s): \r\n            <br/>\r\n            <<RequistionSummary:Allocation:PipelineCode|JobCode>>\r\n            <br/>\r\n            <<RequstionSummary:Requistion:PipelineCode|JobCode>>\r\n            <br/>\r\n            <<AllocationSummary:AllocationPublished:PipelineCode|JobCode>>\r\n            <br/>\r\n            <<MarketPlaceSummary:MarketPlace:PipelineCode|JobCode>>\r\n\r\n            <br/> \r\n            Please <a href='<<BaseUrl:config>>projects'>click here </a> to view the details of project(s). \r\n            <br/>\r\n            <br/>\r\n            Regards,<br/>\r\n            RMS Team\r\n            <br />\r\n            <br/>\r\n            ** This is an autogenerated email. Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 317L,
                column: "template",
                value: "Dear  User, <br/>\r\n            <<userrequesting>> has assigned you Additional EL for project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> on date <<userassignmentdate>>\r\n             <br/> <br/> Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=0'>click here</a> for the details.  You may contact <<userrequesting>> to discuss your responsibilities on the project in RMS. <br/>\r\n            Regards, <br/>\r\n            <RMS Team> <br/>\r\n            ** This is an autogenerated email. Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 319L,
                column: "template",
                value: "Dear User,<br/>\r\n            You have been assigned as Delegate to <<delegateassignedby>> on  Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> on date <<delegateassignmentdate>>.\r\n           <br/> <br/> Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=0'>click here</a> for the details.  You may contact <<delegateassignedby>> to discuss your responsibilities on the project in RMS. <br/>\r\n            Regards,<br/>\r\n            <RMS Team><br/>\r\n            ** This is an autogenerated email. Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 321L,
                column: "template",
                value: "Dear User,<br/>\r\n            <<userrequesting>> has assigned you as Additional Delegate to the  Additional EL for  Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> on date <<userassignmentdate>>\r\n            <br/> <br/> Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=0'>click here</a> for the details. You may contact <<userrequesting>> to discuss your responsibilities on the project in RMS.  <br/>\r\n            Regards,<br/>\r\n            <RMS Team><br/>\r\n            ** This is an autogenerated email. Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 401L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n                Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> end date has been updated.<br/>\r\n                New end date is <<enddate>>.<br/>Please review allocations made to the project and take any necessary actions.\r\n                <br/><br/>\r\n                Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=0'>click here</a> for the details.\r\n                <br/><br/>\r\n                Regards,<br/>\r\n               RMS Team\r\n                <br/><br/>\r\n            **This is an autogenerated email.Kindly do not respond to this.* *");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "NotificationTemplateLinks",
                keyColumn: "Id",
                keyValue: 13L,
                column: "Link",
                value: "/project-details/<<pipelinecode>>/<<jobcode>>?tab=0");

            migrationBuilder.UpdateData(
                table: "NotificationTemplateLinks",
                keyColumn: "Id",
                keyValue: 14L,
                column: "Link",
                value: "/project-details/<<pipelinecode>>/<<jobcode>>?tab=1");

            migrationBuilder.UpdateData(
                table: "NotificationTemplateLinks",
                keyColumn: "Id",
                keyValue: 15L,
                column: "Link",
                value: "/project-details/<<pipelinecode>>/<<jobcode>>?tab=2");

            migrationBuilder.UpdateData(
                table: "NotificationTemplateLinks",
                keyColumn: "Id",
                keyValue: 16L,
                column: "Link",
                value: "/project-details/<<pipelinecode>>/<<jobcode>>?tab=3");

            migrationBuilder.UpdateData(
                table: "NotificationTemplateLinks",
                keyColumn: "Id",
                keyValue: 17L,
                column: "Link",
                value: "/project-details/<<pipelinecode>>/<<jobcode>>?tab=4");

            migrationBuilder.UpdateData(
                table: "NotificationTemplateLinks",
                keyColumn: "Id",
                keyValue: 18L,
                column: "Link",
                value: "/project-details/<<pipelinecode>>/<<jobcode>>?tab=5");

            migrationBuilder.UpdateData(
                table: "NotificationTemplateLinks",
                keyColumn: "Id",
                keyValue: 19L,
                column: "Link",
                value: "/project-details/<<newPipelineCode>>/<<newJobCode>>?tab=0");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 139L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n                Your assignment on the Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been updated on date <<created_at>>.<br/><br/>\r\n                Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=3'>click here</a> for the details.<br/><br/>\r\n                Regards,<br/>\r\n                RMS Team<br/><br/>\r\n                **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 141L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n            Resource allocation request has been rejected by reviewer: <<updated_by:GetUserInfo:updated_by>> for employee: <<empEmail:ResourceAllocationDetails:item_id>> \r\n            in the project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/>\r\n            Rejection reason: <<ReasonForRejectionProvidedByReviewer>><br/><br/>\r\n            Request you to please allocate another resource.<br/><br/>\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=4'>click here</a> for the details.<br/><br/>\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 143L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n            Resource allocation request has been rejected by Employee: <<empEmail:ResourceAllocationDetails:item_id>> for Project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/>\r\n            You can terminate the workflow by <<due_date>> to make new allocations provided the allocated employee does not withdraw their rejection.<br/>\r\n            Rejection reason: <<ReasonForRejectionProvidedByEmployee>><br/><br/>\r\n\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=4'>click here</a> for the details.<br/><br/>\r\n\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 145L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n\r\n            Resource allocation request has been rejected by employee <<empEmail:ResourceAllocationDetails:item_id>> for Project: <<ProjectName:ResourceAllocationDetails:item_id>><br/>\r\n            Rejection reason: <<ReasonForRejectionProvidedByEmployee>><br/><br/>\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=4'>click here</a> to view details and review employee action.<br/><br/>\r\n\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 147L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n\r\n            You have been assigned to the Project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/>\r\n            The Project Allocation Period is:<br/>\r\n            Start Date: <<startdate:ResourceAllocationDetails:item_id>><br/> End Date: <<enddate:ResourceAllocationDetails:item_id>><br/> Hours: <<totaleffort:ResourceAllocationDetails:item_id>>.<br/><br/>\r\n\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=3'>click here</a> to view further details of the allocation and provide your agreement to the allocation.<br/><br/>\r\n            Please note, if you donot take any action, your allocation will be auto-approved by <<due_date>>.<br/><br/>\r\n\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 149L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n\r\n            You have been auto-allocated to the Project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/>\r\n            Start Date: <<startdate:ResourceAllocationDetails:item_id>><br/> End Date: <<enddate:ResourceAllocationDetails:item_id>><br/> Hours: <<totaleffort:ResourceAllocationDetails:item_id>>.<br/><br/>\r\n\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=3'>click here</a> to view allocation details.<br/><br/>\r\n\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 151L,
                column: "template",
                value: "Dear User,<br/><br/> You have been assigned to the Project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/> The Project Allocation Period is: Allocation Start Date: <<startdate:ResourceAllocationDetails:item_id>><br/>\r\n            End Date: <<enddate:ResourceAllocationDetails:item_id>><br/><br/> Hrs: <<totaleffort:ResourceAllocationDetails:item_id>>. \r\n            <br/><br/>\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=3'>click here</a> to view further details of the allocation and provide your agreement to the allocation.<br/><br/>\r\n            Please note, if you donot take any action, your allocation will be auto-approved by <<due_date>>.<br/><br/> \r\n            <br/><br/>Regards,<br/> RMS Team<br/><br/> ** This is an autogenerated email. Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 155L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n\r\n            Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> dates have been rolled forward from <<pipelineoldstartdate>> to <<pipelinestartdate>>. The system has taken the following actions based on the new start date which are set out below:<br/><br/>\r\n\r\n            1. For allocated employees who are available on the revised dates, new allocation workflow and relevant approvals will be triggered.<br/>\r\n            2. For allocated employees who are not available on certain dates in the new project period, those allocations will be moved to DRAFT state to review and change as appropriate.<br/>\r\n            3. For allocated employees who are not available for the requested period, they will be released from the project.<br/><br/>\r\n\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=3'>click here</a> for the details.<br/><br/>\r\n\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 267L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n            Allocation of Employees has  been updated on the   project : <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> as the  Project dates have been rolled forward from <<pipelineoldstartdate>> to <<pipelinestartdate>>.<br/><br/> \r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=3'>click here</a> for the details.<br/><br/> \r\n            Regards,<br/>\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 270L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n            Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> has been removed from Marketplace & has received <<employeeshowedinterestcount>> interests.<br/><br/>\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=5'>click here</a> for the details.<br/><br/>\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 277L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n            The Allocation request rejected by employee <<empEmail:ResourceAllocationDetails:item_id>> for Project: <<ProjectName:ResourceAllocationDetails:item_id>>  has been approved by Reviewer <<updated_by>>.<br/>\r\n            Please do new allocations.<br/><br/>\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=3'>click here</a> for the details.<br/><br/>\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 282L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n            Resource allocation request has been rejected by employee <<empEmail:ResourceAllocationDetails:item_id>> for Project: <<ProjectName:ResourceAllocationDetails:item_id>><br/>\r\n            Rejection reason: <<ReasonForRejectionProvidedByEmployee>><br/><br/>\r\n            Please <a href=' <<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=3'>click here</a> to view details and review employee action.<br/><br/>\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 286L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n            You have been auto-allocated to the Project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/>\r\n            Start Date: <<startdate:ResourceAllocationDetails:item_id>><br/> End Date: <<enddate:ResourceAllocationDetails:item_id>><br/> Hours: <<totaleffort:ResourceAllocationDetails:item_id>>.<br/><br/>\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=3'>click here</a> to view allocation details.<br/><br/>\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 297L,
                column: "template",
                value: "Dear User,\r\n            <br/>\r\n            <br/>\r\n            Allocations on the Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> have been moved from Project Code <<jobcode>> to new Project Code <<newjobcode>> due to an update in WCGT of the Job Code.<br/><br/>\r\n            Please <a href='<<BaseUrl:config>>project-details/<<newPipelineCode>>/<<newJobCode>>?tab=0'>click here<a/> for the details.\r\n            <br/>\r\n            <br/>\r\n\r\n            Regards,\r\n            <br/>\r\n            RMS Team\r\n            <br/>\r\n            <br/>\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 299L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n            <<User requesting>> has assigned you as Additional Delegate to the  Additional EL for  Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> on date <<DD-MM-YY>> <br/><br/>\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=0'>click here</a> for the details. You may contact <<User Requesting>> to discuss your responsibilities on the project in RMS.<br/><br/> \r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 303L,
                column: "template",
                value: "Dear User, <br/><br/> \r\n            cc: Delegate/ Add EL/ Add Delegate/ Reviewer Pipeline: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. has been <<pipelineStatus :GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> on <<:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. Any allocated resources have been auto-released. <br/><br/> \r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=0'>click here</a> for the details. <br/><br/>\r\n                Regards, <br/>\r\n                RMS Team <br/><br/>\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 306L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n\r\n            Employee: <<Employee Name>> is on leave for the below mentioned dates which conflicts with allocations on the Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>.<br/><br/>\r\n\r\n            Leave Dates : <<LeaveDates:EmployeeLeaves:empEmail>><br/><br/>\r\n\r\n            Plaese <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=3'>click here</a> to review allocation detail and kindly update the allocations.<br/><br/>\r\n\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 307L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n\r\n            Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> has consumed <<Limit:GETPROJECTBUDGET:pipelineCode|jobCode>> % of the budget in allocations.<br/><br/>\r\n\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=2'>click here</a> for the details. Request you to review the future budget requirements and seek additional budget approval in WCGT if required.<br/><br/>\r\n\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 310L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n\r\n            Allocation conflict for Employee: <<empEmail:ResourceAllocationDetails:item_id>> as the employee is not available.<br/><br/>\r\n\r\n            Kindly update the allocations accordingly.<br/><br/>\r\n\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=3'>click here</a> for the details.<br/><br/>\r\n\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 313L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n\r\n            Allocation conflicts in the project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> as Employee: <<empEmail:ResourceAllocationDetails:item_id>> is not available.<br/><br/>\r\n\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=3'>click here</a> to review allocation detail and kindly update the allocations.<br/><br/>\r\n\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 316L,
                column: "template",
                value: "Dear User,\r\n            <br/><br/>\r\n            The following activities have been performed on the below mentioned Job / Pipeline (s): \r\n            <br/>\r\n            <<RequistionSummary:Allocation:PipelineCode|JobCode>>\r\n            <br/>\r\n            <<RequstionSummary:Requistion:PipelineCode|JobCode>>\r\n            <br/>\r\n            <<AllocationSummary:AllocationPublished:PipelineCode|JobCode>>\r\n            <br/>\r\n            <<MarketPlaceSummary:MarketPlace:PipelineCode|JobCode>>\r\n\r\n            <br/> \r\n            Please <a href='<<BaseUrl:config>>projects'>click here</a> to view the details of project(s). \r\n            <br/>\r\n            <br/>\r\n            Regards,<br/>\r\n            RMS Team\r\n            <br />\r\n            <br/>\r\n            ** This is an autogenerated email. Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 317L,
                column: "template",
                value: "Dear  User, <br/>\r\n            <<userrequesting>> has assigned you Additional EL for project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> on date <<userassignmentdate>>\r\n             <br/> <br/> Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=0'>click here</a> for the details.  You may contact <<userrequesting>> to discuss your responsibilities on the project in RMS. <br/>\r\n            Regards, <br/>\r\n            <RMS Team> <br/>\r\n            ** This is an autogenerated email. Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 319L,
                column: "template",
                value: "Dear User,<br/>\r\n            You have been assigned as Delegate to <<delegateassignedby>> on  Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> on date <<delegateassignmentdate>>.\r\n           <br/> <br/> Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=0'>click here</a> for the details.  You may contact <<delegateassignedby>> to discuss your responsibilities on the project in RMS. <br/>\r\n            Regards,<br/>\r\n            <RMS Team><br/>\r\n            ** This is an autogenerated email. Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 321L,
                column: "template",
                value: "Dear User,<br/>\r\n            <<userrequesting>> has assigned you as Additional Delegate to the  Additional EL for  Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> on date <<userassignmentdate>>\r\n            <br/> <br/> Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=0'>click here</a> for the details. You may contact <<userrequesting>> to discuss your responsibilities on the project in RMS.  <br/>\r\n            Regards,<br/>\r\n            <RMS Team><br/>\r\n            ** This is an autogenerated email. Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 401L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n                Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> end date has been updated.<br/>\r\n                New end date is <<enddate>>.<br/>Please review allocations made to the project and take any necessary actions.\r\n                <br/><br/>\r\n                Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=0'>click here</a> for the details.\r\n                <br/><br/>\r\n                Regards,<br/>\r\n               RMS Team\r\n                <br/><br/>\r\n            **This is an autogenerated email.Kindly do not respond to this.* *");
        }
    }
}
