using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace RMT.Notification.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class allocationwithdrawl : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 151L,
                column: "template",
                value: "Dear User,<br/><br/>As you have accepted the allocation, yo have now been allocated to the Project: <<ProjectName:ResourceAllocationDetail  s:item_id>> on <<startdate:ResourceAllocationDetails:item_id>>. \r\n                 <br/><br/>\r\n                 Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=3'>click here</a> to view further details.<br/><br/>\r\n                 <br/><br/>\r\n                 Regards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 151L,
                column: "template",
                value: "Dear User,<br/><br/> You have been assigned to the Project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/> The Project Allocation Period is:<br/> Start Date: <<startdate:ResourceAllocationDetails:item_id>><br/>\r\nEnd Date: <<enddate:ResourceAllocationDetails:item_id>><br/><br/> Hours: <<totaleffort:ResourceAllocationDetails:item_id>>. \r\n<br/><br/>\r\nPlease <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=3'>click here</a> to view further details of the allocation and provide your agreement to the allocation.<br/><br/>\r\nPlease note, if you donot take any action, your allocation will be auto-approved by <<due_date>>.<br/><br/> \r\n<br/><br/>\r\nRegards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**");
        }
    }
}
