using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace RMT.Notification.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class skillnitification1 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<DateTime>(
                name: "modifiedDate",
                table: "UserNotification",
                type: "timestamp without time zone",
                nullable: false,
                oldClrType: typeof(DateTime),
                oldType: "timestamp with time zone");

            migrationBuilder.AlterColumn<DateTime>(
                name: "createdDate",
                table: "UserNotification",
                type: "timestamp without time zone",
                nullable: false,
                oldClrType: typeof(DateTime),
                oldType: "timestamp with time zone");

            migrationBuilder.AlterColumn<DateTime>(
                name: "modifiedDate",
                table: "NotificationSubscription",
                type: "timestamp without time zone",
                nullable: true,
                oldClrType: typeof(DateTime),
                oldType: "timestamp with time zone",
                oldNullable: true);

            migrationBuilder.AlterColumn<DateTime>(
                name: "createdDate",
                table: "NotificationSubscription",
                type: "timestamp without time zone",
                nullable: true,
                oldClrType: typeof(DateTime),
                oldType: "timestamp with time zone",
                oldNullable: true);

            migrationBuilder.AlterColumn<DateTime>(
                name: "modifiedDate",
                table: "NotificationEntity",
                type: "timestamp without time zone",
                nullable: false,
                oldClrType: typeof(DateTime),
                oldType: "timestamp with time zone");

            migrationBuilder.AlterColumn<DateTime>(
                name: "createdDate",
                table: "NotificationEntity",
                type: "timestamp without time zone",
                nullable: false,
                oldClrType: typeof(DateTime),
                oldType: "timestamp with time zone");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 123L,
                column: "template",
                value: "Hi Team,\r\n\r\nEmployee <employee_name> has been disabled from RMS. Please review employee allocations on the project <ProjectName>. \r\n\r\nPlease <click_link> here for the details.\r\n\r\nRegards,\r\nRMS Team\r\n\r\n** This is an autogenerated email. Kindly do not respond to this.**");

            migrationBuilder.InsertData(
                table: "NotificationTemplates",
                columns: new[] { "Id", "is_active", "link_id", "module", "notification_type", "sub_module", "subject", "subscription_role", "template", "to", "type" },
                values: new object[,]
                {
                    { 130L, true, 1L, "", "EMAIL", "", "Skill Assessment Request submitted for Review", null, "Dear User,\r\n\r\nYour skill assessment request has been sent to your Supercoach <SuperCoach> for review. \r\n\r\nPlease <click_link> here to track the progress of the your submission request.\r\n\r\nRegards,\r\nRMS Team\r\n\r\n** This is an autogenerated email. Kindly do not respond to this.**", "employee_name", "EMPLOYEE_SHALL_BE_NOTIFIED_FOR_SUBMISSION_OF_THEIR_SKILL_UPDATE_REQUEST_SENT_TO_SUPRERCOACH" },
                    { 131L, true, 1L, "", "PUSH", "", "Skill Assessment Request submitted for Review", null, "Your skill assessment request has been submitted  for review to <SuperCoach> .", "employee_name", "EMPLOYEE_SHALL_BE_NOTIFIED_FOR_SUBMISSION_OF_THEIR_SKILL_UPDATE_REQUEST_SENT_TO_SUPRERCOACH" }
                });

            migrationBuilder.InsertData(
                table: "NotificationPlaceHolder",
                columns: new[] { "id", "is_active", "is_required", "name", "notification_template_id" },
                values: new object[,]
                {
                    { 1233L, true, true, "employee_name", 130L },
                    { 1234L, true, true, "SuperCoach", 130L },
                    { 1235L, true, true, "click_link", 130L },
                    { 1236L, true, true, "employee_name", 131L },
                    { 1237L, true, true, "SuperCoach", 131L }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "NotificationPlaceHolder",
                keyColumn: "id",
                keyValue: 1233L);

            migrationBuilder.DeleteData(
                table: "NotificationPlaceHolder",
                keyColumn: "id",
                keyValue: 1234L);

            migrationBuilder.DeleteData(
                table: "NotificationPlaceHolder",
                keyColumn: "id",
                keyValue: 1235L);

            migrationBuilder.DeleteData(
                table: "NotificationPlaceHolder",
                keyColumn: "id",
                keyValue: 1236L);

            migrationBuilder.DeleteData(
                table: "NotificationPlaceHolder",
                keyColumn: "id",
                keyValue: 1237L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 130L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 131L);

            migrationBuilder.AlterColumn<DateTime>(
                name: "modifiedDate",
                table: "UserNotification",
                type: "timestamp with time zone",
                nullable: false,
                oldClrType: typeof(DateTime),
                oldType: "timestamp without time zone");

            migrationBuilder.AlterColumn<DateTime>(
                name: "createdDate",
                table: "UserNotification",
                type: "timestamp with time zone",
                nullable: false,
                oldClrType: typeof(DateTime),
                oldType: "timestamp without time zone");

            migrationBuilder.AlterColumn<DateTime>(
                name: "modifiedDate",
                table: "NotificationSubscription",
                type: "timestamp with time zone",
                nullable: true,
                oldClrType: typeof(DateTime),
                oldType: "timestamp without time zone",
                oldNullable: true);

            migrationBuilder.AlterColumn<DateTime>(
                name: "createdDate",
                table: "NotificationSubscription",
                type: "timestamp with time zone",
                nullable: true,
                oldClrType: typeof(DateTime),
                oldType: "timestamp without time zone",
                oldNullable: true);

            migrationBuilder.AlterColumn<DateTime>(
                name: "modifiedDate",
                table: "NotificationEntity",
                type: "timestamp with time zone",
                nullable: false,
                oldClrType: typeof(DateTime),
                oldType: "timestamp without time zone");

            migrationBuilder.AlterColumn<DateTime>(
                name: "createdDate",
                table: "NotificationEntity",
                type: "timestamp with time zone",
                nullable: false,
                oldClrType: typeof(DateTime),
                oldType: "timestamp without time zone");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 123L,
                column: "template",
                value: "Hi <Team>,\r\n\r\nEmployee <employee_name> has been disabled from RMS. Please review employee allocations on the project <ProjectName>. \r\n\r\nPlease <click_link> here for the details.\r\n\r\nRegards,\r\nRMS Team\r\n\r\n** This is an autogenerated email. Kindly do not respond to this.**");
        }
    }
}
