using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace RMT.Notification.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class skills_4 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 136L,
                column: "template",
                value: "Dear User,\r\n\r\nFollowing tasks are pending for your action:\r\n\r\n<TABLE_DESIGN_FOR_ALLOCATION>. \r\n\r\n  \r\n\r\n <TABLE_DESIGN_FOR_SKILL> . \r\n\r\nPlease <click_link> here for more details .\r\n\r\nRegards,\r\nRMS Team\r\n\r\n** This is an autogenerated email. Kindly do not respond to this.**");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 136L,
                column: "template",
                value: "Dear User,\r\n\r\nFollowing tasks are pending for your action:\r\n\r\nAllocation Requests:\r\n\r\nIn case no action is taken on the allocation request, the allocation will be auto-approved.\r\n\r\n<TABLE_DESIGN_FOR_ALLOCATION>. \r\n\r\n \r\n\r\n Skill Assessment Requests: \r\n\r\n <TABLE_DESIGN_FOR_SKILL> . \r\n\r\nPlease <click_link> here for the details and approve/reject the request.\r\n\r\nRegards,\r\nRMS Team\r\n\r\n** This is an autogenerated email. Kindly do not respond to this.**");
        }
    }
}
