using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace RMT.Notification.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class newupdatemig260624 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 286L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 287L);

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 150L,
                column: "template",
                value: "Your allocation has been auto-approved for the Project <<ProjectName:ResourceAllocationDetails:item_id>> on <<startdate:ResourceAllocationDetails:item_id>>");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 151L,
                column: "template",
                value: "Dear User,<br/><br/> You have been assigned to the Project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/> The Project Allocation Period is:<br/> Start Date: <<startdate:ResourceAllocationDetails:item_id>><br/>\r\nEnd Date: <<enddate:ResourceAllocationDetails:item_id>><br/><br/> Hours: <<totaleffort:ResourceAllocationDetails:item_id>>. \r\n<br/><br/>\r\nPlease <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=3'>click here</a> to view further details of the allocation and provide your agreement to the allocation.<br/><br/>\r\nPlease note, if you donot take any action, your allocation will be auto-approved by <<due_date>>.<br/><br/> \r\n<br/><br/>\r\nRegards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 152L,
                column: "template",
                value: "You have successfully been allocated to the project <<ProjectName:ResourceAllocationDetails:item_id>> on <<startdate:ResourceAllocationDetails:item_id>>");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 150L,
                column: "template",
                value: "A");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 151L,
                column: "template",
                value: "Dear User,<br/><br/> You have been assigned to the Project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/> The Project Allocation Period is: Allocation Start Date: <<startdate:ResourceAllocationDetails:item_id>><br/>\r\nEnd Date: <<enddate:ResourceAllocationDetails:item_id>><br/><br/> Hrs: <<totaleffort:ResourceAllocationDetails:item_id>>. \r\n<br/><br/>\r\nPlease <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=3'>click here</a> to view further details of the allocation and provide your agreement to the allocation.<br/><br/>\r\nPlease note, if you donot take any action, your allocation will be auto-approved by <<due_date>>.<br/><br/> \r\n<br/><br/>\r\nRegards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 152L,
                column: "template",
                value: "A");

            migrationBuilder.InsertData(
                table: "NotificationTemplates",
                columns: new[] { "Id", "cc", "is_active", "link_id", "module", "notification_type", "sub_module", "subject", "subscription_role", "template", "to", "type" },
                values: new object[,]
                {
                    { 286L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear User,<br/><br/>\r\nYou have been auto-allocated to the Project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/>\r\nStart Date: <<startdate:ResourceAllocationDetails:item_id>><br/> End Date: <<enddate:ResourceAllocationDetails:item_id>><br/> Hours: <<totaleffort:ResourceAllocationDetails:item_id>>.<br/><br/>\r\nPlease <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=3'>click here</a> to view allocation details.<br/><br/>\r\nRegards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_AUTO_APPROVED_AFTER_EMPLOYEE_DUE_DATE_CROSS" },
                    { 287L, null, true, 16L, "Notification", "PUSH", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "A", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_AUTO_APPROVED_AFTER_EMPLOYEE_DUE_DATE_CROSS" }
                });
        }
    }
}
