using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace RMT.Notification.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class updateseedermig2206 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 147L,
                column: "template",
                value: "Dear User,<br/><br/>\r\nYou have been allocated to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> on <<startdate:ResourceAllocationDetails:item_id>>.<br/><br/>\r\nPlease <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=3'>click here</a> or the details.<br/><br/>\r\nRegards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 148L,
                column: "template",
                value: "You have been successfully allocated to the project <<ProjectName:ResourceAllocationDetails:item_id>> on <<startdate:ResourceAllocationDetails:item_id>>.");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 147L,
                column: "template",
                value: "Dear User,<br/><br/>\r\nYou have been allocated to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> on <<created_at>>.<br/><br/>\r\nPlease <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=3'>click here</a> or the details.<br/><br/>\r\nRegards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 148L,
                column: "template",
                value: "You have been successfully allocated to the project <<ProjectName:ResourceAllocationDetails:item_id>> on <<created_at>>.");
        }
    }
}
