using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace RMT.Notification.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class Seeder23063 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 311L,
                column: "template",
                value: "Dear User,<br/><br/>\r\nYour skill self-assessment request for the following skill has been approved by your Supercoach \r\n<<updated_by>>. <br/><br/>\r\nSkill Name : <<skillname:UserSkill:item_id>><br/>\r\nSkill Proficiency Level : <<Proficiency:UserSkill:item_id>><br/><br/>Test\r\nPlease <a href='<<BaseUrl:config>>myskill'>click here</a> for the details.<br/><br/>\r\nRegards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 311L,
                column: "template",
                value: "Dear User,<br/><br/>\r\nYour skill self-assessment request for the following skill has been approved by your Supercoach \r\n<<updated_by>>. <br/><br/>\r\nSkill Name : <<skillname:UserSkill:item_id>><br/>\r\nSkill Proficiency Level : <<Proficiency:UserSkill:item_id>><br/><br/>\r\nPlease <a href='<<BaseUrl:config>>myskill'>click here</a> for the details.<br/><br/>\r\nRegards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**");
        }
    }
}
