using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace RMT.Notification.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class updateseeder2206 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 282L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 284L);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                table: "NotificationTemplates",
                columns: new[] { "Id", "cc", "is_active", "link_id", "module", "notification_type", "sub_module", "subject", "subscription_role", "template", "to", "type" },
                values: new object[,]
                {
                    { 282L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear User,<br/><br/>\r\nResource allocation request has been rejected by employee <<empEmail:ResourceAllocationDetails:item_id>> for Project: <<ProjectName:ResourceAllocationDetails:item_id>><br/>\r\nRejection reason: <<ReasonForRejectionProvidedByEmployee>><br/><br/>\r\nPlease <a href=' <<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=3'>click here</a> to view details and review employee action.<br/><br/>\r\nRegards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**", "resource_requestor_allocation_wf", "NOTIFICATION_TO_RESOURCE_REQUESTOR_AND_REVIEWER_ON_EMPLOYEE_REJECTION_REQUESTOR_CONFIG_IS_ON" },
                    { 284L, null, true, 16L, "Notification", "PUSH", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Resource allocation requests have been rejected for Project: <<ProjectName:ResourceAllocationDetails:item_id>> by employee <<empEmail:ResourceAllocationDetails:item_id>>. Please review employee action", "resource_requestor_allocation_wf", "NOTIFICATION_TO_RESOURCE_REQUESTOR_AND_REVIEWER_ON_EMPLOYEE_REJECTION_REQUESTOR_CONFIG_IS_ON" }
                });
        }
    }
}
