using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace RMT.Notification.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class skillseederadded1206 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                table: "NotificationTemplates",
                columns: new[] { "Id", "cc", "is_active", "link_id", "module", "notification_type", "sub_module", "subject", "subscription_role", "template", "to", "type" },
                values: new object[,]
                {
                    { 323L, null, true, null, "Notification", "PUSH", "Notification", "Skill Assessment Review Updates", null, "Your skill  <<skillname:UserSkill:item_id>> assessment  has been declined by your Supercoach  <<createdby:UserSkill:item_id>> ", "userskillemail", "SUPERCOACH_REJECTED_SKILL_ASSESSMENT_REQUEST" },
                    { 324L, null, true, null, "Notification", "EMAIL", "Notification", "Skill Assessment Review Updates", null, "Dear User, <br/><br/> \r\n\r\n                    Your skill assessment approval has been declined by your Supercoach   <<createdby:UserSkill:item_id>>. <br/><br/> \r\n\r\n                    Skill Name : <<skillname:UserSkill:item_id>><br/>\r\n                    Skill Proficiency Level : <<Proficiency:UserSkill:item_id>><br/>\r\n                    Reason : <<remarks:UserSkill:item_id>> <br/><br/>\r\n\r\n                    Please <a href='<<BaseUrl:config>>myskill'>click here</a> for the details and reach out to your Supercoach for any further clarifications.<br/><br/> \r\n\r\n                    Regards, <br/>  \r\n                    RMS Team <br/>  \r\n                    ** This is an autogenerated email. Kindly do not respond to this.** ", "userskillemail", "SUPERCOACH_REJECTED_SKILL_ASSESSMENT_REQUEST" }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 323L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 324L);
        }
    }
}
