using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace RMT.Notification.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class notificationmultpledataseederupdate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 275L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 281L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 283L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 285L);

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 141L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n            Resource allocation request has been rejected by reviewer: <<updated_by:GetUserInfo:updated_by>> for employee: <<empEmail:ResourceAllocationDetails:item_id>> \r\n            in the project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/>\r\n            Rejection reason: <<ReasonForRejectionProvidedByReviewer>><br/><br/>\r\n            Request you to please allocate another resource.<br/><br/>\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=4'>click here</a> for the details.<br/><br/>\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 300L,
                column: "template",
                value: "You have been assigned the Admin role.Please check your email or visit the User Management Section.");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 141L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n\r\n            Resource allocation request has been rejected by reviewer: <<updated_by:GetUserInfo:updated_by>> for employee: <<empEmail:ResourceAllocationDetails:item_id>> in the project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/>\r\n            Rejection reason: <<ReasonForRejectionProvidedByReviewer>><br/><br/>\r\n\r\n            Please do new allocation.<br/><br/>\r\n\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=4'>click here</a> for the details.<br/><br/>\r\n\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 300L,
                column: "template",
                value: "You have been assigned Admin role. Please check your email for details.");

            migrationBuilder.InsertData(
                table: "NotificationTemplates",
                columns: new[] { "Id", "cc", "is_active", "link_id", "module", "notification_type", "sub_module", "subject", "subscription_role", "template", "to", "type" },
                values: new object[,]
                {
                    { 275L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear User,<br/><br/>\r\n            Resource allocation request has been rejected by reviewer: <<updated_by:GetUserInfo:updated_by>> for  employee: <<empEmail:ResourceAllocationDetails:item_id>> in the project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/> \r\n            Rejection reason: <<ReasonForRejectionProvidedByReviewer>><br/>\r\n            Please do new allocation.<br/><br/>\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=4'>click here</a> for the details.<br/><br/>\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n            **This is an autogenerated email.Kindly do not respond to this.**", "resource_requestor_allocation_wf", "EMPLOYEE_ALLOCATION_REJECTED_BY_REVIEWER_NOTIFICATION_TO_RESOURCE_REQUESTOR" },
                    { 281L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Resource allocation requests have been rejected for Project: <<ProjectName:ResourceAllocationDetails:item_id>> by reviewer <<updated_by>>.  Please do new allocations", "resource_requestor_allocation_wf", "EMPLOYEE_ALLOCATION_REJECTED_BY_REVIEWER_NOTIFICATION_TO_RESOURCE_REQUESTOR" },
                    { 283L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "You have been successfully  allocated  to the project <<ProjectName:ResourceAllocationDetails:item_id>>.", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_AFTER_REVIEWER_ACCEPTS" },
                    { 285L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear  User,<br/><br/>\r\n            You have been assigned to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> . The Project Allocation Period is:<br/>\r\n            Start Date: <<startdate:ResourceAllocationDetails:item_id>><br/> End Date: <<enddate:ResourceAllocationDetails:item_id>><br/> Hours: <<totaleffort:ResourceAllocationDetails:item_id>>.<br/><br/>\r\n            Please <a href='<<BaseUrl:config>>myapproval'>click here</a> here to view further details of the allocation and provide your agreement to the allocation.<br/><br/>\r\n            Please note, if you donot take any action, your allocation will be auto-approved by <<due_date>>.<br/><br/>\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n            **This is an autogenerated email.Kindly do not respond to this.**", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_AFTER_REVIEWER_ACCEPTS" }
                });
        }
    }
}
