using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace RMT.Notification.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class seederupdate1106 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 173L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 174L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 278L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 279L);

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 139L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n                Your assignment on the Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been updated on date <<created_at>>.<br/><br/>\r\n                Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=3'>click here</a> for the details.<br/><br/>\r\n                Regards,<br/>\r\n                RMS Team<br/><br/>\r\n                **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 140L,
                column: "template",
                value: "You assignment on the project  <<ProjectName:ResourceAllocationDetails:item_id>>  has been updated on date <<modifiedat>>. ");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 401L,
                column: "notification_type",
                value: "EMAIL");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 139L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n\r\n            Your assignment on the Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been updated on date <<created_at>>.<br/><br/>\r\n\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=3'>click here</a> for the details.<br/><br/>\r\n\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 140L,
                column: "template",
                value: "Dear User,<br/><br/> Your assignment on the Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been updated on date <<created_at>>.<br/><br/> Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=3'>click here</a> for the details.<br/><br/> Regards,<br/> RMS Team<br/><br/> ** This is an autogenerated email. Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 401L,
                column: "notification_type",
                value: "PUSH");

            migrationBuilder.InsertData(
                table: "NotificationTemplates",
                columns: new[] { "Id", "cc", "is_active", "link_id", "module", "notification_type", "sub_module", "subject", "subscription_role", "template", "to", "type" },
                values: new object[,]
                {
                    { 173L, "", true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> end date update.", null, "Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> end date has been updated. New End Date is <<enddate>>. Please take necessary actions.", "ResourceRequestor,Reviewer,AdditionalEl,AdditionalDelegate,Delegate", "PROJECT_END_DATE_UPDATE_NOTIFICATION" },
                    { 174L, "", true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> end date update.", null, "Dear User,<br/><br/>\r\n                Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> End Date has been updated.New End Date is <<enddate>>.<br/>Please review allocations made to the project and take any necessary actions.\r\n                <br/><br/>\r\n                Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=0'>click here</a> for the details.\r\n                <br/><br/>\r\n                Regards,<br/>\r\n               RMS Team\r\n                <br/><br/>\r\n            **This is an autogenerated email.Kindly do not respond to this.* *", "ResourceRequestor,Reviewer,AdditionalEl,AdditionalDelegate,Delegate", "PROJECT_END_DATE_UPDATE_NOTIFICATION" },
                    { 278L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear User,<br/><br/>\r\n            Your  assignment on the Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been updated on date <<created_at>>.<br/><br/>\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=3'>click here</a> for the details.<br/><br/>\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n            ** This is an autogenerated email. Kindly do not respond to this.**", "employee_name_allocation_wf", "NOTIFICATION_FOR_ALLOCATION_UPDATE_TO_EMPLOYEE" },
                    { 279L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear User,<br/><br/>\r\n            Your assignment on the Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been updated on date <<created_at>>.<br/><br/>\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=3'>click here</a> for the details.<br/><br/>\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n            **This is an autogenerated email.Kindly do not respond to this.**", "employee_name_allocation_wf", "NOTIFICATION_FOR_ALLOCATION_UPDATE_TO_EMPLOYEE" }
                });
        }
    }
}
