using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace RMT.Notification.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class notificationtemplateseederv1Adddata : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                table: "NotificationTemplates",
                columns: new[] { "Id", "cc", "is_active", "link_id", "module", "notification_type", "sub_module", "subject", "subscription_role", "template", "to", "type" },
                values: new object[,]
                {
                    { 42L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "You have been assigned to the Project <<ProjectName:ResourceAllocationDetails:item_id>> on date <<due_date>>.", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_FOR_HIS_ALLOCATION_TASK_TO_PROJECT" },
                    { 43L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear User,<br/><br/>\r\n\r\n            You have been assigned to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> on date <<created_at>>.<br/>\r\n            The Project Allocation Period is:<br/>\r\n            Allocation Start Date: <<startDate:ResourceAllocationDetails:item_id>> End Date: <<endDate:ResourceAllocationDetails:item_id>> Hrs: <<confirmedPerDayHours:ResourceAllocationDetails:item_id>>.<br/><br/>\r\n\r\n            Please <a href=' << BaseUrl:config >> myapproval'>Click here</a> to view further details of the allocation.<br/><br/>\r\n\r\n            Please note, if you are unable to review the request for approval, it will be auto - approved by << due_date >>.< br />< br />\r\n\r\n            Regards,< br />\r\n            << RMS Team >>< br />< br />\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.* *", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_FOR_HIS_ALLOCATION_TASK_TO_PROJECT" },
                    { 137L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear User,<br/><br/>\r\n\r\n            Allocation requests rejected by employee <<empEmail:ResourceAllocationDetails:item_id>> for Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been cancelled by Reviewer <<updated_by>>.<br/><br/>\r\n\r\n            Please do new allocations.<br/><br/>\r\n            <a href=' << BaseUrl:config >> project - details /<< pipelinecode >>/<< jobcode >>? tab = 4'>Click here</a> for the details.<br/><br/>\r\n\r\n            Regards,< br />\r\n            << RMS Team >>< br />< br />\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.* *", "resource_requestor_allocation_wf", "REVIEWER_ACCEPTED_EMPLOYEE_REJECTION_RESPONSE" },
                    { 138L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear User, Allocation requests rejected by employee <<ProjectName:ResourceAllocationDetails:item_id>> for Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been cancelled by Reviewer <<updated_by>>. Please do new allocations. Please <<click_link>> here for the details. Regards, <<RMS Team>> ** This is an autogenerated email. Kindly do not respond to this.**", "resource_requestor_allocation_wf", "REVIEWER_ACCEPTED_EMPLOYEE_REJECTION_RESPONSE" },
                    { 139L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear User,<br/><br/>\r\n\r\n            Your assignment on the Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been updated on date <<created_at>>.<br/><br/>\r\n\r\n            Please <a href=' << BaseUrl:config >> project - details /<< pipelinecode >>/<< jobcode >>? tab = 3'>Click here</a> for the details.<br/><br/>\r\n\r\n            Regards,< br />\r\n            << RMS Team >>< br />< br />\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.* *", "employee_name_allocation_wf", "NOTIFICATION_FOR_ALLOCATION_UPDATE_TO_EMPLOYEE" },
                    { 140L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear User, Your assignment on the Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been updated on date <<created_at>>. Please <<click_link>> here for the details. Regards, <<RMS Team>> ** This is an autogenerated email. Kindly do not respond to this.**", "employee_name_allocation_wf", "NOTIFICATION_FOR_ALLOCATION_UPDATE_TO_EMPLOYEE" },
                    { 141L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear User,<br/><br/>\r\n\r\n            Resource allocation request has been rejected by reviewer: <<updated_by:GetUserInfo:updated_by>> for employee: <<empEmail:ResourceAllocationDetails:item_id>> in the project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/>\r\n            Rejection reason: <<ReasonForRejectionProvidedByReviewer>><br/><br/>\r\n\r\n            Please do new allocation.<br/><br/>\r\n\r\n            Please <a href=' << BaseUrl:config >> project - details /<< pipelinecode >>/<< jobcode >>? tab = 4'>Click here</a> for the details.<br/><br/>\r\n\r\n            Regards,< br />\r\n            << RMS Team >>< br />< br />\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.* *", "resource_requestor_allocation_wf", "EMPLOYEE_ALLOCATION_REJECTED_BY_REVIEWER_NOTIFICATION_TO_RESOURCE_REQUESTOR" },
                    { 142L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Resource allocation requests have been rejected for Project: <<ProjectName:ResourceAllocationDetails:item_id>> by reviewer <<updated_by>>. Please do new allocations", "resource_requestor_allocation_wf", "EMPLOYEE_ALLOCATION_REJECTED_BY_REVIEWER_NOTIFICATION_TO_RESOURCE_REQUESTOR" },
                    { 143L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear User,<br/><br/>\r\n\r\n            Resource allocation request has been rejected by Employee: <<empEmail:ResourceAllocationDetails:item_id>> for Project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/>\r\n            You can terminate the workflow to make new allocations provided the allocated employee does not withdraw their rejection.<br/>\r\n            Rejection reason: <<ReasonForRejectionProvidedByEmployee>><br/><br/>\r\n\r\n            Please <a href=' << BaseUrl:config >> project - details /<< pipelinecode >>/<< jobcode >>? tab = 4'>Click here</a> for the details.<br/><br/>\r\n\r\n            Regards,< br />\r\n            << RMS Team >>< br />< br />\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.* *", "resource_requestor_allocation_wf,Reviewer", "NOTIFICATION_TO_RESOURCE_REQUESTOR_AND_REVIEWER_ON_EMPLOYEE_REJECTION" },
                    { 144L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Resource allocation requests have been rejected for Project: <<ProjectName:ResourceAllocationDetails:item_id>> by employee <<empEmail:ResourceAllocationDetails:item_id>>. Please make new allocations.", "resource_requestor_allocation_wf,Reviewer", "NOTIFICATION_TO_RESOURCE_REQUESTOR_AND_REVIEWER_ON_EMPLOYEE_REJECTION" },
                    { 145L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear User,<br/><br/>\r\n\r\n            Resource allocation request has been rejected by employee <<empEmail:ResourceAllocationDetails:item_id>> for Project: <<ProjectName:ResourceAllocationDetails:item_id>><br/>\r\n            Rejection reason: <<ReasonForRejectionProvidedByEmployee>><br/><br/>\r\n            <a href=' << BaseUrl:config >> project - details /<< pipelinecode >>/<< jobcode >>? tab = 4'>Click here</a> to view details and review employee action.<br/><br/>\r\n\r\n            Regards,< br />\r\n            << RMS Team >>< br />< br />\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.* *", "resource_requestor_allocation_wf", "NOTIFICATION_TO_RESOURCE_REQUESTOR_AND_REVIEWER_ON_EMPLOYEE_REJECTION_REQUESTOR_CONFIG_IS_ON" },
                    { 146L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Resource allocation requests have been rejected for Project: <<ProjectName:ResourceAllocationDetails:item_id>> by employee <<empEmail:ResourceAllocationDetails:item_id>>. Please review employee action", "resource_requestor_allocation_wf", "NOTIFICATION_TO_RESOURCE_REQUESTOR_AND_REVIEWER_ON_EMPLOYEE_REJECTION_REQUESTOR_CONFIG_IS_ON" },
                    { 147L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear User,<br/><br/>\r\n\r\n            You have been assigned to the Project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/>\r\n            The Project Allocation Period is:<br/>\r\n            Allocation Start Date: <<startDate:ResourceAllocationDetails:item_id>> End Date: <<endDate:ResourceAllocationDetails:item_id>> Hrs: <<totalEffort:ResourceAllocationDetails:item_id>>.<br/><br/>\r\n\r\n            Please <a href=' << BaseUrl:config >> myapproval'>Click here</a> to view further details of the allocation.<br/><br/>\r\n\r\n            Regards,< br />\r\n            << RMS Team >>< br />< br />\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.* *", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_AFTER_REVIEWER_ACCEPTS" },
                    { 148L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "You have been successfully allocated to the project <<ProjectName:ResourceAllocationDetails:item_id>>.", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_AFTER_REVIEWER_ACCEPTS" },
                    { 149L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear User,<br/><br/>\r\n\r\n            You have been auto-allocated to the Project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/>\r\n            Allocation Start Date: <<startDate:ResourceAllocationDetails:item_id>> End Date: <<endDate:ResourceAllocationDetails:item_id>> Hrs: <<totalEffort:ResourceAllocationDetails:item_id>>.<br/><br/>\r\n\r\n            <a href=' << BaseUrl:config >> project - details /<< pipelinecode >>/<< jobcode >>? tab = 3'>Click here</a> to view allocation details.<br/><br/>\r\n\r\n            Regards,< br />\r\n            << RMS Team >>< br />< br />\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.* *", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_AUTO_APPROVED_AFTER_EMPLOYEE_DUE_DATE_CROSS" },
                    { 150L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "A", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_AUTO_APPROVED_AFTER_EMPLOYEE_DUE_DATE_CROSS" },
                    { 151L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear User, You have been assigned to the Project: <<ProjectName:ResourceAllocationDetails:item_id>>. The Project Allocation Period is: Allocation Start Date: <<startDate:ResourceAllocationDetails:item_id>> End Date: <<endDate:ResourceAllocationDetails:item_id>> Hrs: <<totalEffort:ResourceAllocationDetails:item_id>>. Please <<click_link>> here to view further details of the allocation. Regards, <<RMS Team>> ** This is an autogenerated email. Kindly do not respond to this.**", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_WITHDRAWS_REJECTION" },
                    { 152L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "A", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_WITHDRAWS_REJECTION" },
                    { 153L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear User,<br/><br/>\r\n\r\n            Your assignment to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been cancelled. Your Allocation Rejection request had been approved by <<updated_by>>.<br/><br/>\r\n\r\n            Regards,<br/>\r\n            <<RMS Team>><br/><br/>\r\n\r\n            ** This is an autogenerated email. Kindly do not respond to this.**", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_REQUESTOR_APPROVED_REJECTION" },
                    { 154L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Your allocation to the project <<ProjectName:ResourceAllocationDetails:item_id>> has been cancelled. Allocation Rejection request has been approved by Resoruce Requestor <<updated_by>>.", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_REQUESTOR_APPROVED_REJECTION" },
                    { 155L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> Roll Forward Update", null, "Dear User,<br/><br/>\r\n\r\n            Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> dates have been rolled forward from <<pipelineoldstartdate>> to <<pipelinestartdate>>. The system has taken the following actions based on the new start date which are set out below:<br/><br/>\r\n\r\n            1. For allocated employees who are available on the revised dates, new allocation workflow and relevant approvals will be triggered.<br/>\r\n            2. For allocated employees who are not available on certain dates in the new project period, those allocations will be moved to DRAFT state to review and change as appropriate.<br/>\r\n            3. For allocated employees who are not available for the requested period, they will be released from the project.<br/><br/>\r\n\r\n            <a href=' << BaseUrl:config >> project - details /<< pipelinecode >>/<< jobcode >>? tab = 3'>Click here</a> for the details.<br/><br/>\r\n\r\n            Regards,< br />\r\n            << RMS Team >>< br />< br />\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.* *", "Requestor,Reviewer,AdditionalEL,AdditionalDelegate", "ROLL_OVER_ALLOCATED_EMPLOYEES_AVAILABLE_FOR_REVISED_DATES_ALLOCATION_SHIFTED_NEW_WF_TRIGGERED_NOTIFICATION_TO_REQUESTOR_AND_REVIEWER" },
                    { 156L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> Roll Forward Update", null, "Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> has been rolled forward to <<pipelinestartdate>>. Review Project details for change in allocations.", "Requestor,Reviewer,AdditionalEL,AdditionalDelegate", "ROLL_OVER_ALLOCATED_EMPLOYEES_AVAILABLE_FOR_REVISED_DATES_ALLOCATION_SHIFTED_NEW_WF_TRIGGERED_NOTIFICATION_TO_REQUESTOR_AND_REVIEWER" },
                    { 157L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear User,<br/><br/>\r\n            Your assignment to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been cancelled..<br/><br/>\r\n            Regards,<br/>\r\n            <<RMS Team>><br/><br/>\r\n            ** This is an autogenerated email. Kindly do not respond to this.**", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_REVIEWER_APPROVED_EMPLOYEE_REJECTION" },
                    { 158L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Your allocation to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been cancelled.", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_REVIEWER_APPROVED_EMPLOYEE_REJECTION" },
                    { 169L, "ResourceRequestor,Delegate", true, null, "Notification", "EMAIL", "Notification", "Project Marketplace Updates", null, "Dear User,\r\n            Below listed projects have been moved in the Marketplace.\r\n            <projectmovedtomarketplacetable>\r\n            Regards,\r\n            <RMS Team>\r\n            ** This is an autogenerated email. Kindly do not respond to this.**", "Reviewer", "PROJECT_MOVED_TO_MARKETPLACE_SUMMARY_EMAIL" },
                    { 170L, null, true, null, "Notification", "EMAIL", "Notification", "New Projects in the Marketplace", null, "Dear User,\r\n            New projects have been added to the Marketplace in the RMS. These projects offer exciting opportunities for you to contribute your skills and expertise. A summary of the new projects provided in the table below:\r\n            <<projectlistinginmarketplacenotificationtoemployee>>\r\n\r\n            Click here to view details in the Marketplace and submit your interest.\r\n            Regards,\r\n            <RMS Team>\r\n            ** This is an autogenerated email. Kindly do not respond to this.**", "employee", "CONSOLIDATED_MAIL_TO_EMPLOYEE_FOR_PROJECT_LISTING_IN_MARKETPLACE" },
                    { 171L, null, true, null, "Notification", "EMAIL", "Notification", "RMS Tasks pending for your action", null, "Dear User,\r\n            Following tasks are pending for your action:\r\n            <<allocationtablecontent>>\r\n            <<skilltablecontent>>\r\n            Click here for to review further details and approve/reject the request.\r\n            Regards,\r\n            RMS Team\r\n            ** This is an autogenerated email. Kindly do not respond to this.**", "employee", "RMS_ALLOCATION_AND_SKILL_TASKS_PENDING_FOR_ACTION_SUMMARY_MAIL" },
                    { 172L, null, true, null, "Notification", "EMAIL", "Notification", "RMS Tasks pending for your action", null, "Dear User,\r\n            Following tasks are pending for your action:\r\n            <<allocationtablecontent>>\r\n            <<skilltablecontent>>\r\n            Click here for to review further details and approve/reject the request.\r\n            Regards,\r\n            RMS Team\r\n            ** This is an autogenerated email. Kindly do not respond to this.**", "employee", "ADDITION_OF_NEW_PROJECT_NOTIFICATION_TO_RESOURCE_REQUESTOR" },
                    { 262L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear  User,<br/><br/>\r\n            You have been assigned to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> on date <<created_at>>. The Project Allocation Period is:\r\n            Allocation Start Date: <<startdate:ResourceAllocationDetails:item_id>> End Date: <<enddate:ResourceAllocationDetails:item_id>> Hrs: <<totaleffort:ResourceAllocationDetails:item_id>>.<br/>\r\n            Please <a href=' << BaseUrl:config >> myapproval'>Click here</a> to view further details of the allocation.<br/>\r\n            Please note, if you are unable to review the request for approval, it will be auto - approved by << due_date >>.< br />< br />\r\n            Regards,< br />\r\n            << RMS Team >>< br />< br />\r\n            **This is an autogenerated email.Kindly do not respond to this.* *", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_FOR_HIS_ALLOCATION_TASK_TO_PROJECT" },
                    { 263L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> Allocation Update", null, "Allocation updates for Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>>", "employee_name_release_resource", "NOTIFICATION_TO_EMPLOYEE_AS_RELEASED_FROM_PROJECT" },
                    { 264L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> Allocation Update", null, "Dear User,<br/><br/>\r\n            Your Allocation on the Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> has been released.<br/> \r\n            Please reach out to <<modifiedBy>> for any queries.<br/><br/>\r\n            Regards,<br/>\r\n            <<RMS Team>><br/><br/>\r\n            ** This is an autogenerated email. Kindly do not respond to this.**", "employee_name_release_resource", "NOTIFICATION_TO_EMPLOYEE_AS_RELEASED_FROM_PROJECT" },
                    { 265L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "You have been assigned to the Project <<ProjectName:ResourceAllocationDetails:item_id>> on date <<due_date>>. ", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_FOR_HIS_ALLOCATION_TASK_TO_PROJECT" },
                    { 266L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> Roll Forward Update", null, "Dear User,<br/><br/>\r\n            Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> dates have been rolled forward from <<pipelineoldstartdate>> to <<pipelinestartdate>>.<br/><br/> \r\n            The system has taken the following actions based on the new start date which are set out below:<br/><br/> \r\n            1. For allocated employees who are available on the revised dates,  new allocation workflow and relevant approvals will be  triggered.<br/>\r\n            2. For allocated employees who are not available on certain dates in the new project period, those allocations will be moved to DRAFT state to review and change as appropriate.<br/>\r\n            3. For allocated employees who are not available for the requested period,  they will be released from the project.<br/>\r\n            <a href=' << BaseUrl:config >> project - details /<< pipelinecode >>/<< jobcode >>? tab = 3'>Click here</a> for the details.<br/><br/>\r\n            Regards,< br />\r\n            << RMS Team >> < br />< br />\r\n            **This is an autogenerated email.Kindly do not respond to this.* *", "ResourceRequestor,Delegate,AdditionalEl,AdditionalDelegate", "ROLL_OVER_ALLOCATED_EMPLOYEES_AVAILABLE_FOR_REVISED_DATES_ALLOCATION_SHIFTED_NEW_WF_TRIGGERED_NOTIFICATION_TO_REQUESTOR_AND_REVIEWER" },
                    { 267L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> Roll Forward Update.", null, "Dear User,<br/><br/>\r\n            Allocation of Employees has  been updated on the   project : <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> as the  Project dates have been rolled forward from <<pipelineoldstartdate>> to <<pipelinestartdate>>.<br/>   \r\n            <a href=' << BaseUrl:config >> project - details /<< pipelinecode >>/<< jobcode >>? tab = 3'>Click here</a> for the details.<br/><br/> \r\n            Regards,< br />\r\n            << RMS Team >>< br />< br />\r\n            **This is an autogenerated email.Kindly do not respond to this.* *", "Reviewer", "NOTIFICATION_TO_REVIEWER_ALLOCATIONS_ARE_SHIFTED_AND_NEW_WORKFLOW_ARE_TRIGGERED" },
                    { 268L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> Roll Forward Update.", null, "Allocation Update - Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> rolled forward to <<pipelinestartdate>>", "Reviewer", "NOTIFICATION_TO_REVIEWER_ALLOCATIONS_ARE_SHIFTED_AND_NEW_WORKFLOW_ARE_TRIGGERED" },
                    { 269L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> Name  Marketplace  Summary", null, "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> has received <<employeeshowedinterestcount>> interests. ", "ResourceRequestor,Delegate", "NOTIFICATION_TO_RESOURCE_REQUESTOR_AND_DELEGATE_FOR_REMOVAL_OF_PROJECT_FROM_MP" },
                    { 270L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> Name  Marketplace  Summary", null, "Dear User,<br/><br/>\r\n            Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> has been removed from Marketplace & has received <<employeeshowedinterestcount>> interests.<br/><br/>\r\n            <a href=' << BaseUrl:config >> project - details /<< pipelinecode >>/<< jobcode >>? tab = 5'>Click here</a> for the details.<br/><br/>\r\n            Regards,< br />\r\n            << RMS Team >>< br />< br />\r\n            **This is an autogenerated email.Kindly do not respond to this.* *", "ResourceRequestor,Delegate", "NOTIFICATION_TO_RESOURCE_REQUESTOR_AND_DELEGATE_FOR_REMOVAL_OF_PROJECT_FROM_MP" },
                    { 271L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> Roll Forward Update - Allocation Release", null, "Dear User,<br/><br/>\r\n            Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> dates have been rolled forward from <<pipelineoldstartdate>> to <<pipelinestartdate>>.   Since you are  not available on the revised project dates, your allocation on the project has been released.<br/><br/>\r\n            Please speak to <<ProjectResourceRequestor:GetProjectResourceRequestor:pipelineCode|jobCode>> for concerns on the allocations.<br/><br/>\r\n            Regards,<br/>\r\n            <<RMS Team>><br/><br/>\r\n            ** This is an autogenerated email. Kindly do not respond to this.**", "employee_name_roll_over_draft", "ROLL_OVER_ALLOCATION_IN_DRAFT_DUE_TO_UNAVAILABLITY" },
                    { 272L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> Roll Forward Update - Allocation Release", null, "Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> has been rolled forward to <<pipelinestartdate>>.  Your allocation has been released. ", "employee_name_roll_over_draft", "ROLL_OVER_ALLOCATION_IN_DRAFT_DUE_TO_UNAVAILABLITY" },
                    { 273L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> Roll Forward Update - Allocation Release", null, "Dear User,<br/><br/>\r\n            Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> dates have been rolled forward from <<pipelineoldstartdate>> to <<pipelinestartdate>>.   Since you are  not available on the revised project dates, your allocation on the project has been released.<br/><br/>\r\n            Please speak to <<ProjectResourceRequestor:GetProjectResourceRequestor:pipelineCode|jobCode>> for concerns on the allocations.<br/><br/>\r\n            Regards,<br/>\r\n            <<RMS Team>><br/><br/>\r\n            ** This is an autogenerated email. Kindly do not respond to this.**", "employee_name_roll_over_terminated", "ROLL_OVER_ALLOCATION_TERMINATED_DUE_TO_UNAVAILABLITY" },
                    { 274L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> Roll Forward Update - Allocation Release", null, "Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> has been rolled forward to <<pipelinestartdate>>.  ", "employee_name_roll_over_terminated", "ROLL_OVER_ALLOCATION_TERMINATED_DUE_TO_UNAVAILABLITY" },
                    { 275L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear User,<br/><br/>\r\n            Resource allocation request has been rejected by reviewer: <<updated_by:GetUserInfo:updated_by>> for  employee: <<empEmail:ResourceAllocationDetails:item_id>> in the project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/> \r\n            Rejection reason: <<ReasonForRejectionProvidedByReviewer>><br/>\r\n            Please do new allocation.<br/>\r\n            <a href=' << BaseUrl:config >> project - details /<< pipelinecode >>/<< jobcode >>? tab = 4'>Click here</a> for the details.<br/><br/>\r\n            Regards,< br />\r\n            << RMS Team >>< br />< br />\r\n            **This is an autogenerated email.Kindly do not respond to this.* *", "resource_requestor_allocation_wf", "EMPLOYEE_ALLOCATION_REJECTED_BY_REVIEWER_NOTIFICATION_TO_RESOURCE_REQUESTOR" },
                    { 276L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear User,<br/><br/>\r\n            Allocation requests rejected by employee <<empEmail:ResourceAllocationDetails:item_id>> for Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been cancelled by Reviewer <<updated_by>>.<br/> \r\n            Please do new allocations.<br/>\r\n            Please <<click_link>> here for the details.<br/><br/>\r\n            Regards,<br/>\r\n            <<RMS Team>><br/><br/>\r\n            ** This is an autogenerated email. Kindly do not respond to this.**", "resource_requestor_allocation_wf", "REVIEWER_ACCEPTED_EMPLOYEE_REJECTION_RESPONSE" },
                    { 277L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear User,<br/><br/>\r\n            Allocation requests rejected by employee <<empEmail:ResourceAllocationDetails:item_id>> for Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been cancelled by Reviewer <<updated_by>>.<br/>\r\n            Please do new allocations.<br/>\r\n            Please <a href=' << BaseUrl:config >> project - details /<< pipelinecode >>/<< jobcode >>? tab = 3'>Click here</a> for the details.<br/><br/>\r\n            Regards,< br />\r\n            << RMS Team >>< br />< br />\r\n            **This is an autogenerated email.Kindly do not respond to this.* *", "resource_requestor_allocation_wf", "REVIEWER_ACCEPTED_EMPLOYEE_REJECTION_RESPONSE" },
                    { 278L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear User,<br/><br/>\r\n            Your  assignment on the Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been updated on date <<created_at>>.<br/>\r\n            Please <<click_link>> here for the details.<br/><br/>\r\n            Regards,<br/>\r\n            <<RMS Team>><br/><br/>\r\n            ** This is an autogenerated email. Kindly do not respond to this.**", "employee_name_allocation_wf", "NOTIFICATION_FOR_ALLOCATION_UPDATE_TO_EMPLOYEE" },
                    { 279L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear User,<br/><br/>\r\n            Your  assignment on the Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been updated on date <<created_at>>.<br/>\r\n            Please <a href=' << BaseUrl:config >> project - details /<< pipelinecode >>/<< jobcode >>? tab = 3'>Click here</a> for the details.<br/><br/>\r\n            Regards,< br />\r\n            << RMS Team >>< br />< br />\r\n            **This is an autogenerated email.Kindly do not respond to this.* *", "employee_name_allocation_wf", "NOTIFICATION_FOR_ALLOCATION_UPDATE_TO_EMPLOYEE" },
                    { 280L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear User,<br/><br/>\r\n            Resource allocation request has been rejected by Employee: <<empEmail:ResourceAllocationDetails:item_id>> for Project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/>\r\n            You can terminate the workflow to make new allocations provided the allocated employee does not withdraw their rejection.<br/>\r\n            Rejection reason: <<ReasonForRejectionProvidedByEmployee>><br/>\r\n            Please <a href=' << BaseUrl:config >> project - details /<< pipelinecode >>/<< jobcode >>? tab = 4'>Click here</a> for the details.<br/><br/>\r\n            Regards,< br />\r\n            << RMS Team >>< br />< br />\r\n            **This is an autogenerated email.Kindly do not respond to this.* *", "resource_requestor_allocation_wf,Reviewer", "NOTIFICATION_TO_RESOURCE_REQUESTOR_AND_REVIEWER_ON_EMPLOYEE_REJECTION" },
                    { 281L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Resource allocation requests have been rejected for Project: <<ProjectName:ResourceAllocationDetails:item_id>> by reviewer <<updated_by>>.  Please do new allocations", "resource_requestor_allocation_wf", "EMPLOYEE_ALLOCATION_REJECTED_BY_REVIEWER_NOTIFICATION_TO_RESOURCE_REQUESTOR" },
                    { 282L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear User,<br/><br/>\r\n            Resource allocation request has been rejected by employee <<empEmail:ResourceAllocationDetails:item_id>> for Project: <<ProjectName:ResourceAllocationDetails:item_id>><br/>\r\n            Rejection reason: <<ReasonForRejectionProvidedByEmployee>><br/>\r\n            <a href=' << BaseUrl:config >> project - details /<< pipelinecode >>/<< jobcode >>? tab = 3'>Click here</a> to view details and review employee action.<br/><br/>\r\n            Regards,< br />\r\n            << RMS Team >>< br />< br />\r\n            **This is an autogenerated email.Kindly do not respond to this.* *", "resource_requestor_allocation_wf", "NOTIFICATION_TO_RESOURCE_REQUESTOR_AND_REVIEWER_ON_EMPLOYEE_REJECTION_REQUESTOR_CONFIG_IS_ON" },
                    { 283L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "You have been successfully  allocated  to the project <<ProjectName:ResourceAllocationDetails:item_id>>.", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_AFTER_REVIEWER_ACCEPTS" },
                    { 284L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Resource allocation requests have been rejected for Project: <<ProjectName:ResourceAllocationDetails:item_id>> by employee <<empEmail:ResourceAllocationDetails:item_id>>.  Please review employee action", "resource_requestor_allocation_wf", "NOTIFICATION_TO_RESOURCE_REQUESTOR_AND_REVIEWER_ON_EMPLOYEE_REJECTION_REQUESTOR_CONFIG_IS_ON" },
                    { 285L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear  User,<br/><br/>\r\n            You have been assigned to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> . The Project Allocation Period is:<br/>\r\n            Allocation Start Date: <<startDate:ResourceAllocationDetails:item_id>> End Date: <<endDate:ResourceAllocationDetails:item_id>> Hrs: <<totalEffort:ResourceAllocationDetails:item_id>>.\r\n            Please <a href=' << BaseUrl:config >> myapproval'>Click here</a> here to view further details of the allocation.<br/><br/>\r\n            Regards,< br />\r\n            << RMS Team >>< br />< br />\r\n            **This is an autogenerated email.Kindly do not respond to this.* *", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_AFTER_REVIEWER_ACCEPTS" },
                    { 286L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear User,<br/><br/>\r\n            You have been auto-allocated to the Project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/>\r\n            Allocation Start Date: <<startDate:ResourceAllocationDetails:item_id>> End Date: <<endDate:ResourceAllocationDetails:item_id>> Hrs: <<totalEffort:ResourceAllocationDetails:item_id>>.<br/>\r\n            <a href=' << BaseUrl:config >> project - details /<< pipelinecode >>/<< jobcode >>? tab = 3'>Click here</a> to view allocation details.<br/><br/>\r\n            Regards,< br />\r\n            << RMS Team >>< br />< br />\r\n            **This is an autogenerated email.Kindly do not respond to this.* *", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_AUTO_APPROVED_AFTER_EMPLOYEE_DUE_DATE_CROSS" },
                    { 287L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "A", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_AUTO_APPROVED_AFTER_EMPLOYEE_DUE_DATE_CROSS" },
                    { 288L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "A", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_WITHDRAWS_REJECTION" },
                    { 289L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear  User,<br/><br/>\r\n            You have been assigned to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> . The Project Allocation Period is:<br/>\r\n            Allocation Start Date: <<startDate:ResourceAllocationDetails:item_id>> End Date: <<endDate:ResourceAllocationDetails:item_id>> Hrs: <<totalEffort:ResourceAllocationDetails:item_id>>.<br/>\r\n            Please <<click_link>> here to view further details of the allocation.<br/><br/>\r\n            Regards,<br/>\r\n            <<RMS Team>><br/><br/>\r\n            ** This is an autogenerated email. Kindly do not respond to this.**", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_WITHDRAWS_REJECTION" },
                    { 290L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear User,<br/><br/>\r\n            Your assignment to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been cancelled. Your Allocation Rejection request had been approved by <<updated_by>>.<br/><br/>\r\n            Regards,<br/>\r\n            <<RMS Team>><br/><br/>\r\n            ** This is an autogenerated email. Kindly do not respond to this.**", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_REQUESTOR_APPROVED_REJECTION" },
                    { 291L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Your allocation to the project <<ProjectName:ResourceAllocationDetails:item_id>> has been cancelled. Allocation Rejection request has been approved by Resoruce Requestor <<updated_by>>.", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_REQUESTOR_APPROVED_REJECTION" },
                    { 292L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Resource allocation requests have been rejected for Project: <<ProjectName:ResourceAllocationDetails:item_id>> by employee <<empEmail:ResourceAllocationDetails:item_id>>.  Please make new allocations.", "resource_requestor_allocation_wf,Reviewer", "NOTIFICATION_TO_RESOURCE_REQUESTOR_AND_REVIEWER_ON_EMPLOYEE_REJECTION" },
                    { 293L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear User,<br/><br/>\r\n            Your assignment to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been cancelled..<br/><br/>\r\n            Regards,<br/>\r\n            <<RMS Team>><br/><br/>\r\n            ** This is an autogenerated email. Kindly do not respond to this.**", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_REVIEWER_APPROVED_EMPLOYEE_REJECTION" },
                    { 294L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> Roll Forward Update", null, "Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> has been rolled forward to <<pipelinestartdate>>.  Review Project details for change in allocations. ", "ResourceRequestor,Delegate,AdditionalEl,AdditionalDelegate", "ROLL_OVER_ALLOCATED_EMPLOYEES_AVAILABLE_FOR_REVISED_DATES_ALLOCATION_SHIFTED_NEW_WF_TRIGGERED_NOTIFICATION_TO_REQUESTOR_AND_REVIEWER" },
                    { 295L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Your allocation to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been cancelled.", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_REVIEWER_APPROVED_EMPLOYEE_REJECTION" },
                    { 296L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> Allocation Update", null, "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> allocations have been moved to new project code", "ResourceRequestor,Reviewer,Delegate,AdditionalEl,AdditionalDelegate", "JOB_CODE_UPDATE_TO_NEW_CODE" },
                    { 297L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> Allocation Update", null, "Dear User,\r\n            <br/>\r\n            <br/>\r\n            Allocations on the Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> have been moved from Project Code <<jobcode>> to  new Project Code <<newjobcode>> .<br/>\r\n            <a href=' << BaseUrl:config >> project - details /<< newPipelineCode >>/<< newJobCode >>? tab = 0'>Click here<a/> for the details.\r\n            < br />\r\n            < br />\r\n\r\n            Regards,\r\n            < br />\r\n            RMS Team\r\n            < br />\r\n            < br />\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.* *", "ResourceRequestor,Reviewer,Delegate,AdditionalEl,AdditionalDelegate", "JOB_CODE_UPDATE_TO_NEW_CODE" },
                    { 298L, null, true, null, "Notification", "PUSH", "Notification", "Additional Delegate assigned to Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>", null, "You have been assigned as Additional Delegate for <<User Requesting>> for Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>.", "employee_name_additional_delegate", "ASSIGNMENT_OF_ADDITIONAL_DELEGATE_BY_ADDITIONAL_EL" },
                    { 299L, null, true, null, "Notification", "EMAIL", "Notification", "Additional Delegate assigned to Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>", null, "Dear User,<br/><br/>\r\n            <<User requesting>> has assigned you as Additional Delegate to the  Additional EL for  Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> on date <<DD-MM-YY>> <br/><br/>\r\n            <a href=' << BaseUrl:config >> project - details /<< pipelinecode >>/<< jobcode >>? tab = 0'>Click here</a> for the details. You may contact <<User Requesting>> to discuss your responsibilities on the project in RMS.<br/><br/> \r\n            Regards,< br />\r\n            << RMS Team >>< br />< br />\r\n            **This is an autogenerated email.Kindly do not respond to this.* *", "employee_name_additional_delegate", "ASSIGNMENT_OF_ADDITIONAL_DELEGATE_BY_ADDITIONAL_EL" },
                    { 300L, null, true, null, "Notification", "PUSH", "Notification", "RMS Admin Role assigned", null, "You have been assigned Admin role. Please check your email for details.", "employee_name_assign_as_admin", "ADMIN_ASSIGNED_BY_SYSTEM_ADMIN" },
                    { 301L, null, true, null, "Notification", "EMAIL", "Notification", "RMS Admin Role assigned", null, "Dear User,<br/><br/>\r\n            You have been assigned the role of Admin  in the RMS application.<br/><br/>\r\n            <a href=' << BaseUrl:config >> roles - permission'>Click here</a> to view details in the User Management section.<br/><br/> \r\n            Regards,< br />\r\n            << RMS Team >>< br />< br />\r\n            **This is an autogenerated email.Kindly do not respond to this.* *", "employee_name_assign_as_admin", "ADMIN_ASSIGNED_BY_SYSTEM_ADMIN" },
                    { 302L, null, true, null, "Notification", "EMAIL", "Notification", "Project:<<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> - <<pipelineStatus :GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>", null, "Dear User,<br/><br/> \r\n            Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. has been <<pipelineStatus :GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> on <<SuspendedAt:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. Your allocation has been auto-released from the project. <br/><br/> \r\n            Regards,<br/>\r\n            <<RMS Team>><br/><br/> \r\n            ** This is an autogenerated email. Kindly do not respond to this.**", "employee_name_allocation", "PROJECT_SUSPENSION_ALLOCATION_RELEASE_NOTIFICATION" },
                    { 303L, null, true, null, "Notification", "EMAIL", "Notification", "Project:<<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> - Suspended", null, "Dear User, <br/><br/> \r\n            cc: Delegate/ Add EL/ Add Delegate/ Reviewer Pipeline: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. has been <<pipelineStatus :GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> on <<:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. Any allocated resources have been auto-released. <br/><br/> \r\n            <a href=' << BaseUrl:config >> project - details /<< pipelinecode >>/<< jobcode >>? tab = 0'>Click here</a> for the details. <br/><br/>\r\n                Regards, < br />\r\n                << RMS Team >> < br />< br />\r\n            **This is an autogenerated email.Kindly do not respond to this.* *", "Requestor,Reviewer,AdditionalEL,AdditionalDelegate", "PROJECT_SUSPENSION_NOTIFICATION" },
                    { 304L, null, true, null, "Notification", "PUSH", "Notification", "Project:<<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> - Suspended", null, "Pipeline: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. has been <<pipelineStatus :GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> on <<:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. Any allocated resources have been auto-released.", "Requestor,Reviewer,AdditionalEL,AdditionalDelegate", "PROJECT_SUSPENSION_NOTIFICATION" },
                    { 305L, null, true, null, "Notification", "PUSH", "Notification", "Project:<<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> - <<pipelineStatus :GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>", null, "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. has been <<pipelineStatus :GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> on <<SuspendedAt:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. Your allocation has been auto-released from the project.", "employee_name_allocation", "PROJECT_SUSPENSION_ALLOCATION_RELEASE_NOTIFICATION" },
                    { 306L, null, true, null, "Notification", "EMAIL", "Notification", "Allocation conflicts for <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>", null, "Dear User,<br/><br/>\r\n\r\n            Employee: <<Employee Name>> is on leave for the below mentioned dates which conflicts with allocations on the Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>.<br/><br/>\r\n\r\n            Leave Dates : <<LeaveDates:EmployeeLeaves:empEmail>><br/><br/>\r\n\r\n            <a href=' << BaseUrl:config >> project - details /<< pipelinecode >>/<< jobcode >>? tab = 3'>Click here</a> to review allocation detail and kindly update the allocations.<br/><br/>\r\n\r\n            Regards,< br />\r\n            << RMS Team >>< br />< br />\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.* *", "Requestor,Reviewer,AdditionalEL,AdditionalDelegate", "EMPLOYEE_LEAVE_NOTIFCATION" },
                    { 307L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> Budget Updates", null, "Dear User,<br/><br/>\r\n\r\n            Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> has consumed <<Limit:GETPROJECTBUDGET:pipelineCode|jobCode>> % of the budget in allocations.<br/><br/>\r\n\r\n            <a href=' << BaseUrl:config >> project - details /<< pipelinecode >>/<< jobcode >>? tab = 2'>Click here</a> for the details. Request you to review the future budget requirements and seek additional budget approval in WCGT if required.<br/><br/>\r\n\r\n            Regards,< br />\r\n            << RMS Team >>< br />< br />\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.* *", "Requestor,Reviewer", "PROJECT_BUDGET_NOTIFICATION" },
                    { 308L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> Budget Updates", null, "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> has consumed <<ProjectBudget:GETPROJECTBUDGET:pipelineCode|jobCode>> % of the budget in allocations.", "Requestor,Reviewer", "PROJECT_BUDGET_NOTIFICATION" },
                    { 309L, null, true, null, "Notification", "PUSH", "Notification", "Allocation conflicts for <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>", null, "Employee <<empEmail:ResourceAllocationDetails:item_id>> is not available on the allocated dates for the project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>.\r\n\r\n            Kindly update the allocations accordingly.\r\n\r\n            Click here for the details.\r\n            ", "Requestor,Reviewer,AdditionalEL,AdditionalDelegate", "EMPLOYEE_LEAVE_NOTIFCATION" },
                    { 310L, null, true, null, "Notification", "EMAIL", "Notification", "Allocation conflicts for <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>", null, "Dear User,<br/><br/>\r\n\r\n            Allocation conflict for Employee: <<empEmail:ResourceAllocationDetails:item_id>> as the employee is not available.<br/><br/>\r\n\r\n            Kindly update the allocations accordingly.<br/><br/>\r\n\r\n            <a href=' << BaseUrl:config >> project - details /<< pipelinecode >>/<< jobcode >>? tab = 3'>Click here</a> for the details.<br/><br/>\r\n\r\n            Regards,< br />\r\n            << RMS Team >>< br />< br />\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.* *", "Requestor,Reviewer,AdditionalEL,AdditionalDelegate", "ALLOCATION_CONFLICT_NOTIFICATION" },
                    { 311L, null, true, null, "Notification", "EMAIL", "Notification", "Skill Assessment Review Updates", null, "Dear User,<br/><br/>\r\n\r\n            Your <<SkillName:UserSkill:item_id>> assessment <<Status:UserSkill:item_id>> <<Approver:UserSkill:item_id>><br/><br/>\r\n\r\n            <a href=' << BaseUrl:config >> myskill'>Click here</a> for the details.<br/><br/>\r\n\r\n            Regards,< br />\r\n            << RMS Team >>< br />< br />\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.* *", "<<Email:UserSkill:item_id>>", "SUPERCOACH_ACCEPTED_SKILL_ASSESSMENT_REQUEST" },
                    { 312L, null, true, null, "Notification", "PUSH", "Notification", "Skill Assessment Review Updates", null, "Your skill Your <<SkillName:UserSkill:item_id>> assessment <<Status:UserSkill:item_id>> <<Approver:UserSkill:item_id>> \r\n\r\n\r\n            Click here for the details.\r\n            ", "<<Email:UserSkill:item_id>>", "SUPERCOACH_ACCEPTED_SKILL_ASSESSMENT_REQUEST" },
                    { 313L, null, true, null, "Notification", "EMAIL", "Notification", "Allocation conflicts for <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>", null, "Dear User,<br/><br/>\r\n\r\n            Allocation conflicts in the project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> as Employee: <<empEmail:ResourceAllocationDetails:item_id>> is not available.<br/><br/>\r\n\r\n            <a href=' << BaseUrl:config >> project - details /<< pipelinecode >>/<< jobcode >>? tab = 3'>Click here</a> to review allocation detail and kindly update the allocations.<br/><br/>\r\n\r\n            Regards,< br />\r\n            << RMS Team >>< br />< br />\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.* *", "Requestor,Reviewer,AdditionalEL,AdditionalDelegate", "EMPLOYEE_ABSCONDING_NOTIFCATION" },
                    { 314L, null, true, null, "Notification", "PUSH", "Notification", "Allocation conflicts for <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>", null, "Employee <<empEmail:ResourceAllocationDetails:item_id>> is not available on the allocated dates for the project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>.\r\n\r\n            Kindly update the allocations accordingly.\r\n\r\n            Click here for the details.\r\n            ", "Requestor,Reviewer,AdditionalEL,AdditionalDelegate", "EMPLOYEE_ABSCONDING_NOTIFCATION" },
                    { 315L, null, true, null, "Notification", "PUSH", "Notification", "Allocation conflicts for <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>", null, "Employee <<empEmail:ResourceAllocationDetails:item_id>> is not available on the allocated dates for the project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>.\r\n\r\n            Kindly update the allocations accordingly.\r\n\r\n            Click here for the details.\r\n            ", "Requestor,Reviewer,AdditionalEL,AdditionalDelegate", "ALLOCATION_CONFLICT_NOTIFICATION" },
                    { 316L, null, true, null, "Notification", "EMAIL", "Notification", "Project  Updates", null, "Dear User,\r\n            <br />\r\n            The following activities have been performed on the below mentioned Job / Pipeline (s): \r\n\r\n            <<RequistionSummary:Allocation:PipelineCode|JobCode>>\r\n\r\n            <<RequstionSummary:Requistion:PipelineCode|JobCode>>\r\n\r\n            <<AllocationSummary:AllocationPublished:PipelineCode|JobCode>>\r\n\r\n            <<MarketPlaceSummary:MarketPlace:PipelineCode|JobCode>>\r\n\r\n            <br/> \r\n            Click\r\n            here\r\n            to view the details of project(s). \r\n            <br/>\r\n\r\n\r\n            Regards, <br />\r\n            <<RMS Team>>\r\n            <br />\r\n            ** This is an autogenerated email. Kindly do not respond to this.**", "ResourceRequestor,Reviewer,AdditionalEl,AdditionalDelegate", "ALLOCATION_SUMMARY_NOTIFICATION" }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 42L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 43L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 137L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 138L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 139L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 140L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 141L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 142L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 143L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 144L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 145L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 146L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 147L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 148L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 149L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 150L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 151L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 152L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 153L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 154L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 155L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 156L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 157L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 158L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 169L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 170L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 171L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 172L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 262L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 263L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 264L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 265L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 266L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 267L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 268L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 269L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 270L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 271L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 272L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 273L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 274L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 275L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 276L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 277L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 278L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 279L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 280L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 281L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 282L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 283L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 284L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 285L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 286L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 287L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 288L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 289L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 290L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 291L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 292L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 293L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 294L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 295L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 296L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 297L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 298L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 299L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 300L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 301L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 302L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 303L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 304L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 305L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 306L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 307L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 308L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 309L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 310L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 311L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 312L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 313L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 314L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 315L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 316L);
        }
    }
}
