using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace RMT.Notification.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class suspendnotificationdate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 302L,
                column: "template",
                value: "Dear User,<br/><br/> \r\nProject: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. has been <<pipelineStatus:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> on <<SuspendedAt:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. Your allocation has been auto-released from the project. <br/><br/> \r\nRegards,<br/>RMS Team<br/><br/>** This is an autogenerated email. Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 303L,
                column: "template",
                value: "Dear User, <br/><br/> \r\n<<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. has been <<pipelineStatus:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> on <<suspendedmodifyat:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. Any allocated resources have been auto-released. <br/><br/> \r\nPlease <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=0'>click here</a> for the details. <br/><br/>\r\nRegards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 304L,
                column: "template",
                value: "Pipeline: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. has been <<pipelineStatus:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> on <<suspendedmodifyat:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. Any allocated resources have been auto-released.");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 302L,
                column: "template",
                value: "Dear User,<br/><br/> \r\nProject: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. has been <<pipelineStatus :GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> on <<SuspendedAt:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. Your allocation has been auto-released from the project. <br/><br/> \r\nRegards,<br/>RMS Team<br/><br/>** This is an autogenerated email. Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 303L,
                column: "template",
                value: "Dear User, <br/><br/> \r\n<<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. has been <<pipelineStatus:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> on <<:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. Any allocated resources have been auto-released. <br/><br/> \r\nPlease <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=0'>click here</a> for the details. <br/><br/>\r\nRegards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 304L,
                column: "template",
                value: "Pipeline: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. has been <<pipelineStatus:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> on <<:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>>. Any allocated resources have been auto-released.");
        }
    }
}
