using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace RMT.Notification.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class seedupdate2206 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 293L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 295L);

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 154L,
                column: "template",
                value: "\r\n                Your allocation to the project <<ProjectName:ResourceAllocationDetails:item_id>> has been cancelled. Allocation Rejection request has been approved by Resoruce Requestor <<updated_by>>.");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 157L,
                column: "template",
                value: "Dear User,<br/><br/>\r\nYour assignment to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been cancelled. Your request for non acceptance of the allocation has been approved by Reviewer <<updated_by>>.<br/><br/>\r\nRegards,<br/>RMS Team<br/><br/>** This is an autogenerated email. Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 158L,
                column: "template",
                value: "Your allocation to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been cancelled.\r\n                Allocation Rejection request has been approved by Reviewer <<updated_by>> ");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 277L,
                column: "template",
                value: "Dear User,<br/><br/>\r\nThe Allocation request rejected by employee <<empEmail:ResourceAllocationDetails:item_id>> for Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been approved by Reviewer <<updated_by>>.\r\nRequest you to please allocate another resource.<br/><br/>\r\nPlease <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=3'>click here</a> for the details.<br/><br/>\r\nRegards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 154L,
                column: "template",
                value: "\r\n                Your allocation to the project << ProjectName:ResourceAllocationDetails:item_id >> has been cancelled. Allocation Rejection request has been approved by Resoruce Requestor << updated_by >>.");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 157L,
                column: "template",
                value: "Dear User,<br/><br/>\r\nYour assignment to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been cancelled.<br/><br/>\r\nRegards,<br/>RMS Team<br/><br/>** This is an autogenerated email. Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 158L,
                column: "template",
                value: "Your allocation to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been cancelled.");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 277L,
                column: "template",
                value: "Dear User,<br/><br/>\r\nThe Allocation request rejected by employee <<empEmail:ResourceAllocationDetails:item_id>> for Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been approved by Reviewer <<updated_by>>.<br/>\r\nPlease do new allocations.<br/><br/>\r\nPlease <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=3'>click here</a> for the details.<br/><br/>\r\nRegards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.InsertData(
                table: "NotificationTemplates",
                columns: new[] { "Id", "cc", "is_active", "link_id", "module", "notification_type", "sub_module", "subject", "subscription_role", "template", "to", "type" },
                values: new object[,]
                {
                    { 293L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear User,<br/><br/>\r\nYour assignment to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been cancelled.<br/><br/>\r\nRegards,<br/>RMS Team<br/><br/>** This is an autogenerated email. Kindly do not respond to this.**", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_REVIEWER_APPROVED_EMPLOYEE_REJECTION" },
                    { 295L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Your allocation to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been cancelled.", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_REVIEWER_APPROVED_EMPLOYEE_REJECTION" }
                });
        }
    }
}
