using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace RMT.Notification.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class seederupdate1006 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 323L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 324L);

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 143L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n\r\n            Resource allocation request has been rejected by Employee: <<empEmail:ResourceAllocationDetails:item_id>> for Project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/>\r\n            You can terminate the workflow by <<due_date>> to make new allocations provided the allocated employee does not withdraw their rejection.<br/>\r\n            Rejection reason: <<ReasonForRejectionProvidedByEmployee>><br/><br/>\r\n\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=4'>click here</a> for the details.<br/><br/>\r\n\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 280L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n            Resource allocation request has been rejected by Employee: <<empEmail:ResourceAllocationDetails:item_id>> for Project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/>\r\n            You can terminate the workflow by <<due_date>> to make new allocations provided the allocated employee does not withdraw their rejection.<br/>\r\n            Rejection reason: <<ReasonForRejectionProvidedByEmployee>><br/><br/>\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=4'>click here</a> for the details.<br/><br/>\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 311L,
                columns: new[] { "template", "to" },
                values: new object[] { "Dear User,<br/><br/>\r\n            Your skill self-assessment request for the following skill has been approved by your Supercoach <<Approver:UserSkill:item_id>>. <br/><br/>\r\n\r\n            Skill Name : <<SkillName:UserSkill:item_id><br/>\r\n            Skill Proficiency Level : <<Proficiency:UserSkill:item_id>><br/><br/>\r\n\r\n            Please <a href='<<BaseUrl:config>>myskill'>click here</a> for the details.<br/><br/>\r\n\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.**", "<<Email:UserSkill:item_id>>" });

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 312L,
                columns: new[] { "template", "to" },
                values: new object[] { "Your skill Your <<SkillName:UserSkill:item_id>> assessment <<Status:UserSkill:item_id>> <<Approver:UserSkill:item_id>> ", "<<Email:UserSkill:item_id>>" });

            migrationBuilder.InsertData(
                table: "NotificationTemplates",
                columns: new[] { "Id", "cc", "is_active", "link_id", "module", "notification_type", "sub_module", "subject", "subscription_role", "template", "to", "type" },
                values: new object[,]
                {
                    { 400L, "", true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> Allocations Update.", null, "Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> end date has been updated. New End Date is <<enddate>>. Please take necessary actions.", "ResourceRequestor,Reviewer,AdditionalEl,AdditionalDelegate,Delegate", "PROJECT_END_DATE_UPDATE_NOTIFICATION" },
                    { 401L, "", true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> end date update.", null, "Dear User,<br/><br/>\r\n                Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> End Date has been updated.New End Date is <<enddate>>.<br/>Please review allocations made to the project and take any necessary actions.\r\n                <br/><br/>\r\n                Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=0'>click here</a> for the details.\r\n                <br/><br/>\r\n                Regards,<br/>\r\n               RMS Team\r\n                <br/><br/>\r\n            **This is an autogenerated email.Kindly do not respond to this.* *", "ResourceRequestor,Reviewer,AdditionalEl,AdditionalDelegate,Delegate", "PROJECT_END_DATE_UPDATE_NOTIFICATION" }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 400L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 401L);

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 143L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n\r\n            Resource allocation request has been rejected by Employee: <<empEmail:ResourceAllocationDetails:item_id>> for Project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/>\r\n            You can terminate the workflow to make new allocations provided the allocated employee does not withdraw their rejection.<br/>\r\n            Rejection reason: <<ReasonForRejectionProvidedByEmployee>><br/><br/>\r\n\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=4'>click here</a> for the details.<br/><br/>\r\n\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 280L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n            Resource allocation request has been rejected by Employee: <<empEmail:ResourceAllocationDetails:item_id>> for Project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/>\r\n            You can terminate the workflow to make new allocations provided the allocated employee does not withdraw their rejection.<br/>\r\n            Rejection reason: <<ReasonForRejectionProvidedByEmployee>><br/><br/>\r\n            Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode>>/<<jobcode>>?tab=4'>click here</a> for the details.<br/><br/>\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 311L,
                columns: new[] { "template", "to" },
                values: new object[] { "Dear User,<br/><br/>\r\n            Your skill self-assessment request for the following skill has been approved by your Supercoach  \r\n 	        <<createdby:UserSkill:item_id>>. <br/><br/>\r\n\r\n            Skill Name : <<skillname:UserSkill:item_id>><br/>\r\n            Skill Proficiency Level : <<Proficiency:UserSkill:item_id>><br/><br/>\r\n\r\n            Please <a href='<<BaseUrl:config>>myskill'>click here</a> for the details.<br/><br/>\r\n\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.**", "userskillemail" });

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 312L,
                columns: new[] { "template", "to" },
                values: new object[] { "Your skill  <<skillname:UserSkill:item_id>> assessment  has been approved by your Supercoach  <<createdby:UserSkill:item_id>> ", "userskillemail" });

            migrationBuilder.InsertData(
                table: "NotificationTemplates",
                columns: new[] { "Id", "cc", "is_active", "link_id", "module", "notification_type", "sub_module", "subject", "subscription_role", "template", "to", "type" },
                values: new object[,]
                {
                    { 323L, null, true, null, "Notification", "PUSH", "Notification", "Skill Assessment Review Updates", null, "Your skill  <<skillname:UserSkill:item_id>> assessment  has been declined by your Supercoach  <<createdby:UserSkill:item_id>> ", "userskillemail", "SUPERCOACH_REJECTED_SKILL_ASSESSMENT_REQUEST" },
                    { 324L, null, true, null, "Notification", "EMAIL", "Notification", "Skill Assessment Review Updates", null, "Dear User, <br/><br/> \r\n\r\n                    Your skill assessment approval has been declined by your Supercoach   <<createdby:UserSkill:item_id>>. <br/><br/> \r\n\r\n                    Skill Name : <<skillname:UserSkill:item_id>><br/>\r\n                    Skill Proficiency Level : <<Proficiency:UserSkill:item_id>><br/>\r\n                    Reason : <br/><br/>\r\n\r\n                    Please <a href='<<BaseUrl:config>>myskill'>click here</a> for the details and reach out to your Supercoach for any further clarifications.<br/><br/> \r\n\r\n                    Regards, \r\n                    RMS Team \r\n                    ** This is an autogenerated email. Kindly do not respond to this.** ", "userskillemail", "SUPERCOACH_REJECTED_SKILL_ASSESSMENT_REQUEST" }
                });
        }
    }
}
