using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace RMT.Notification.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class updatedmigration1206 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 262L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 265L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 288L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 289L);

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 42L,
                column: "template",
                value: "You have been assigned to the Project <<ProjectName:ResourceAllocationDetails:item_id>> on date <<created_at>>.");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 43L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n\r\n            You have been assigned to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> on date <<created_at>>.<br/>\r\n            The Project Allocation Period is:<br/>\r\n            Start Date: <<startdate:ResourceAllocationDetails:item_id>><br/> End Date: <<enddate:ResourceAllocationDetails:item_id>><br/> Hours: <<totaleffort:ResourceAllocationDetails:item_id>>.<br/><br/>\r\n\r\n            Please <a href='<<BaseUrl:config>>myapproval'>click here</a> to view further details of the allocation and provide your agreement to the allocation.<br/><br/>\r\n\r\n            Please note, if you are unable to review the request for approval, it will be auto - approved by <<due_date>>.<br/><br/>\r\n\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 311L,
                columns: new[] { "template", "to" },
                values: new object[] { "Dear User,<br/><br/>\r\n                Your skill self-assessment request for the following skill has been approved by your Supercoach  \r\n 	            <<createdby:UserSkill:item_id>>. <br/><br/>\r\n                Skill Name : <<skillname:UserSkill:item_id>><br/>\r\n                Skill Proficiency Level : <<Proficiency:UserSkill:item_id>><br/><br/>\r\n                Please <a href='<<BaseUrl:config>>myskill'>click here</a> for the details.<br/><br/>\r\n                Regards,<br/>\r\n                RMS Team<br/><br/>\r\n                **This is an autogenerated email.Kindly do not respond to this.**", "userskillemail" });

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 312L,
                columns: new[] { "template", "to" },
                values: new object[] { "Your skill <<skillname:UserSkill:item_id>> assessment has been approved by your Supercoach  <<createdby:UserSkill:item_id>> ", "userskillemail" });

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 323L,
                column: "template",
                value: "Your skill <<skillname:UserSkill:item_id>> assessment has been declined by your Supercoach <<createdby:UserSkill:item_id>>");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 324L,
                column: "template",
                value: "Dear User, <br/><br/> \r\n                    Your skill assessment approval has been declined by your Supercoach   <<createdby:UserSkill:item_id>>. <br/><br/> \r\n                    Skill Name : <<skillname:UserSkill:item_id>><br/>\r\n                    Skill Proficiency Level : <<Proficiency:UserSkill:item_id>><br/>\r\n                    Reason :  <<remarks:UserSkill:item_id>> <br/><br/>\r\n                    Please <a href='<<BaseUrl:config>>myskill'>click here</a> for the details and reach out to your Supercoach for any further clarifications.<br/><br/> \r\n                    Regards,<br/>\r\n                    RMS Team \r\n                    <br/><br/>** This is an autogenerated email. Kindly do not respond to this.**");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 42L,
                column: "template",
                value: "You have been assigned to the Project <<ProjectName:ResourceAllocationDetails:item_id>> on date <<due_date>>.");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 43L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n\r\n            You have been assigned to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> on date <<created_at>>.<br/>\r\n            The Project Allocation Period is:<br/>\r\n            Start Date: <<startdate:ResourceAllocationDetails:item_id>><br/> End Date: <<enddate:ResourceAllocationDetails:item_id>><br/> Hours: <<confirmedPerDayHours:ResourceAllocationDetails:item_id>>.<br/><br/>\r\n\r\n            Please <a href='<<BaseUrl:config>>myapproval'>click here</a> to view further details of the allocation and provide your agreement to the allocation.<br/><br/>\r\n\r\n            Please note, if you are unable to review the request for approval, it will be auto - approved by <<due_date>>.<br/><br/>\r\n\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 311L,
                columns: new[] { "template", "to" },
                values: new object[] { "Dear User,<br/><br/>\r\n            Your skill self-assessment request for the following skill has been approved by your Supercoach <<Approver:UserSkill:item_id>>. <br/><br/>\r\n\r\n            Skill Name : <<SkillName:UserSkill:item_id><br/>\r\n            Skill Proficiency Level : <<Proficiency:UserSkill:item_id>><br/><br/>\r\n\r\n            Please <a href='<<BaseUrl:config>>myskill'>click here</a> for the details.<br/><br/>\r\n\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.**", "<<Email:UserSkill:item_id>>" });

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 312L,
                columns: new[] { "template", "to" },
                values: new object[] { "Your skill Your <<SkillName:UserSkill:item_id>> assessment <<Status:UserSkill:item_id>> <<Approver:UserSkill:item_id>> ", "<<Email:UserSkill:item_id>>" });

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 323L,
                column: "template",
                value: "Your skill  <<skillname:UserSkill:item_id>> assessment  has been declined by your Supercoach  <<createdby:UserSkill:item_id>> ");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 324L,
                column: "template",
                value: "Dear User, <br/><br/> \r\n\r\n                    Your skill assessment approval has been declined by your Supercoach   <<createdby:UserSkill:item_id>>. <br/><br/> \r\n\r\n                    Skill Name : <<skillname:UserSkill:item_id>><br/>\r\n                    Skill Proficiency Level : <<Proficiency:UserSkill:item_id>><br/>\r\n                    Reason : <<remarks:UserSkill:item_id>> <br/><br/>\r\n\r\n                    Please <a href='<<BaseUrl:config>>myskill'>click here</a> for the details and reach out to your Supercoach for any further clarifications.<br/><br/> \r\n\r\n                    Regards, <br/>  \r\n                    RMS Team <br/>  \r\n                    ** This is an autogenerated email. Kindly do not respond to this.** ");

            migrationBuilder.InsertData(
                table: "NotificationTemplates",
                columns: new[] { "Id", "cc", "is_active", "link_id", "module", "notification_type", "sub_module", "subject", "subscription_role", "template", "to", "type" },
                values: new object[,]
                {
                    { 262L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear  User,<br/><br/>\r\n            You have been assigned to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> on date <<created_at>>. The Project Allocation Period is:\r\n            Start Date: <<startdate:ResourceAllocationDetails:item_id>><br/> End Date: <<enddate:ResourceAllocationDetails:item_id>><br/> Hours: <<totaleffort:ResourceAllocationDetails:item_id>>.<br/><br/>\r\n            Please <a href='<<BaseUrl:config>>myapproval'>click here</a> to view further details of the allocation and provide your agreement to the allocation.<br/><br/>\r\n            Please note, if you are unable to review the request for approval, it will be auto - approved by <<due_date>>.<br/><br/>\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n            **This is an autogenerated email.Kindly do not respond to this.**", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_FOR_HIS_ALLOCATION_TASK_TO_PROJECT" },
                    { 265L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "You have been assigned to the Project <<ProjectName:ResourceAllocationDetails:item_id>> on date <<due_date>>. ", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_FOR_HIS_ALLOCATION_TASK_TO_PROJECT" },
                    { 288L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "A", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_WITHDRAWS_REJECTION" },
                    { 289L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear  User,<br/><br/>\r\n            You have been assigned to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> . The Project Allocation Period is:<br/>\r\n            Start Date: <<startdate:ResourceAllocationDetails:item_id>><br/> End Date: <<enddate:ResourceAllocationDetails:item_id>><br/> Hours: <<totaleffort:ResourceAllocationDetails:item_id>>.<br/><br/>\r\n            Please <a href='<<BaseUrl:config>>myapproval'>click here</a> to view further details of the allocation and provide your agreement to the allocation.<br/><br/>\r\n            Please note, if you donot take any action, your allocation will be auto-approved by <<due_date>><br/><br/>\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n            ** This is an autogenerated email. Kindly do not respond to this.**", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_WITHDRAWS_REJECTION" }
                });
        }
    }
}
