using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace RMT.Notification.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class NotificationTemplate293295 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 157L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 158L);

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 141L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n                Resource allocation request has been rejected by reviewer: <<updated_by:GetUserInfo:updated_by>> for employee: <<empEmail:ResourceAllocationDetails:item_id>> \r\n                in the project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/>\r\n                Rejection reason: <<ReasonForRejectionProvidedByReviewer>><br/><br/>\r\n                Request you to please allocate another resource.<br/><br/>\r\n                Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=4'>click here</a> for the details.<br/><br/>\r\n                Regards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 293L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n                Your assignment to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been cancelled.\r\n                Your request for non acceptance of the allocation  has been approved by Reviewer <<updated_by>> .\r\n                <br/><br/>\r\n                Regards,<br/>RMS Team<br/><br/>** This is an autogenerated email. Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 295L,
                column: "template",
                value: "Your allocation to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been cancelled. Allocation Rejection request has been approved by Reviewer <<updated_by>> ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 141L,
                column: "template",
                value: "Dear User,<br/><br/>\r\nResource allocation request has been rejected by reviewer: <<updated_by:GetUserInfo:updated_by>> for employee: <<empEmail:ResourceAllocationDetails:item_id>> \r\nin the project: <<ProjectName:ResourceAllocationDetails:item_id>>.<br/>\r\nRejection reason: <<ReasonForRejectionProvidedByReviewer>><br/><br/>\r\nRequest you to please allocate another resource.<br/><br/>\r\nPlease <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=4'>click here</a> for the details.<br/><br/>\r\nRegards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 293L,
                column: "template",
                value: "Dear User,<br/><br/>\r\nYour assignment to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been cancelled.<br/><br/>\r\nRegards,<br/>RMS Team<br/><br/>** This is an autogenerated email. Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 295L,
                column: "template",
                value: "Your allocation to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been cancelled.");

            migrationBuilder.InsertData(
                table: "NotificationTemplates",
                columns: new[] { "Id", "cc", "is_active", "link_id", "module", "notification_type", "sub_module", "subject", "subscription_role", "template", "to", "type" },
                values: new object[,]
                {
                    { 157L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Dear User,<br/><br/>\r\nYour assignment to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been cancelled.<br/><br/>\r\nRegards,<br/>RMS Team<br/><br/>** This is an autogenerated email. Kindly do not respond to this.**", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_REVIEWER_APPROVED_EMPLOYEE_REJECTION" },
                    { 158L, null, true, null, "Notification", "PUSH", "Notification", "Project: <<ProjectName:ResourceAllocationDetails:item_id>> Allocations Update", null, "Your allocation to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been cancelled.", "employee_name_allocation_wf", "NOTIFICATION_TO_EMPLOYEE_REVIEWER_APPROVED_EMPLOYEE_REJECTION" }
                });
        }
    }
}
