using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace RMT.Notification.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class updateseeder2006 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 317L,
                column: "template",
                value: "Dear  User, <br/><br/>\r\n            <<userrequesting>> has assigned you Additional EL for project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> on date <<userassignmentdate>>\r\n             <br/> <br/> Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=0'>click here</a> for the details.  You may contact <<userrequesting>> to discuss your responsibilities on the project in RMS. <br/><br/>\r\n            Regards, <br/>\r\n            RMS Team<br/><br/>\r\n            ** This is an autogenerated email. Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 319L,
                column: "template",
                value: "Dear User,<br/>\r\n            You have been assigned as Delegate to <<delegateassignedby>> on  Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> on date <<delegateassignmentdate>>.\r\n           <br/> <br/> Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=0'>click here</a> for the details.You may contact <<delegateassignedby>> to discuss your responsibilities on the project in RMS. <br/><br/>\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n            ** This is an autogenerated email. Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 321L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n            <<userrequesting>> has assigned you as Additional Delegate to the  Additional EL for  Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> on date <<userassignmentdate>>\r\n            <br/> <br/> Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=0'>click here</a> for the details. You may contact <<userrequesting>> to discuss your responsibilities on the project in RMS. <br/> <br/>\r\n            Regards,<br/>\r\n            RMS Team<br/><br/>\r\n            ** This is an autogenerated email. Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 400L,
                column: "template",
                value: "Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> end date has been updated to <<enddate>>. Please take necessary actions.");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 401L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n                Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> end date has been updated to <<enddate>>.Please review allocations made to the project and take any necessary actions.\r\n                <br/><br/>\r\n                Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=0'>click here</a> for the details.\r\n                <br/><br/>\r\n                Regards,<br/>\r\n               RMS Team\r\n                <br/><br/>\r\n            **This is an autogenerated email.Kindly do not respond to this.* *");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 402L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n                    Your Allocation on the Project: <<projectname>> has been moved from Project Code <<oldprojectcode>> to new Project Code <<newprojectcode>>.<br/><br/>\r\n                    Please <a href='<<BaseUrl:config>>project-details/<<newpipelinecode##>>/<<newjobcode##>>?tab=0'>click here<a/> for the details.<br/><br/>\r\n                    Regards,<br/>\r\n                    RMS Team\r\n                    <br/><br/>** This is an autogenerated email. Kindly do not respond to this.**");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 317L,
                column: "template",
                value: "Dear  User, <br/>\r\n            <<userrequesting>> has assigned you Additional EL for project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> on date <<userassignmentdate>>\r\n             <br/> <br/> Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=0'>click here</a> for the details.  You may contact <<userrequesting>> to discuss your responsibilities on the project in RMS. <br/>\r\n            Regards, <br/>\r\n            <RMS Team> <br/>\r\n            ** This is an autogenerated email. Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 319L,
                column: "template",
                value: "Dear User,<br/>\r\n            You have been assigned as Delegate to <<delegateassignedby>> on  Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> on date <<delegateassignmentdate>>.\r\n           <br/> <br/> Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=0'>click here</a> for the details.  You may contact <<delegateassignedby>> to discuss your responsibilities on the project in RMS. <br/>\r\n            Regards,<br/>\r\n            <RMS Team><br/>\r\n            ** This is an autogenerated email. Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 321L,
                column: "template",
                value: "Dear User,<br/>\r\n            <<userrequesting>> has assigned you as Additional Delegate to the  Additional EL for  Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> on date <<userassignmentdate>>\r\n            <br/> <br/> Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=0'>click here</a> for the details. You may contact <<userrequesting>> to discuss your responsibilities on the project in RMS.  <br/>\r\n            Regards,<br/>\r\n            <RMS Team><br/>\r\n            ** This is an autogenerated email. Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 400L,
                column: "template",
                value: "Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> end date has been updated. New End Date is <<enddate>>. Please take necessary actions.");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 401L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n                Project <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> end date has been updated.<br/>\r\n                New end date is <<enddate>>.<br/>Please review allocations made to the project and take any necessary actions.\r\n                <br/><br/>\r\n                Please <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=0'>click here</a> for the details.\r\n                <br/><br/>\r\n                Regards,<br/>\r\n               RMS Team\r\n                <br/><br/>\r\n            **This is an autogenerated email.Kindly do not respond to this.* *");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 402L,
                column: "template",
                value: "Dear User,<br/><br/>\r\n                    Your Allocation on the Project: <<projectname>> has been moved from Project Code <<oldprojectcode>> to  new Project Code<<newprojectcode>>.<br/><br/>\r\n                    Please <a href='<<BaseUrl:config>>project-details/<<newpipelinecode##>>/<<newjobcode##>>?tab=0'>click here<a/> for the details.<br/><br/>\r\n                    Regards,<br/><br/>\r\n                    RMS Team\r\n                    <br/><br/>** This is an autogenerated email. Kindly do not respond to this.**");
        }
    }
}
