using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace RMT.Notification.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class JobcodeMovementContent1606 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "NotificationTemplateLinks",
                keyColumn: "Id",
                keyValue: 19L,
                column: "Link",
                value: "/project-details/<<newpipelinecode##>>/<<newjobcode##>>?tab=0");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 297L,
                column: "template",
                value: "Dear User,\r\n            <br/>\r\n            <br/>\r\n            Allocations on the Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> have been moved from Project Code <<jobcode>> to new Project Code <<newjobcode>> due to an update in WCGT of the Job Code.<br/><br/>\r\n            Please <a href='<<BaseUrl:config>>project-details/<<newpipelinecode##>>/<<newjobcode##>>?tab=0'>click here<a/> for the details.\r\n            <br/>\r\n            <br/>\r\n\r\n            Regards,\r\n            <br/>\r\n            RMS Team\r\n            <br/>\r\n            <br/>\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.InsertData(
                table: "NotificationTemplates",
                columns: new[] { "Id", "cc", "is_active", "link_id", "module", "notification_type", "sub_module", "subject", "subscription_role", "template", "to", "type" },
                values: new object[,]
                {
                    { 402L, null, true, null, "Notification", "EMAIL", "Notification", "Project: <<projectname>> Allocation Update", null, "Dear User,<br/><br/>\r\n                    Your Allocation on the Project: <<projectname>> has been moved from Project Code <<oldprojectcode>> to new Project Code <<newprojectcode>>.<br/><br/>\r\n                    Please <a href='<<BaseUrl:config>>project-details/<<newpipelinecode##>>/<<newjobcode##>>?tab=0'>click here<a/> for the details.<br/><br/>\r\n                    Regards,<br/><br/>\r\n                    RMS Team\r\n                    <br/><br/>** This is an autogenerated email. Kindly do not respond to this.**", "employee_jobcode_change", "PROJECT_JOB_CODE_CHANGE_INFORMATION_TO_EMPLOYEE" },
                    { 403L, null, true, 19L, "Notification", "PUSH", "Notification", "Project: <<projectname>> Allocation Update", null, "Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> allocations have been moved to new project code", "employee_jobcode_change", "PROJECT_JOB_CODE_CHANGE_INFORMATION_TO_EMPLOYEE" }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 402L);

            migrationBuilder.DeleteData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 403L);

            migrationBuilder.UpdateData(
                table: "NotificationTemplateLinks",
                keyColumn: "Id",
                keyValue: 19L,
                column: "Link",
                value: "/project-details/<<newPipelineCode##>>/<<newJobCode##>>?tab=0");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 297L,
                column: "template",
                value: "Dear User,\r\n            <br/>\r\n            <br/>\r\n            Allocations on the Project: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelinecode|jobcode>> have been moved from Project Code <<jobcode>> to new Project Code <<newjobcode>> due to an update in WCGT of the Job Code.<br/><br/>\r\n            Please <a href='<<BaseUrl:config>>project-details/<<newPipelineCode##>>/<<newJobCode##>>?tab=0'>click here<a/> for the details.\r\n            <br/>\r\n            <br/>\r\n\r\n            Regards,\r\n            <br/>\r\n            RMS Team\r\n            <br/>\r\n            <br/>\r\n\r\n            **This is an autogenerated email.Kindly do not respond to this.**");
        }
    }
}
