using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace RMT.Notification.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class seederupdate2206 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 42L,
                column: "template",
                value: "You have been assigned to the Project <<ProjectName:ResourceAllocationDetails:item_id>> on <<startdate:ResourceAllocationDetails:item_id>>.");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 43L,
                column: "template",
                value: "Dear User,<br/><br/>\r\nYou have been assigned to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> on <<created_at>>.<br/>\r\nThe Project Allocation Period is:<br/>\r\nStart Date: <<startdate:ResourceAllocationDetails:item_id>><br/> End Date: <<enddate:ResourceAllocationDetails:item_id>><br/> Hours: <<totaleffort:ResourceAllocationDetails:item_id>>.<br/><br/>\r\nPlease <a href='<<BaseUrl:config>>myapproval'>click here</a> to view further details of the allocation and provide your agreement to the allocation.<br/><br/>\r\nPlease note, if you donot take any action, your allocation will be auto-approved by <<due_date>>.<br/><br/>\r\nRegards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 42L,
                column: "template",
                value: "You have been assigned to the Project <<ProjectName:ResourceAllocationDetails:item_id>> on date <<created_at>>.");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 43L,
                column: "template",
                value: "Dear User,<br/><br/>\r\nYou have been assigned to the Project: <<ProjectName:ResourceAllocationDetails:item_id>> on date <<created_at>>.<br/>\r\nThe Project Allocation Period is:<br/>\r\nStart Date: <<startdate:ResourceAllocationDetails:item_id>><br/> End Date: <<enddate:ResourceAllocationDetails:item_id>><br/> Hours: <<totaleffort:ResourceAllocationDetails:item_id>>.<br/><br/>\r\nPlease <a href='<<BaseUrl:config>>myapproval'>click here</a> to view further details of the allocation and provide your agreement to the allocation.<br/><br/>\r\nPlease note, if you are unable to review the request for approval, it will be auto - approved by <<due_date>>.<br/><br/>\r\nRegards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**");
        }
    }
}
