using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace RMT.Notification.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class budgetTemplatev1 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 504L,
                column: "template",
                value: "Dear User,<br/><br/> \r\nProject: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> has consumed <<consumedtimesheetbudgetpct>>% of the budgeted hours in clocking.<br/><br/><a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=2'>Click here</a> for the details. Request you to review the future budget requirements and seek additional budget approval in WCGT if required. <br/><br/> \r\nRegards,<br/>RMS Team<br/><br/>** This is an autogenerated email. Kindly do not respond to this.**");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 504L,
                column: "template",
                value: "Dear User,<br/><br/> \r\nProject: <<ProjectName:GetProjectDetailsByPipelineCodeAndJobCode:pipelineCode|jobCode>> has consumed <<consumedtimesheetbudgetpct>>% of the budgeted hours in clocking.<br/><br/>Click here for the details. Request you to review the future budget requirements and seek additional budget approval in WCGT if required. <br/><br/> \r\nRegards,<br/>RMS Team<br/><br/>** This is an autogenerated email. Kindly do not respond to this.**");
        }
    }
}
