using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace RMT.Notification.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class supercoach_notif_change : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 141L,
                column: "to",
                value: "resource_requestor_allocation_wf,Reviewer,supercoach_email");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 142L,
                column: "to",
                value: "resource_requestor_allocation_wf,Reviewer,supercoach_email");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 145L,
                column: "to",
                value: "resource_requestor_allocation_wf,Reviewer,supercoach_email");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 146L,
                column: "to",
                value: "resource_requestor_allocation_wf,Reviewer,supercoach_email");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 276L,
                column: "template",
                value: " Allocation rejection by <<empEmail:ResourceAllocationDetails:item_id>> for Project: <<ProjectName:ResourceAllocationDetails:item_id>> have been approved by super coach <<updated_by>>. Please do new allocations");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 277L,
                column: "template",
                value: "Dear User,<br/><br/>\r\nThe Allocation request rejected by employee <<empEmail:ResourceAllocationDetails:item_id>> for Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been approved by Super Coach <<updated_by>>.\r\nRequest you to please allocate another resource.<br/><br/>\r\nPlease <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=4'>click here</a> for the details.<br/><br/>\r\nRegards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 410L,
                column: "template",
                value: "Resource Allocation Request for Project: <<ProjectName:ResourceAllocationDetails:item_id>>  have been approved by <<updated_by>>. ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 141L,
                column: "to",
                value: "resource_requestor_allocation_wf,Reviewer");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 142L,
                column: "to",
                value: "resource_requestor_allocation_wf,Reviewer");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 145L,
                column: "to",
                value: "resource_requestor_allocation_wf,Reviewer");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 146L,
                column: "to",
                value: "resource_requestor_allocation_wf,Reviewer");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 276L,
                column: "template",
                value: " Allocation rejection by <<empEmail:ResourceAllocationDetails:item_id>> for Project: <<ProjectName:ResourceAllocationDetails:item_id>> have been approved by reviewer <<updated_by>>. Please do new allocations");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 277L,
                column: "template",
                value: "Dear User,<br/><br/>\r\nThe Allocation request rejected by employee <<empEmail:ResourceAllocationDetails:item_id>> for Project: <<ProjectName:ResourceAllocationDetails:item_id>> has been approved by Reviewer <<updated_by>>.\r\nRequest you to please allocate another resource.<br/><br/>\r\nPlease <a href='<<BaseUrl:config>>project-details/<<pipelinecode##>>/<<jobcode##>>?tab=4'>click here</a> for the details.<br/><br/>\r\nRegards,<br/>RMS Team<br/><br/>**This is an autogenerated email.Kindly do not respond to this.**");

            migrationBuilder.UpdateData(
                table: "NotificationTemplates",
                keyColumn: "Id",
                keyValue: 410L,
                column: "template",
                value: "Resource Allocation Request for Project: <<ProjectName:ResourceAllocationDetails:item_id>>  have been approved by reviewer <<updated_by>>. ");
        }
    }
}
